import type { SupabaseSession } from "../../lib/supabase";
import { containsForbiddenAmbientContent, containsHealthDiagnosis, isHighStakesAutonomy, type AmbientAttentionBrief, type AmbientAttentionItem, type AmbientContextStatus, type AmbientEpistemicKind, type AmbientFoundationRead, type AmbientObservation, type AmbientObservationReview, type AmbientRuntimeContext, type AmbientSource, type AmbientUserPreference, type LeadershipCommitment } from "./types";

const env = (import.meta as ImportMeta & { env?: Record<string, unknown> }).env ?? {};
const supabaseUrl = (env.VITE_SUPABASE_URL as string | undefined)?.replace(/\/$/, "");
const supabaseAnonKey = env.VITE_SUPABASE_ANON_KEY as string | undefined;
type AmbientReadContext = AmbientRuntimeContext & { session: SupabaseSession };
function config() { if (!supabaseUrl || !supabaseAnonKey) throw new Error("O ambiente ainda não está conectado ao Supabase."); return { url: supabaseUrl, key: supabaseAnonKey }; }
function safeQuery(value: string) { return encodeURIComponent(value); }
async function readTable<T>(context: AmbientReadContext, table: string, extra = ""): Promise<T[]> { const c = config(); const response = await fetch(`${c.url}/rest/v1/${table}?select=*${extra}&organization_id=eq.${safeQuery(context.organizationId)}`, { headers: { apikey: c.key, Authorization: `Bearer ${context.session.access_token}` } }); if (!response.ok) throw new Error("Não foi possível carregar o contexto ambiente autorizado."); return (await response.json()) as T[]; }
async function writeTable<T>(context: AmbientReadContext, table: string, payload: Record<string, unknown>, method = "POST"): Promise<T> { const c = config(); if (containsForbiddenAmbientContent(payload) || containsHealthDiagnosis(payload) || isHighStakesAutonomy(payload)) throw new Error("Conteúdo não permitido para a fundação de inteligência ambiente."); const response = await fetch(`${c.url}/rest/v1/${table}`, { method, headers: { apikey: c.key, Authorization: `Bearer ${context.session.access_token}`, "Content-Type": "application/json", Prefer: "return=representation" }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error("Não foi possível persistir o registro ambiente."); return (await response.json()) as T; }
export async function readAmbientFoundation(context: AmbientReadContext): Promise<AmbientFoundationRead> { const org = `&order=created_at.desc`; const [sources, observations, reviews, preferences, attention, commitments, briefs] = await Promise.all([readTable<AmbientSource>(context, "ambient_source_registry", org), readTable<AmbientObservation>(context, "ambient_observations", org), readTable<AmbientObservationReview>(context, "ambient_observation_reviews", org), readTable<AmbientUserPreference>(context, "ambient_user_preferences", `&user_id=eq.${safeQuery(context.userId)}${org}`), readTable<AmbientAttentionItem>(context, "ambient_attention_items", `&owner_user_id=eq.${safeQuery(context.userId)}${org}`), readTable<LeadershipCommitment>(context, "ambient_leadership_commitments", `&owner_user_id=eq.${safeQuery(context.userId)}${org}`), readTable<AmbientAttentionBrief>(context, "ambient_attention_briefs", `&owner_user_id=eq.${safeQuery(context.userId)}${org}`)]); return { sources, observations, reviews, preferences, attention, commitments, briefs }; }
export async function recordAmbientObservation(context: AmbientReadContext, input: { observationType: string; epistemicKind: AmbientEpistemicKind; summary: string; observedAt: string; provenance: Record<string, unknown>; structuredValue?: Record<string, unknown>; sourceRegistryId?: string; confidence?: number; actorUserId?: string | null }): Promise<AmbientObservation> { if (context.userId !== context.session.user.id) throw new Error("Ambient actor must match the authenticated session."); if (input.epistemicKind === "machine_inferred" && !input.provenance.basis) throw new Error("Machine inference requires an explicit basis."); return writeTable<AmbientObservation>(context, "ambient_observations", { organization_id: context.organizationId, source_registry_id: input.sourceRegistryId ?? null, observation_type: input.observationType, epistemic_kind: input.epistemicKind, summary: input.summary, observed_at: input.observedAt, provenance: input.provenance, structured_value: input.structuredValue ?? {}, confidence: input.confidence ?? null, actor_user_id: input.actorUserId ?? null, created_by_user_id: context.userId }); }
export async function reviewAmbientObservation(context: AmbientReadContext, input: { observationId: string; reviewType: "confirm" | "correct" | "reject"; correctionSummary?: string; correctionValue?: Record<string, unknown>; reason?: string }): Promise<AmbientObservationReview> { return writeTable<AmbientObservationReview>(context, "ambient_observation_reviews", { organization_id: context.organizationId, observation_id: input.observationId, review_type: input.reviewType, reviewer_user_id: context.userId, correction_summary: input.correctionSummary ?? null, correction_value: input.correctionValue ?? null, reason: input.reason ?? null }); }
export async function setPrivateWorkPreference(context: AmbientReadContext, preferenceKey: string, preferenceValue: Record<string, unknown>): Promise<AmbientUserPreference> { return writeTable<AmbientUserPreference>(context, "ambient_user_preferences", { organization_id: context.organizationId, user_id: context.userId, preference_key: preferenceKey, preference_value: preferenceValue, privacy: "private" }); }
export async function createAttentionItem(context: AmbientReadContext, input: Pick<AmbientAttentionItem, "horizon" | "attention_type" | "title" | "rationale" | "priority"> & Partial<Pick<AmbientAttentionItem, "source_observation_id" | "due_at" | "context">>): Promise<AmbientAttentionItem> { return writeTable<AmbientAttentionItem>(context, "ambient_attention_items", { organization_id: context.organizationId, owner_user_id: context.userId, created_by_user_id: context.userId, ...input, human_required: true }); }
export async function createLeadershipCommitment(context: AmbientReadContext, input: { title: string; context?: string; impact?: string; horizon: AmbientAttentionItem["horizon"]; dueAt?: string }): Promise<LeadershipCommitment> { return writeTable<LeadershipCommitment>(context, "ambient_leadership_commitments", { organization_id: context.organizationId, owner_user_id: context.userId, created_by_user_id: context.userId, title: input.title, context: input.context ?? null, impact: input.impact ?? null, horizon: input.horizon, due_at: input.dueAt ?? null, provenance: { epistemic_kind: "human_declared" } }); }
export function valueBeforeInput<T>(input: { systemRecord?: T | null; question: string; fallback?: T | null }): { shouldAsk: boolean; value: T | null; message: string } { if (input.systemRecord != null) return { shouldAsk: false, value: input.systemRecord, message: "A youB já encontrou esse contexto em uma fonte autorizada." }; return { shouldAsk: true, value: input.fallback ?? null, message: input.question }; }
export function buildInsufficientBrief(organizationId: string, userId: string, horizon: AmbientAttentionBrief["horizon"], reason = "Não há contexto autorizado suficiente para preparar prioridades."): AmbientAttentionBrief { return { organization_id: organizationId, owner_user_id: userId, horizon, context_status: "insufficient" as AmbientContextStatus, insufficiency_reason: reason, focus_statement: null, priority_items: [], do_items: [], delegate_items: [], stop_items: [], source_observation_ids: [], generated_by: "human_reviewed_service" }; }
