-- youB — Bee Action Authorization + Impact Model V1 structural and hardening suite
-- Disposable staging only. Transactional fixtures, fail-fast assertions, no migration execution.
begin;
create temp table ctx(key text primary key, value uuid not null) on commit drop;
do $$ declare k text; begin
  foreach k in array array['bee_action_requests','intelligence_outcome_evidence'] loop
    if to_regclass('public.'||k) is null then raise exception 'missing Bee/Impact prerequisite: %', k; end if;
  end loop;
  if (select count(*) from auth.users) < 5 then raise exception 'suite requires five auth users'; end if;
end $$;
insert into ctx values
 ('org_a','11111111-1111-1111-1111-111111111111'),('org_b','22222222-2222-2222-2222-222222222222'),
 ('employee_a','11111111-0000-0000-0000-000000000001'),('employee_b','22222222-0000-0000-0000-000000000001'),
 ('recommendation_a','11111111-0000-0000-0000-000000000010'),('intervention_a','11111111-0000-0000-0000-000000000011'),
 ('action_a','11111111-0000-0000-0000-000000000012'),('outcome_a','11111111-0000-0000-0000-000000000013'),('outcome_b','22222222-0000-0000-0000-000000000013'),('outcome_b_probe','22222222-0000-0000-0000-000000000019'),
 ('signal_a','11111111-0000-0000-0000-000000000014'),('signal_b','22222222-0000-0000-0000-000000000014'),('signal_b_probe','22222222-0000-0000-0000-000000000017'),('evidence_a','11111111-0000-0000-0000-000000000015'),('evidence_b','22222222-0000-0000-0000-000000000015'),('evidence_b_probe','22222222-0000-0000-0000-000000000018'),('evidence_contradicts','11111111-0000-0000-0000-000000000016'),
 ('bee_private','11111111-0000-0000-0000-000000000020'),('bee_other','11111111-0000-0000-0000-000000000021');
insert into ctx select 'user_'||row_number() over(order by created_at),id from auth.users order by created_at limit 5;
insert into public.organizations(id,name,slug,plan,status) values ((select value from ctx where key='org_a'),'Bee Impact A','bee-impact-a','essencial','active'),((select value from ctx where key='org_b'),'Bee Impact B','bee-impact-b','essencial','active');
insert into public.memberships(organization_id,user_id,role) values ((select value from ctx where key='org_a'),(select value from ctx where key='user_1'),'admin_youb'),((select value from ctx where key='org_a'),(select value from ctx where key='user_2'),'diretoria'),((select value from ctx where key='org_a'),(select value from ctx where key='user_3'),'gestor'),((select value from ctx where key='org_a'),(select value from ctx where key='user_4'),'colaborador'),((select value from ctx where key='org_a'),(select value from ctx where key='user_5'),'rh');
insert into public.employees(id,organization_id,auth_user_id,full_name,email,manager_employee_id) values ((select value from ctx where key='employee_a'),(select value from ctx where key='org_a'),null,'Bee Employee A','bee-a@example.invalid',null),((select value from ctx where key='employee_b'),(select value from ctx where key='org_b'),null,'Bee Employee B','bee-b@example.invalid',null);
insert into public.intelligence_signals(id,organization_id,employee_id,signal_type,source_type) values ((select value from ctx where key='signal_a'),(select value from ctx where key='org_a'),(select value from ctx where key='employee_a'),'fixture','test'),((select value from ctx where key='signal_b'),(select value from ctx where key='org_b'),(select value from ctx where key='employee_b'),'fixture','test'),((select value from ctx where key='signal_b_probe'),(select value from ctx where key='org_b'),(select value from ctx where key='employee_b'),'fixture_probe','test');
insert into public.intelligence_evidence(id,organization_id,signal_id,evidence_type,summary,relation,independence_group,source_type) values ((select value from ctx where key='evidence_a'),(select value from ctx where key='org_a'),(select value from ctx where key='signal_a'),'documented','fixture','supports','bee-source','test'),((select value from ctx where key='evidence_contradicts'),(select value from ctx where key='org_a'),(select value from ctx where key='signal_a'),'qualitative','contradictory fixture','contradicts','independent-source','test'),((select value from ctx where key='evidence_b'),(select value from ctx where key='org_b'),(select value from ctx where key='signal_b'),'documented','tenant B fixture','supports','bee-source','test'),((select value from ctx where key='evidence_b_probe'),(select value from ctx where key='org_b'),(select value from ctx where key='signal_b_probe'),'documented','tenant B RLS probe evidence','supports','probe-source','test');
insert into public.intelligence_recommendations(id,organization_id,employee_id,title) values ((select value from ctx where key='recommendation_a'),(select value from ctx where key='org_a'),(select value from ctx where key='employee_a'),'Bee fixture recommendation');
insert into public.intelligence_interventions(id,organization_id,recommendation_id,employee_id,intervention_type,title) values ((select value from ctx where key='intervention_a'),(select value from ctx where key='org_a'),(select value from ctx where key='recommendation_a'),(select value from ctx where key='employee_a'),'fixture','Bee fixture intervention');
insert into public.intelligence_actions(id,organization_id,intervention_id,action_type,title,assignee_employee_id) values ((select value from ctx where key='action_a'),(select value from ctx where key='org_a'),(select value from ctx where key='intervention_a'),'fixture','Bee fixture action',(select value from ctx where key='employee_a'));
insert into public.intelligence_outcomes(id,organization_id,intervention_id,action_id,outcome_type) values ((select value from ctx where key='outcome_a'),(select value from ctx where key='org_a'),(select value from ctx where key='intervention_a'),(select value from ctx where key='action_a'),'fixture'),((select value from ctx where key='outcome_b'),(select value from ctx where key='org_b'),null,null,'tenant_b_fixture'),((select value from ctx where key='outcome_b_probe'),(select value from ctx where key='org_b'),null,null,'tenant_b_rls_probe');
insert into public.intelligence_outcome_evidence(organization_id,outcome_id,evidence_id,relation) values ((select value from ctx where key='org_a'),(select value from ctx where key='outcome_a'),(select value from ctx where key='evidence_a'),'supports'),((select value from ctx where key='org_a'),(select value from ctx where key='outcome_a'),(select value from ctx where key='evidence_contradicts'),'contradicts'),((select value from ctx where key='org_b'),(select value from ctx where key='outcome_b'),(select value from ctx where key='evidence_b'),'supports');
insert into public.bee_action_requests(id,organization_id,requester_user_id,action_key,capability_level,risk_level,authorization_requirement,authorization_status,purpose,target_scope_type,request_payload,execution_payload,execution_result) values ((select value from ctx where key='bee_private'),(select value from ctx where key='org_a'),(select value from ctx where key='user_4'),'private_context','explain','informational','none','not_required','Private collaborator context','employee','{}','{}','{}'),((select value from ctx where key='bee_other'),(select value from ctx where key='org_a'),(select value from ctx where key='user_1'),'admin_context','explain','informational','none','not_required','Admin context','organization','{}','{}','{}');

create or replace function pg_temp.assert_true(label text, condition boolean) returns void language plpgsql as $$ begin if condition is distinct from true then raise exception 'FAIL-FAST assertion: %',label; end if; end; $$;
create or replace function pg_temp.try_bee(p_cap text,p_risk text,p_req text,p_auth text,p_exec text,p_scope text,p_sensitivity text,p_confirmed_by uuid,p_confirmed_at timestamptz,p_approved_by uuid,p_approved_at timestamptz,p_executed_at timestamptz) returns boolean language plpgsql security invoker as $$ declare probe uuid; begin begin insert into public.bee_action_requests(organization_id,requester_user_id,requester_employee_id,action_key,capability_level,risk_level,authorization_requirement,authorization_status,execution_status,purpose,target_scope_type,target_scope_ref,target_employee_id,sensitivity,confirmed_by,confirmed_at,approved_by,approved_at,executed_at) values((select value from ctx where key='org_a'),(select value from ctx where key='user_1'),(select value from ctx where key='employee_a'),'qa_'||md5(random()::text),p_cap,p_risk,p_req,p_auth,p_exec,'QA request',p_scope,'descriptive-ref',(select value from ctx where key='employee_a'),p_sensitivity,p_confirmed_by,p_confirmed_at,p_approved_by,p_approved_at,p_executed_at) returning id into probe; delete from public.bee_action_requests where id=probe; return true; exception when others then return false; end; end; $$;
create or replace function pg_temp.try_outcome(p_level text,p_claim text,p_measure text,p_validation text,p_financial numeric,p_currency text,p_method text,p_validated_by uuid,p_validated_at timestamptz) returns boolean language plpgsql security invoker as $$ declare probe uuid; begin begin insert into public.intelligence_outcomes(organization_id,outcome_type,outcome_level,claim_strength,measurement_kind,validation_status,financial_value,currency,measurement_methodology,validated_by,validated_at,context) values((select value from ctx where key='org_a'),'qa_probe',p_level,p_claim,p_measure,p_validation,p_financial,p_currency,p_method,p_validated_by,p_validated_at,'{}') returning id into probe; delete from public.intelligence_outcomes where id=probe; return true; exception when others then return false; end; end; $$;
create or replace function pg_temp.invalid_bee_json_shape() returns boolean language plpgsql security invoker as $$ begin begin insert into public.bee_action_requests(organization_id,requester_user_id,action_key,capability_level,risk_level,authorization_requirement,authorization_status,purpose,target_scope_type,request_payload) values((select value from ctx where key='org_a'),(select value from ctx where key='user_1'),'invalid_json','observe','informational','none','not_required','QA invalid JSON','employee','[]'); return true; exception when others then return false; end; end; $$;
create or replace function pg_temp.outcome_rls_probe() returns boolean language plpgsql security invoker as $$ declare msg text; begin begin insert into public.intelligence_outcomes(organization_id,outcome_type,outcome_level,claim_strength,measurement_kind,validation_status,metric_key,metric_label,metric_unit,observed_value,window_start,window_end,context) values((select value from ctx where key='org_b'),'valid_org_b_probe','business','observed','measured','reviewed','qa_metric','QA Metric','count',1,'2026-09-01','2026-09-02','{}'); return false; exception when others then get stacked diagnostics msg = message_text; return msg ilike '%row-level security%'; end; end; $$;
create or replace function pg_temp.outcome_evidence_rls_probe() returns boolean language plpgsql security invoker as $$ declare msg text; begin begin insert into public.intelligence_outcome_evidence(organization_id,outcome_id,evidence_id,relation) values((select value from ctx where key='org_b'),(select value from ctx where key='outcome_b_probe'),(select value from ctx where key='evidence_b_probe'),'supports'); return false; exception when others then get stacked diagnostics msg = message_text; return msg ilike '%row-level security%'; end; end; $$;
create or replace function pg_temp.outcome_evidence_fk_probe() returns boolean language plpgsql security invoker as $$ declare msg text; begin begin insert into public.intelligence_outcome_evidence(organization_id,outcome_id,evidence_id,relation) values((select value from ctx where key='org_a'),(select value from ctx where key='outcome_a'),(select value from ctx where key='evidence_b'),'supports'); return false; exception when others then get stacked diagnostics msg = message_text; return msg ilike '%foreign key%' or msg ilike '%violates%'; end; end; $$;
create or replace function pg_temp.cross_tenant_bee_rls_probe() returns boolean language plpgsql security invoker as $$ declare msg text; begin begin insert into public.bee_action_requests(organization_id,requester_user_id,requester_employee_id,action_key,capability_level,risk_level,authorization_requirement,authorization_status,purpose,target_scope_type,target_employee_id,request_payload,execution_payload,execution_result) values((select value from ctx where key='org_b'),(select value from ctx where key='user_1'),'22222222-0000-0000-0000-000000000001','tenant_b_action','explain','informational','none','not_required','Valid tenant B request','employee','22222222-0000-0000-0000-000000000001','{}','{}','{}'); return false; exception when others then get stacked diagnostics msg = message_text; return msg ilike '%row-level security%'; end; end; $$;

create or replace function pg_temp.rh_valid_bee_request() returns boolean language plpgsql security invoker as $$ declare probe uuid; begin begin insert into public.bee_action_requests(organization_id,requester_user_id,requester_employee_id,action_key,capability_level,risk_level,authorization_requirement,authorization_status,execution_status,purpose,target_scope_type,target_scope_ref,target_employee_id,sensitivity,request_payload,execution_payload,execution_result) values((select value from ctx where key='org_a'),(select value from ctx where key='user_5'),(select value from ctx where key='employee_a'),'rh_qa_action','explain','informational','none','not_required','not_started','RH QA request','employee','rh-qa-ref',(select value from ctx where key='employee_a'),'standard','{}','{}','{}') returning id into probe; delete from public.bee_action_requests where id=probe; return true; exception when others then return false; end; end; $$;
create or replace function pg_temp.rh_valid_outcome() returns boolean language plpgsql security invoker as $$ declare probe uuid; begin begin insert into public.intelligence_outcomes(organization_id,outcome_type,status,details,measured_at,outcome_level,claim_strength,measurement_kind,validation_status,metric_key,metric_label,metric_unit,observed_value,window_start,window_end,context) values((select value from ctx where key='org_a'),'rh_qa_outcome','observed','{}',now(),'business','observed','measured','reviewed','rh_metric','RH QA Metric','count',1,'2026-09-01','2026-09-02','{}') returning id into probe; delete from public.intelligence_outcomes where id=probe; return true; exception when others then return false; end; end; $$;

set local role authenticated;
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_1'),true);
-- Every Bee vocabulary: valid values and invalid values, independently asserted.
select pg_temp.assert_true('capability observe valid',pg_temp.try_bee('observe','informational','none','not_required','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('capability explain valid',pg_temp.try_bee('explain','informational','none','not_required','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('capability ask valid',pg_temp.try_bee('ask','informational','none','not_required','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('capability recommend valid',pg_temp.try_bee('recommend','informational','none','not_required','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('capability prepare valid',pg_temp.try_bee('prepare','informational','none','not_required','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('capability execute valid with approval',pg_temp.try_bee('execute','operational','approval','approved','not_started','employee','standard',null,null,(select value from ctx where key='user_1'),now(),null));
select pg_temp.assert_true('invalid capability rejected',not pg_temp.try_bee('invalid','informational','none','not_required','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('risk informational valid',pg_temp.try_bee('observe','informational','none','not_required','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('risk personal_reversible valid',pg_temp.try_bee('ask','personal_reversible','confirmation','awaiting_confirmation','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('risk operational valid',pg_temp.try_bee('prepare','operational','confirmation','awaiting_confirmation','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('risk sensitive valid only with approval',pg_temp.try_bee('execute','sensitive','approval','awaiting_approval','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('risk prohibited_autonomous valid as rejected',pg_temp.try_bee('observe','prohibited_autonomous','prohibited','rejected','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('invalid risk rejected',not pg_temp.try_bee('observe','invalid','none','not_required','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('authorization none valid only not_required',pg_temp.try_bee('observe','informational','none','not_required','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('authorization confirmation valid awaiting',pg_temp.try_bee('ask','personal_reversible','confirmation','awaiting_confirmation','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('authorization approval valid awaiting',pg_temp.try_bee('prepare','operational','approval','awaiting_approval','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('authorization prohibited valid rejected',pg_temp.try_bee('observe','prohibited_autonomous','prohibited','rejected','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('invalid authorization requirement rejected',not pg_temp.try_bee('observe','informational','invalid','not_required','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('scope employee valid',pg_temp.try_bee('observe','informational','none','not_required','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('scope team valid',pg_temp.try_bee('observe','informational','none','not_required','not_started','team','standard',null,null,null,null,null));
select pg_temp.assert_true('scope area valid',pg_temp.try_bee('observe','informational','none','not_required','not_started','area','standard',null,null,null,null,null));
select pg_temp.assert_true('scope position valid',pg_temp.try_bee('observe','informational','none','not_required','not_started','position','standard',null,null,null,null,null));
select pg_temp.assert_true('scope process valid',pg_temp.try_bee('observe','informational','none','not_required','not_started','process','standard',null,null,null,null,null));
select pg_temp.assert_true('scope unit valid',pg_temp.try_bee('observe','informational','none','not_required','not_started','unit','standard',null,null,null,null,null));
select pg_temp.assert_true('scope organization valid',pg_temp.try_bee('observe','informational','none','not_required','not_started','organization','standard',null,null,null,null,null));
select pg_temp.assert_true('invalid scope rejected',not pg_temp.try_bee('observe','informational','none','not_required','not_started','invalid','standard',null,null,null,null,null));
select pg_temp.assert_true('sensitivity standard valid',pg_temp.try_bee('observe','informational','none','not_required','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('sensitivity restricted valid',pg_temp.try_bee('observe','informational','none','not_required','not_started','employee','restricted',null,null,null,null,null));
select pg_temp.assert_true('sensitivity highly_sensitive valid',pg_temp.try_bee('observe','informational','none','not_required','not_started','employee','highly_sensitive',null,null,null,null,null));
select pg_temp.assert_true('invalid sensitivity rejected',not pg_temp.try_bee('observe','informational','none','not_required','not_started','employee','invalid',null,null,null,null,null));
select pg_temp.assert_true('status not_required valid',pg_temp.try_bee('observe','informational','none','not_required','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('status awaiting_confirmation valid',pg_temp.try_bee('ask','personal_reversible','confirmation','awaiting_confirmation','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('status awaiting_approval valid',pg_temp.try_bee('prepare','operational','approval','awaiting_approval','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('status approved valid with provenance',pg_temp.try_bee('ask','personal_reversible','confirmation','approved','not_started','employee','standard',(select value from ctx where key='user_1'),now(),null,null,null));
select pg_temp.assert_true('status rejected valid',pg_temp.try_bee('ask','personal_reversible','confirmation','rejected','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('status expired valid',pg_temp.try_bee('prepare','operational','approval','expired','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('invalid authorization status rejected',not pg_temp.try_bee('observe','informational','none','invalid','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('execution not_started valid',pg_temp.try_bee('observe','informational','none','not_required','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('execution ready valid after confirmation approval',pg_temp.try_bee('ask','personal_reversible','confirmation','approved','ready','employee','standard',(select value from ctx where key='user_1'),now(),null,null,null));
select pg_temp.assert_true('execution executing valid after approval',pg_temp.try_bee('prepare','operational','approval','approved','executing','employee','standard',null,null,(select value from ctx where key='user_1'),now(),null));
select pg_temp.assert_true('execution completed valid with executed_at',pg_temp.try_bee('prepare','operational','approval','approved','completed','employee','standard',null,null,(select value from ctx where key='user_1'),now(),now()));
select pg_temp.assert_true('execution failed valid',pg_temp.try_bee('ask','personal_reversible','confirmation','awaiting_confirmation','failed','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('execution cancelled valid',pg_temp.try_bee('prepare','operational','approval','awaiting_approval','cancelled','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('invalid execution status rejected',not pg_temp.try_bee('observe','informational','none','not_required','invalid','employee','standard',null,null,null,null,null));
-- State-machine hardening: invalid combinations must fail for both confirmation and approval.
select pg_temp.assert_true('none cannot await confirmation',not pg_temp.try_bee('observe','informational','none','awaiting_confirmation','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('confirmation cannot be not_required',not pg_temp.try_bee('ask','personal_reversible','confirmation','not_required','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('approval cannot await confirmation',not pg_temp.try_bee('prepare','operational','approval','awaiting_confirmation','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('prohibited must be rejected',not pg_temp.try_bee('observe','prohibited_autonomous','prohibited','approved','not_started','employee','standard',null,null,(select value from ctx where key='user_1'),now(),null));
select pg_temp.assert_true('prohibited cannot execute',not pg_temp.try_bee('observe','prohibited_autonomous','prohibited','rejected','ready','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('confirmation approved requires confirmed_by and confirmed_at',not pg_temp.try_bee('ask','personal_reversible','confirmation','approved','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('approval approved requires approved_by and approved_at',not pg_temp.try_bee('prepare','operational','approval','approved','not_started','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('confirmation ready requires approved status',not pg_temp.try_bee('ask','personal_reversible','confirmation','awaiting_confirmation','ready','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('confirmation executing requires approved status',not pg_temp.try_bee('ask','personal_reversible','confirmation','awaiting_confirmation','executing','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('confirmation completed requires approved status',not pg_temp.try_bee('ask','personal_reversible','confirmation','awaiting_confirmation','completed','employee','standard',null,null,null,null,now()));
select pg_temp.assert_true('approval ready requires approved status',not pg_temp.try_bee('prepare','operational','approval','awaiting_approval','ready','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('approval executing requires approved status',not pg_temp.try_bee('prepare','operational','approval','awaiting_approval','executing','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('approval completed requires approved status',not pg_temp.try_bee('prepare','operational','approval','awaiting_approval','completed','employee','standard',null,null,null,null,now()));
select pg_temp.assert_true('rejected cannot be ready',not pg_temp.try_bee('ask','personal_reversible','confirmation','rejected','ready','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('expired cannot be executing',not pg_temp.try_bee('prepare','operational','approval','expired','executing','employee','standard',null,null,null,null,null));
select pg_temp.assert_true('sensitive execute cannot use confirmation only',not pg_temp.try_bee('execute','sensitive','confirmation','approved','not_started','employee','standard',(select value from ctx where key='user_1'),now(),null,null,null));
select pg_temp.assert_true('completed requires executed_at',not pg_temp.try_bee('prepare','operational','approval','approved','completed','employee','standard',null,null,(select value from ctx where key='user_1'),now(),null));
select pg_temp.assert_true('Bee JSON objects required',not pg_temp.invalid_bee_json_shape());
select pg_temp.assert_true('no Bee request creates action or intervention',((select count(*) from public.intelligence_actions where organization_id=(select value from ctx where key='org_a'))=1 and (select count(*) from public.intelligence_interventions where organization_id=(select value from ctx where key='org_a'))=1));

-- Impact vocabularies: every valid value plus invalid values.
select pg_temp.assert_true('outcome execution valid',pg_temp.try_outcome('execution','observed','measured','unvalidated',null,null,null,null,null));
select pg_temp.assert_true('outcome learning valid',pg_temp.try_outcome('learning','observed','measured','unvalidated',null,null,null,null,null));
select pg_temp.assert_true('outcome application valid',pg_temp.try_outcome('application','observed','measured','unvalidated',null,null,null,null,null));
select pg_temp.assert_true('outcome capability valid',pg_temp.try_outcome('capability','observed','measured','unvalidated',null,null,null,null,null));
select pg_temp.assert_true('outcome people valid',pg_temp.try_outcome('people','observed','measured','unvalidated',null,null,null,null,null));
select pg_temp.assert_true('outcome business valid',pg_temp.try_outcome('business','observed','measured','unvalidated',null,null,null,null,null));
select pg_temp.assert_true('outcome financial valid with methodology',pg_temp.try_outcome('financial','associated','estimated','unvalidated',10,'BRL','reviewed methodology',null,null));
select pg_temp.assert_true('invalid outcome level rejected',not pg_temp.try_outcome('invalid','observed','measured','unvalidated',null,null,null,null,null));
select pg_temp.assert_true('claim observed valid',pg_temp.try_outcome('business','observed','measured','unvalidated',null,null,null,null,null));
select pg_temp.assert_true('claim associated valid',pg_temp.try_outcome('business','associated','measured','unvalidated',null,null,null,null,null));
select pg_temp.assert_true('claim contribution_supported valid',pg_temp.try_outcome('business','contribution_supported','measured','reviewed',null,null,null,null,null));
select pg_temp.assert_true('claim causal_validated valid with methodology',pg_temp.try_outcome('business','causal_validated','measured','validated',null,null,'causal methodology',(select value from ctx where key='user_1'),now()));
select pg_temp.assert_true('invalid claim rejected',not pg_temp.try_outcome('business','invalid','measured','unvalidated',null,null,null,null,null));
select pg_temp.assert_true('measurement measured valid',pg_temp.try_outcome('business','observed','measured','unvalidated',null,null,null,null,null));
select pg_temp.assert_true('measurement estimated valid',pg_temp.try_outcome('business','observed','estimated','unvalidated',null,null,null,null,null));
select pg_temp.assert_true('invalid measurement rejected',not pg_temp.try_outcome('business','observed','invalid','unvalidated',null,null,null,null,null));
select pg_temp.assert_true('validation unvalidated valid',pg_temp.try_outcome('business','observed','measured','unvalidated',null,null,null,null,null));
select pg_temp.assert_true('validation reviewed valid',pg_temp.try_outcome('business','observed','measured','reviewed',null,null,null,null,null));
select pg_temp.assert_true('validation validated valid with provenance',pg_temp.try_outcome('business','observed','measured','validated',null,null,null,(select value from ctx where key='user_1'),now()));
select pg_temp.assert_true('invalid validation rejected',not pg_temp.try_outcome('business','observed','measured','invalid',null,null,null,null,null));
select pg_temp.assert_true('validated requires validated_by and validated_at',not pg_temp.try_outcome('business','observed','measured','validated',null,null,null,null,null));
select pg_temp.assert_true('causal validated requires methodology',not pg_temp.try_outcome('business','causal_validated','measured','validated',null,null,null,(select value from ctx where key='user_1'),now()));
select pg_temp.assert_true('financial value without currency fails',not pg_temp.try_outcome('business','associated','estimated','unvalidated',10,null,'financial methodology',null,null));
select pg_temp.assert_true('financial value without methodology fails',not pg_temp.try_outcome('business','associated','estimated','unvalidated',10,'BRL',null,null,null));
select pg_temp.assert_true('financial negative value fails',not pg_temp.try_outcome('business','associated','estimated','unvalidated',-1,'BRL','financial methodology',null,null));
select pg_temp.assert_true('financial value with currency and methodology succeeds',pg_temp.try_outcome('business','associated','estimated','unvalidated',10,'BRL','financial methodology',null,null));

-- Direct RLS probes use fully valid tenant-B payloads; FK integrity remains a separate probe.
select pg_temp.assert_true('admin org A outcome insert into org B denied by RLS',pg_temp.outcome_rls_probe());
select pg_temp.assert_true('admin org A valid org B junction denied by RLS',pg_temp.outcome_evidence_rls_probe());
select pg_temp.assert_true('cross-tenant outcome evidence rejected by FK',pg_temp.outcome_evidence_fk_probe());
select pg_temp.assert_true('contradictory evidence relation is preserved',((select count(*) from public.intelligence_outcome_evidence where organization_id=(select value from ctx where key='org_a') and outcome_id=(select value from ctx where key='outcome_a') and relation='contradicts')=1));

select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_5'),true);
select pg_temp.assert_true('RH org A outcome insert into org B denied by RLS',pg_temp.outcome_rls_probe());
select pg_temp.assert_true('RH org A valid org B junction denied by RLS',pg_temp.outcome_evidence_rls_probe());
select pg_temp.assert_true('RH inserts and removes valid own-tenant Bee request',pg_temp.rh_valid_bee_request());
select pg_temp.assert_true('RH inserts and removes valid own-tenant Outcome',pg_temp.rh_valid_outcome());
select pg_temp.assert_true('RH reads own tenant Bee requests',((select count(*) from public.bee_action_requests where organization_id=(select value from ctx where key='org_a'))=2));
select pg_temp.assert_true('RH cross-tenant Bee request denied by RLS',pg_temp.cross_tenant_bee_rls_probe());
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_2'),true);
create or replace function pg_temp.probe_bee_write() returns boolean language plpgsql security invoker as $$ begin begin insert into public.bee_action_requests(organization_id,requester_user_id,action_key,capability_level,risk_level,authorization_requirement,purpose,target_scope_type) values((select value from ctx where key='org_a'),(select value from ctx where key='user_4'),'x','explain','informational','none','x','employee');return true;exception when others then return false;end;end; $$;
create or replace function pg_temp.probe_outcome_write() returns boolean language plpgsql security invoker as $$ begin begin insert into public.intelligence_outcomes(organization_id,outcome_type) values((select value from ctx where key='org_a'),'probe');return true;exception when others then return false;end;end; $$;
select pg_temp.assert_true('diretoria cannot write Bee requests',not pg_temp.probe_bee_write());
select pg_temp.assert_true('diretoria can read Outcomes',((select count(*) from public.intelligence_outcomes where organization_id=(select value from ctx where key='org_a'))=1));
select pg_temp.assert_true('diretoria cannot write Outcomes',not pg_temp.probe_outcome_write());
select pg_temp.assert_true('diretoria cannot read private collaborator request',((select count(*) from public.bee_action_requests where id=(select value from ctx where key='bee_private'))=0));
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_3'),true);
select pg_temp.assert_true('gestor cannot write Bee requests',not pg_temp.probe_bee_write());
select pg_temp.assert_true('gestor cannot write Outcomes',not pg_temp.probe_outcome_write());
select pg_temp.assert_true('gestor cannot read private collaborator request',((select count(*) from public.bee_action_requests where id=(select value from ctx where key='bee_private'))=0));
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_4'),true);
select pg_temp.assert_true('collaborator cannot write Bee requests',not pg_temp.probe_bee_write());
select pg_temp.assert_true('collaborator cannot write Outcomes',not pg_temp.probe_outcome_write());
select pg_temp.assert_true('requester reads own Bee request',((select count(*) from public.bee_action_requests where id=(select value from ctx where key='bee_private'))=1));
select pg_temp.assert_true('requester cannot read another users request',((select count(*) from public.bee_action_requests where id=(select value from ctx where key='bee_other'))=0));
select pg_temp.assert_true('collaborator cannot read generic request list',((select count(*) from public.bee_action_requests)=1));
rollback;
