-- youB — Evidence + Recommendation Operational V1 QA
-- Transactional disposable fixtures; fail-fast; no staging/production execution.
begin;
create temp table ctx(key text primary key,value uuid not null) on commit drop;
do $$ declare k text; begin foreach k in array array['intelligence_evidence_assessments','intelligence_evidence_assessment_evidence','intelligence_recommendation_readings','intelligence_recommendation_assessments','intelligence_recommendation_hypotheses','intelligence_recommendation_evidence'] loop if to_regclass('public.'||k) is null then raise exception 'missing prerequisite: %',k; end if; end loop; if (select count(*) from auth.users)<5 then raise exception 'suite requires five auth users'; end if; end $$;
insert into ctx values
 ('org_a','77777777-7777-7777-7777-777777777777'),('org_b','88888888-8888-8888-8888-888888888888'),('employee_a','77777777-0000-0000-0000-000000000001'),('employee_b','88888888-0000-0000-0000-000000000001'),
 ('reading_a','77777777-0000-0000-0000-000000000011'),('reading_b','88888888-0000-0000-0000-000000000011'),('hypothesis_a','77777777-0000-0000-0000-000000000012'),('hypothesis_b','88888888-0000-0000-0000-000000000012'),
 ('evidence_a1','77777777-0000-0000-0000-000000000021'),('evidence_a2','77777777-0000-0000-0000-000000000022'),('evidence_a3','77777777-0000-0000-0000-000000000023'),('evidence_b','88888888-0000-0000-0000-000000000021'),
 ('assessment_a','77777777-0000-0000-0000-000000000031'),('assessment_draft','77777777-0000-0000-0000-000000000033'),('assessment_b','88888888-0000-0000-0000-000000000031'),('assessment_other','77777777-0000-0000-0000-000000000032'),('recommendation_a','77777777-0000-0000-0000-000000000041'),('recommendation_b','88888888-0000-0000-0000-000000000041'),('recommendation_other','77777777-0000-0000-0000-000000000042'),('memory_assessment','77777777-0000-0000-0000-000000000051'),('memory_recommendation','77777777-0000-0000-0000-000000000052');
insert into ctx select 'user_'||row_number() over(order by created_at),id from auth.users order by created_at limit 5;
insert into public.organizations(id,name,slug,plan,status) values((select value from ctx where key='org_a'),'Evidence Recommendation A','evidence-rec-a','essencial','active'),((select value from ctx where key='org_b'),'Evidence Recommendation B','evidence-rec-b','essencial','active');
insert into public.memberships(organization_id,user_id,role) values((select value from ctx where key='org_a'),(select value from ctx where key='user_1'),'admin_youb'),((select value from ctx where key='org_a'),(select value from ctx where key='user_2'),'diretoria'),((select value from ctx where key='org_a'),(select value from ctx where key='user_3'),'gestor'),((select value from ctx where key='org_a'),(select value from ctx where key='user_4'),'colaborador'),((select value from ctx where key='org_a'),(select value from ctx where key='user_5'),'rh');
insert into public.employees(id,organization_id,auth_user_id,full_name,email,manager_employee_id) values((select value from ctx where key='employee_a'),(select value from ctx where key='org_a'),null,'Evidence Employee A','evidence-a@example.invalid',null),((select value from ctx where key='employee_b'),(select value from ctx where key='org_b'),null,'Evidence Employee B','evidence-b@example.invalid',null);
insert into public.intelligence_organizational_readings(id,organization_id,reading_type,scope_type,scope_ref,title,description,status,knowledge_kind,observation_window_start,observation_window_end,detected_at,source_summary,context) values((select value from ctx where key='reading_a'),(select value from ctx where key='org_a'),'movement','team','team-a','Turnover movement','Turnover increased in two teams.','open','interpreted','2026-01-01','2026-01-31','2026-02-01','Manual and quantitative sources.','{"tenure":"6-18m"}'),((select value from ctx where key='reading_b'),(select value from ctx where key='org_b'),'pattern','organization','org-b','Tenant B pattern','Tenant B fixture.','open','interpreted','2026-01-01','2026-01-31','2026-02-01','Tenant B source.','{}');
insert into public.intelligence_organizational_reading_hypotheses(id,organization_id,reading_id,hypothesis_statement,status,knowledge_kind,context,created_by) values((select value from ctx where key='hypothesis_a'),(select value from ctx where key='org_a'),(select value from ctx where key='reading_a'),'Leadership change may be contributing.','proposed','hypothesis','{"not_causal_confirmation":true}',(select value from ctx where key='user_1')),((select value from ctx where key='hypothesis_b'),(select value from ctx where key='org_b'),(select value from ctx where key='reading_b'),'Tenant B hypothesis.','proposed','hypothesis','{}',(select value from ctx where key='user_1'));
insert into public.intelligence_evidence(id,organization_id,evidence_type,summary,payload,source_type,source_id,created_by,observed_at) values((select value from ctx where key='evidence_a1'),(select value from ctx where key='org_a'),'quantitative','Turnover metric','{"value":2}','service','metric-a',(select value from ctx where key='user_1'),'2026-01-15'),((select value from ctx where key='evidence_a2'),(select value from ctx where key='org_a'),'qualitative','Leadership context','{"theme":"change"}','manual','note-a',(select value from ctx where key='user_1'),'2026-01-20'),((select value from ctx where key='evidence_a3'),(select value from ctx where key='org_a'),'behavioral','Contradicting retention observation','{"value":"stable"}','service','metric-a3',(select value from ctx where key='user_1'),'2026-01-25'),((select value from ctx where key='evidence_b'),(select value from ctx where key='org_b'),'quantitative','Tenant B evidence','{"value":9}','service','metric-b',(select value from ctx where key='user_1'),'2026-01-15');
insert into public.intelligence_evidence_assessments(id,organization_id,reading_id,hypothesis_id,status,evidence_state,supporting_evidence_count,contradicting_evidence_count,unknowns,limitations,assessment_summary,assessed_by_user_id,assessed_at,context) values((select value from ctx where key='assessment_a'),(select value from ctx where key='org_a'),(select value from ctx where key='reading_a'),(select value from ctx where key='hypothesis_a'),'under_investigation','moderate',2,1,'["causal mechanism unknown"]','["small window"]','Moderate support with explicit limitations.',null,null,'{"manual":true}'),((select value from ctx where key='assessment_b'),(select value from ctx where key='org_b'),(select value from ctx where key='reading_b'),(select value from ctx where key='hypothesis_b'),'under_investigation','insufficient',0,0,'["more data"]','["tenant B fixture"]','Insufficient evidence.',null,null,'{}'),((select value from ctx where key='assessment_other'),(select value from ctx where key='org_a'),(select value from ctx where key='reading_a'),null,'under_investigation','insufficient',0,0,'["other unknown"]','["other limitation"]','Other assessment must remain unchanged.',null,null,'{}'),((select value from ctx where key='assessment_draft'),(select value from ctx where key='org_a'),(select value from ctx where key='reading_a'),null,'draft','insufficient',0,0,'["draft unknown"]','["draft limitation"]','Draft assessment.',null,null,'{}');
insert into public.intelligence_evidence_assessment_evidence(organization_id,assessment_id,evidence_id,evidence_relation,provenance_note,context) values((select value from ctx where key='org_a'),(select value from ctx where key='assessment_a'),(select value from ctx where key='evidence_a1'),'supports','Metric supports the reading.','{}'),((select value from ctx where key='org_a'),(select value from ctx where key='assessment_a'),(select value from ctx where key='evidence_a2'),'supports','Context supports investigation.','{}'),((select value from ctx where key='org_a'),(select value from ctx where key='assessment_a'),(select value from ctx where key='evidence_a3'),'contradicts','Retention observation limits interpretation.','{}');
insert into public.intelligence_recommendations(id,organization_id,employee_id,title,rationale,status,source_evidence_ids,created_by,recommendation_type,scope_type,scope_ref,evidence_state,problem_statement,unknowns,recommended_intervention_type,alternatives,do_not_recommend,expected_outcome,measurement_plan,owner_employee_id,approval_required,context) values((select value from ctx where key='recommendation_a'),(select value from ctx where key='org_a'),null,'Cautious leadership review','Moderate evidence supports a cautious review, not a causal claim.','proposed','[]',(select value from ctx where key='user_1'),'investigate','organization',(select value from ctx where key='org_a'),'moderate','Understand the movement before acting.','["causal mechanism unknown"]','investigation','[{"option":"monitor"},{"option":"investigate"}]','["do not change leaders based on this alone"]','Clarify evidence and options.','{"metric":"turnover","window":"30d"}',null,true,'{"prepared_from":"assessment_a"}');
insert into public.intelligence_recommendations(id,organization_id,title,rationale,status,source_evidence_ids,created_by,recommendation_type,scope_type,scope_ref,evidence_state,unknowns,alternatives,do_not_recommend,measurement_plan,context) values((select value from ctx where key='recommendation_other'),(select value from ctx where key='org_a'),'Other recommendation','Must remain unchanged.','draft','[]',(select value from ctx where key='user_1'),'investigate','organization','org-a','insufficient','["other unknown"]','[]','[]','{}','{}'),((select value from ctx where key='recommendation_b'),(select value from ctx where key='org_b'),'Tenant B recommendation','Tenant B fixture.','draft','[]',(select value from ctx where key='user_1'),'investigate','organization','org-b','insufficient','[]','[]','[]','{}','{}');

create or replace function pg_temp.assert_true(label text,condition boolean) returns void language plpgsql as $$ begin if condition is distinct from true then raise exception 'FAIL-FAST assertion: %',label; end if; end; $$;
insert into public.intelligence_recommendation_readings(organization_id,recommendation_id,reading_id,context) values((select value from ctx where key='org_a'),(select value from ctx where key='recommendation_a'),(select value from ctx where key='reading_a'),'{}');
insert into public.intelligence_recommendation_assessments(organization_id,recommendation_id,assessment_id,context) values((select value from ctx where key='org_a'),(select value from ctx where key='recommendation_a'),(select value from ctx where key='assessment_a'),'{}');
insert into public.intelligence_recommendation_hypotheses(organization_id,recommendation_id,hypothesis_id,context) values((select value from ctx where key='org_a'),(select value from ctx where key='recommendation_a'),(select value from ctx where key='hypothesis_a'),'{}');
insert into public.intelligence_recommendation_evidence(organization_id,recommendation_id,evidence_id,evidence_relation,context) values((select value from ctx where key='org_a'),(select value from ctx where key='recommendation_a'),(select value from ctx where key='evidence_a1'),'supports','{}'),((select value from ctx where key='org_a'),(select value from ctx where key='recommendation_a'),(select value from ctx where key='evidence_a3'),'contradicts','{}');
select pg_temp.assert_true('legacy Recommendation Evidence contract has no synthetic id and expected columns',
 (select array_agg(column_name order by ordinal_position) from information_schema.columns where table_schema='public' and table_name='intelligence_recommendation_evidence')=array['organization_id','recommendation_id','evidence_id','created_at','evidence_relation','context']::text[]
 and not exists(select 1 from information_schema.columns where table_schema='public' and table_name='intelligence_recommendation_evidence' and column_name='id'));
select pg_temp.assert_true('legacy Recommendation Evidence PK remains the composed identity',
 (select string_agg(att.attname,',' order by key.ord) from pg_index idx cross join lateral unnest(idx.indkey) with ordinality as key(attnum,ord) join pg_attribute att on att.attrelid=idx.indrelid and att.attnum=key.attnum where idx.indrelid='public.intelligence_recommendation_evidence'::regclass and idx.indisprimary)='organization_id,recommendation_id,evidence_id');
select pg_temp.assert_true('evidence_state vocabulary is closed',not exists(select 1 from public.intelligence_evidence_assessments where evidence_state not in('insufficient','insufficient','moderate','strong','conflicting')));
select pg_temp.assert_true('assessment links Reading tenant-safely',exists(select 1 from public.intelligence_evidence_assessments where organization_id=(select value from ctx where key='org_a') and reading_id=(select value from ctx where key='reading_a')));
select pg_temp.assert_true('assessment links Hypothesis tenant-safely',exists(select 1 from public.intelligence_evidence_assessments where organization_id=(select value from ctx where key='org_a') and hypothesis_id=(select value from ctx where key='hypothesis_a')));
select pg_temp.assert_true('supporting and contradicting evidence are normalized',exists(select 1 from public.intelligence_evidence_assessment_evidence where assessment_id=(select value from ctx where key='assessment_a') and evidence_relation='supports') and exists(select 1 from public.intelligence_evidence_assessment_evidence where assessment_id=(select value from ctx where key='assessment_a') and evidence_relation='contradicts'));
select pg_temp.assert_true('counts do not replace evidence relations',(select count(*) from public.intelligence_evidence_assessment_evidence where assessment_id=(select value from ctx where key='assessment_a'))=3 and (select supporting_evidence_count from public.intelligence_evidence_assessments where id=(select value from ctx where key='assessment_a'))=2);
select pg_temp.assert_true('unknowns and limitations are preserved',(select unknowns->>0 from public.intelligence_evidence_assessments where id=(select value from ctx where key='assessment_a'))='causal mechanism unknown' and (select limitations->>0 from public.intelligence_evidence_assessments where id=(select value from ctx where key='assessment_a'))='small window');
select pg_temp.assert_true('Recommendation is explicitly linked to Reading',exists(select 1 from public.intelligence_recommendation_readings where recommendation_id=(select value from ctx where key='recommendation_a') and reading_id=(select value from ctx where key='reading_a')));
select pg_temp.assert_true('Recommendation is explicitly linked to Assessment',exists(select 1 from public.intelligence_recommendation_assessments where recommendation_id=(select value from ctx where key='recommendation_a') and assessment_id=(select value from ctx where key='assessment_a')));
select pg_temp.assert_true('Recommendation is explicitly linked to Hypothesis',exists(select 1 from public.intelligence_recommendation_hypotheses where recommendation_id=(select value from ctx where key='recommendation_a') and hypothesis_id=(select value from ctx where key='hypothesis_a')));
select pg_temp.assert_true('Recommendation preserves supporting and contradicting evidence',exists(select 1 from public.intelligence_recommendation_evidence where recommendation_id=(select value from ctx where key='recommendation_a') and evidence_id=(select value from ctx where key='evidence_a1') and evidence_relation='supports') and exists(select 1 from public.intelligence_recommendation_evidence where recommendation_id=(select value from ctx where key='recommendation_a') and evidence_id=(select value from ctx where key='evidence_a3') and evidence_relation='contradicts'));
select pg_temp.assert_true('Recommendation preserves alternatives and do_not_recommend',(select jsonb_array_length(alternatives) from public.intelligence_recommendations where id=(select value from ctx where key='recommendation_a'))=2 and (select jsonb_array_length(do_not_recommend) from public.intelligence_recommendations where id=(select value from ctx where key='recommendation_a'))=1);
select pg_temp.assert_true('Recommendation preserves measurement_plan',(select measurement_plan->>'metric' from public.intelligence_recommendations where id=(select value from ctx where key='recommendation_a'))='turnover');
select pg_temp.assert_true('Recommendation is not a Decision',not exists(select 1 from public.intelligence_decisions where organization_id=(select value from ctx where key='org_a') and id=(select value from ctx where key='recommendation_a')));
select pg_temp.assert_true('insufficient cannot be proposed',not exists(select 1 from public.intelligence_recommendations where status in('proposed','accepted') and evidence_state='insufficient'));

create or replace function pg_temp.invalid_insufficient_recommendation() returns boolean language plpgsql security invoker as $$ begin begin insert into public.intelligence_recommendations(organization_id,title,status,evidence_state,unknowns,alternatives,do_not_recommend,measurement_plan,context) values((select value from ctx where key='org_a'),'Invalid insufficient','proposed','insufficient','[]','[]','[]','{}','{}'); return false; exception when others then return true; end; end; $$;
create or replace function pg_temp.invalid_cross_tenant_assessment() returns boolean language plpgsql security invoker as $$ begin begin insert into public.intelligence_evidence_assessments(organization_id,reading_id,status,evidence_state,assessment_summary,context) values((select value from ctx where key='org_a'),(select value from ctx where key='reading_b'),'under_investigation','insufficient','Cross tenant','{}'); return false; exception when others then return true; end; end; $$;
create or replace function pg_temp.invalid_cross_tenant_rec_link() returns boolean language plpgsql security invoker as $$ begin begin insert into public.intelligence_recommendation_readings(organization_id,recommendation_id,reading_id,context) values((select value from ctx where key='org_a'),(select value from ctx where key='recommendation_a'),(select value from ctx where key='reading_b'),'{}'); return false; exception when others then return true; end; end; $$;
create or replace function pg_temp.duplicate_recommendation_evidence_relation() returns boolean language plpgsql security invoker as $$ begin begin insert into public.intelligence_recommendation_evidence(organization_id,recommendation_id,evidence_id,evidence_relation,context) values((select value from ctx where key='org_a'),(select value from ctx where key='recommendation_a'),(select value from ctx where key='evidence_a1'),'contradicts','{}'); return false; exception when others then return true; end; end; $$;
select pg_temp.assert_true('historical Recommendation Evidence PK forbids two relations for one evidence',pg_temp.duplicate_recommendation_evidence_relation());
select pg_temp.assert_true('insufficient readiness guard rejects proposal',pg_temp.invalid_insufficient_recommendation());
select pg_temp.assert_true('cross-tenant Assessment rejected',pg_temp.invalid_cross_tenant_assessment());
select pg_temp.assert_true('cross-tenant Recommendation link rejected',pg_temp.invalid_cross_tenant_rec_link());

-- Explicit Memory entries: assessment is evaluated knowledge; recommendation is derived proposal.
insert into public.organizational_memory_relations(id,organization_id,source_entity_type,source_entity_id,target_entity_type,target_entity_id,relationship_type,knowledge_kind,valid_from,source_type,source_id,sensitivity,context) values((select value from ctx where key='memory_assessment'),(select value from ctx where key='org_a'),'evidence_assessment',(select value from ctx where key='assessment_a'),'reading',(select value from ctx where key='reading_a'),'related_to','interpreted','2026-02-02','service',(select value::text from ctx where key='assessment_a'),'standard','{"epistemic":"assessed"}'),((select value from ctx where key='memory_recommendation'),(select value from ctx where key='org_a'),'recommendation',(select value from ctx where key='recommendation_a'),'reading',(select value from ctx where key='reading_a'),'derived_from','derived','2026-02-02','service',(select value::text from ctx where key='recommendation_a'),'standard','{"proposal":true}');
select pg_temp.assert_true('Assessment and Recommendation Memory registration is explicit',exists(select 1 from public.organizational_memory_relations where source_entity_type='evidence_assessment' and knowledge_kind='interpreted') and exists(select 1 from public.organizational_memory_relations where source_entity_type='recommendation' and knowledge_kind='derived'));
insert into public.organizational_events(organization_id,event_type,entity_type,entity_id,occurred_at,source_type,actor_user_id,sensitivity,payload) values((select value from ctx where key='org_a'),'evidence_assessment_created','evidence_assessment',(select value from ctx where key='assessment_a'),'2026-02-02','service',(select value from ctx where key='user_1'),'standard','{"assessment_id":"assessment_a"}'),((select value from ctx where key='org_a'),'recommendation_prepared','recommendation',(select value from ctx where key='recommendation_a'),'2026-02-02','service',(select value from ctx where key='user_1'),'standard','{"recommendation_id":"recommendation_a"}');
select pg_temp.assert_true('operational Event Layer contracts are implemented',(select count(*) from public.organizational_event_types where event_type in('evidence_assessment_created','evidence_assessment_updated','recommendation_prepared','recommendation_evidence_updated') and implemented=true)=4);

set local role authenticated;
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_1'),true);
select pg_temp.assert_true('admin reads own assessment',exists(select 1 from public.intelligence_evidence_assessments where organization_id=(select value from ctx where key='org_a')));
select pg_temp.assert_true('admin cannot read tenant B assessment',not exists(select 1 from public.intelligence_evidence_assessments where organization_id=(select value from ctx where key='org_b')));
create or replace function pg_temp.cross_tenant_assessment_insert() returns boolean language plpgsql security invoker as $$ declare msg text; begin begin insert into public.intelligence_evidence_assessments(organization_id,reading_id,status,evidence_state,assessment_summary,context) values((select value from ctx where key='org_b'),(select value from ctx where key='reading_b'),'under_investigation','insufficient','Cross tenant','{}'); return false; exception when others then get stacked diagnostics msg=message_text; return msg ilike '%row-level security%'; end; end; $$;
select pg_temp.assert_true('admin cross-tenant assessment write denied',pg_temp.cross_tenant_assessment_insert());
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_2'),true);
select pg_temp.assert_true('diretoria reads permitted organizational assessment',exists(select 1 from public.intelligence_evidence_assessments where organization_id=(select value from ctx where key='org_a')));
select pg_temp.assert_true('diretoria reads permitted Recommendation provenance',exists(select 1 from public.intelligence_recommendation_assessments where organization_id=(select value from ctx where key='org_a')));
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_3'),true);
select pg_temp.assert_true('gestor has no generic Assessment access',not exists(select 1 from public.intelligence_evidence_assessments where organization_id=(select value from ctx where key='org_a')));
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_4'),true);
select pg_temp.assert_true('colaborador has no generic Assessment access',not exists(select 1 from public.intelligence_evidence_assessments where organization_id=(select value from ctx where key='org_a')));
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_5'),true);
insert into public.intelligence_evidence_assessments(organization_id,reading_id,status,evidence_state,assessment_summary,context) values((select value from ctx where key='org_a'),(select value from ctx where key='reading_a'),'under_investigation','insufficient','RH assessment','{}');
select pg_temp.assert_true('RH can create own tenant Assessment',exists(select 1 from public.intelligence_evidence_assessments where assessment_summary='RH assessment'));

-- Controlled revisions preserve assessment and Recommendation provenance.
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_1'),true);
select public.revise_intelligence_evidence_assessment((select value from ctx where key='assessment_a'),'{"status":"assessed","evidence_state":"strong","supporting_evidence_count":2,"contradicting_evidence_count":1,"unknowns":["causal mechanism unknown"],"limitations":["small window"],"assessment_summary":"Reassessed with same limitations.","context":{"manual":true,"revised":true}}'::jsonb,'admin reassessment');
select pg_temp.assert_true('assessment revision preserves before and after',exists(select 1 from public.intelligence_evidence_assessment_revisions where assessment_id=(select value from ctx where key='assessment_a') and previous_snapshot->>'evidence_state'='moderate' and new_snapshot->>'evidence_state'='strong'));
select pg_temp.assert_true('assessment revision changes only requested Assessment',(select evidence_state from public.intelligence_evidence_assessments where id=(select value from ctx where key='assessment_a'))='strong' and (select evidence_state from public.intelligence_evidence_assessments where id=(select value from ctx where key='assessment_other'))='insufficient' and not exists(select 1 from public.intelligence_evidence_assessment_revisions where assessment_id=(select value from ctx where key='assessment_other')));
select public.revise_intelligence_evidence_assessment((select value from ctx where key='assessment_draft'),'{"status":"assessed","evidence_state":"weak","supporting_evidence_count":0,"contradicting_evidence_count":0,"unknowns":["draft unknown"],"limitations":["draft limitation"],"assessment_summary":"Draft finalized.","context":{"finalized":true}}'::jsonb,'finalize draft assessment');
select pg_temp.assert_true('draft Assessment can be finalized', (select status from public.intelligence_evidence_assessments where id=(select value from ctx where key='assessment_draft'))='assessed');
select pg_temp.assert_true('finalization stamps authenticated actor and time',(select assessed_by_user_id from public.intelligence_evidence_assessments where id=(select value from ctx where key='assessment_draft'))=(select value from ctx where key='user_1') and (select assessed_at from public.intelligence_evidence_assessments where id=(select value from ctx where key='assessment_draft')) is not null);
select pg_temp.assert_true('finalization snapshot records actor and time',exists(select 1 from public.intelligence_evidence_assessment_revisions where assessment_id=(select value from ctx where key='assessment_draft') and new_snapshot->>'status'='assessed' and new_snapshot->>'assessed_by_user_id'=(select value::text from ctx where key='user_1') and (new_snapshot->>'assessed_at') is not null));
select public.revise_intelligence_recommendation((select value from ctx where key='recommendation_a'),'{"title":"Cautious leadership review revised","rationale":"Revised cautious rationale.","evidence_state":"strong","unknowns":["causal mechanism unknown"],"alternatives":[{"option":"monitor"},{"option":"investigate"}],"do_not_recommend":["do not change leaders based on this alone"],"measurement_plan":{"metric":"turnover","window":"60d"},"approval_required":true,"scope_type":"organization","scope_ref":"org-a","status":"proposed","context":{"prepared_from":"assessment_a","revised":true}}'::jsonb,'admin recommendation revision');
select pg_temp.assert_true('Recommendation revision preserves before and after',exists(select 1 from public.intelligence_recommendation_revisions where recommendation_id=(select value from ctx where key='recommendation_a') and previous_snapshot->>'title'='Cautious leadership review' and new_snapshot->>'title'='Cautious leadership review revised'));
select pg_temp.assert_true('Recommendation revision changes only requested Recommendation',(select title from public.intelligence_recommendations where id=(select value from ctx where key='recommendation_a'))='Cautious leadership review revised' and (select title from public.intelligence_recommendations where id=(select value from ctx where key='recommendation_other'))='Other recommendation' and not exists(select 1 from public.intelligence_recommendation_revisions where recommendation_id=(select value from ctx where key='recommendation_other')));
create or replace function pg_temp.cross_tenant_assessment_revision() returns boolean language plpgsql security invoker as $$ begin begin perform public.revise_intelligence_evidence_assessment((select value from ctx where key='assessment_b'),'{"status":"under_investigation","evidence_state":"weak","supporting_evidence_count":0,"contradicting_evidence_count":0,"unknowns":[],"limitations":[],"assessment_summary":"cross tenant","context":{}}'::jsonb,'cross tenant'); return false; exception when others then return true; end; end; $$;
create or replace function pg_temp.cross_tenant_recommendation_revision() returns boolean language plpgsql security invoker as $$ begin begin perform public.revise_intelligence_recommendation((select value from ctx where key='recommendation_b'),'{"title":"cross tenant","rationale":"cross tenant","evidence_state":"weak","unknowns":[],"alternatives":[],"do_not_recommend":[],"measurement_plan":{},"approval_required":false,"scope_type":"organization","scope_ref":"org-b","status":"draft","context":{}}'::jsonb,'cross tenant'); return false; exception when others then return true; end; end; $$;
select pg_temp.assert_true('cross-tenant Assessment revision blocked',pg_temp.cross_tenant_assessment_revision());
select pg_temp.assert_true('cross-tenant Recommendation revision blocked',pg_temp.cross_tenant_recommendation_revision());
create or replace function pg_temp.revise_assessed_again() returns boolean language plpgsql security invoker as $$ begin begin perform public.revise_intelligence_evidence_assessment((select value from ctx where key='assessment_a'),'{"status":"under_investigation","evidence_state":"weak","supporting_evidence_count":0,"contradicting_evidence_count":0,"unknowns":[],"limitations":[],"assessment_summary":"illegal","context":{}}'::jsonb,'illegal reverse'); return false; exception when others then return true; end; end; $$;
create or replace function pg_temp.falsify_assessment_authorship() returns boolean language plpgsql security invoker as $$ begin begin perform public.revise_intelligence_evidence_assessment((select value from ctx where key='assessment_other'),'{"status":"assessed","evidence_state":"weak","supporting_evidence_count":0,"contradicting_evidence_count":0,"unknowns":[],"limitations":[],"assessment_summary":"forged","context":{},"assessed_by_user_id":"99999999-9999-9999-9999-999999999999","assessed_at":"2000-01-01T00:00:00Z"}'::jsonb,'forged author'); return false; exception when others then return true; end; end; $$;
select pg_temp.assert_true('already assessed Assessment cannot be revised',pg_temp.revise_assessed_again());
select pg_temp.assert_true('client cannot falsify assessment authorship or timestamp',pg_temp.falsify_assessment_authorship());
select pg_temp.assert_true('forgery attempt leaves other Assessment unchanged',(select status from public.intelligence_evidence_assessments where id=(select value from ctx where key='assessment_other'))='under_investigation' and not exists(select 1 from public.intelligence_evidence_assessment_revisions where assessment_id=(select value from ctx where key='assessment_other')));
create or replace function pg_temp.silent_assessment_update() returns boolean language plpgsql security invoker as $$ declare msg text; begin begin update public.intelligence_evidence_assessments set assessment_summary='silent' where id=(select value from ctx where key='assessment_a'); return false; exception when others then get stacked diagnostics msg=message_text; return msg ilike '%permission denied%' or msg ilike '%row-level security%'; end; end; $$;
create or replace function pg_temp.silent_recommendation_update() returns boolean language plpgsql security invoker as $$ declare msg text; begin begin update public.intelligence_recommendations set rationale='silent' where id=(select value from ctx where key='recommendation_a'); return false; exception when others then get stacked diagnostics msg=message_text; return msg ilike '%permission denied%' or msg ilike '%row-level security%'; end; end; $$;
select pg_temp.assert_true('silent Assessment update blocked',pg_temp.silent_assessment_update());
select pg_temp.assert_true('silent Recommendation update blocked',pg_temp.silent_recommendation_update());
select pg_temp.assert_true('no downstream Decision Intervention Action Outcome created',not exists(select 1 from public.intelligence_decisions where organization_id=(select value from ctx where key='org_a')) and not exists(select 1 from public.intelligence_interventions where organization_id=(select value from ctx where key='org_a')) and not exists(select 1 from public.intelligence_actions where organization_id=(select value from ctx where key='org_a')) and not exists(select 1 from public.intelligence_outcomes where organization_id=(select value from ctx where key='org_a')));
select pg_temp.assert_true('no automatic triggers on operational tables',not exists(select 1 from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in('intelligence_evidence_assessments','intelligence_evidence_assessment_evidence','intelligence_recommendation_readings','intelligence_recommendation_assessments','intelligence_recommendation_hypotheses','intelligence_recommendation_evidence','intelligence_evidence_assessment_revisions','intelligence_recommendation_revisions') and not t.tgisinternal));
select pg_temp.assert_true('no raw conversation prompt or chain of thought columns',not exists(select 1 from information_schema.columns where table_schema='public' and table_name like 'intelligence_%' and column_name in('conversation','raw_conversation','prompt','raw_prompt','chain_of_thought')));
rollback;
