-- youB — Leitura Organizacional Engine V1 dedicated QA suite
-- Transactional disposable fixtures; fail-fast; no staging/production execution.
begin;
create temp table ctx(key text primary key,value uuid not null) on commit drop;
do $$ declare k text; begin
 foreach k in array array['intelligence_organizational_readings','intelligence_organizational_reading_sources','intelligence_organizational_reading_hypotheses','intelligence_organizational_reading_revisions'] loop
  if to_regclass('public.'||k) is null then raise exception 'missing Leitura Organizacional prerequisite: %',k; end if;
 end loop;
 if (select count(*) from auth.users)<5 then raise exception 'suite requires five auth users'; end if;
end $$;
insert into ctx values
 ('org_a','55555555-5555-5555-5555-555555555555'),('org_b','66666666-6666-6666-6666-666666666666'),
 ('reading_rh','55555555-0000-0000-0000-000000000012'),('reading_a2','55555555-0000-0000-0000-000000000013'),
 ('employee_a','55555555-0000-0000-0000-000000000001'),('employee_b','66666666-0000-0000-0000-000000000001'),
 ('reading_a','55555555-0000-0000-0000-000000000011'),('reading_b','66666666-0000-0000-0000-000000000011'),
 ('evidence_a1','55555555-0000-0000-0000-000000000021'),('evidence_a2','55555555-0000-0000-0000-000000000022'),('evidence_b','66666666-0000-0000-0000-000000000021'),
 ('event_a','55555555-0000-0000-0000-000000000031'),('hypothesis_a','55555555-0000-0000-0000-000000000041'),('memory_a','55555555-0000-0000-0000-000000000051');
insert into ctx select 'user_'||row_number() over(order by created_at),id from auth.users order by created_at limit 5;
insert into public.organizations(id,name,slug,plan,status) values
 ((select value from ctx where key='org_a'),'Reading A','reading-a','essencial','active'),((select value from ctx where key='org_b'),'Reading B','reading-b','essencial','active');
insert into public.memberships(organization_id,user_id,role) values
 ((select value from ctx where key='org_a'),(select value from ctx where key='user_1'),'admin_youb'),
 ((select value from ctx where key='org_a'),(select value from ctx where key='user_2'),'diretoria'),
 ((select value from ctx where key='org_a'),(select value from ctx where key='user_3'),'gestor'),
 ((select value from ctx where key='org_a'),(select value from ctx where key='user_4'),'colaborador'),
 ((select value from ctx where key='org_a'),(select value from ctx where key='user_5'),'rh');
insert into public.employees(id,organization_id,auth_user_id,full_name,email,manager_employee_id) values
 ((select value from ctx where key='employee_a'),(select value from ctx where key='org_a'),null,'Reading Employee A','reading-a@example.invalid',null),
 ((select value from ctx where key='employee_b'),(select value from ctx where key='org_b'),null,'Reading Employee B','reading-b@example.invalid',null);
insert into public.intelligence_evidence(id,organization_id,evidence_type,summary,payload,source_type,source_id,created_by,observed_at) values
 ((select value from ctx where key='evidence_a1'),(select value from ctx where key='org_a'),'quantitative','Turnover window A','{"metric":"turnover","value":2}','service','metric-a',(select value from ctx where key='user_1'),'2026-01-15'),
 ((select value from ctx where key='evidence_a2'),(select value from ctx where key='org_a'),'qualitative','Team context A','{"theme":"leadership change"}','manual','note-a',(select value from ctx where key='user_1'),'2026-01-20'),
 ((select value from ctx where key='evidence_b'),(select value from ctx where key='org_b'),'quantitative','Tenant B evidence','{"metric":"turnover","value":9}','service','metric-b',(select value from ctx where key='user_1'),'2026-01-15');
insert into public.organizational_events(id,organization_id,event_type,entity_type,entity_id,occurred_at,source_type,actor_user_id,sensitivity,payload) values
 ((select value from ctx where key='event_a'),(select value from ctx where key='org_a'),'employee_created','employee',(select value from ctx where key='employee_a'),'2026-01-10','service',(select value from ctx where key='user_1'),'standard','{"fixture":"reading"}');
insert into public.intelligence_organizational_readings(id,organization_id,reading_type,scope_type,scope_ref,title,description,status,knowledge_kind,observation_window_start,observation_window_end,detected_at,source_summary,context) values
 ((select value from ctx where key='reading_a'),(select value from ctx where key='org_a'),'movement','team','team-a','Turnover movement in two teams','Turnover increased among people with 6–18 months in two teams.','open','interpreted','2026-01-01','2026-01-31','2026-02-01','Two existing evidence records and one organizational event.','{"tenure_band":"6-18m","teams":2}'),
 ((select value from ctx where key='reading_a2'),(select value from ctx where key='org_a'),'pattern','team','team-b','Another team reading','Another reading in the same tenant.','open','interpreted','2026-01-01','2026-01-31','2026-02-01','Same tenant provenance.','{}'),
 ((select value from ctx where key='reading_b'),(select value from ctx where key='org_b'),'pattern','organization','org-b','Tenant B reading','Tenant B fixture reading.','open','interpreted','2026-01-01','2026-01-31','2026-02-01','Tenant B evidence.','{}');
insert into public.intelligence_organizational_reading_sources(organization_id,reading_id,source_type,evidence_id,relationship_type,provenance_note,context) values
 ((select value from ctx where key='org_a'),(select value from ctx where key='reading_a'),'evidence',(select value from ctx where key='evidence_a1'),'supports','Metric observed in the window.','{}'),
 ((select value from ctx where key='org_a'),(select value from ctx where key='reading_a'),'evidence',(select value from ctx where key='evidence_a2'),'contextualizes','Context recorded in the window.','{}');
insert into public.intelligence_organizational_reading_sources(organization_id,reading_id,source_type,organizational_event_id,relationship_type,provenance_note,context)
values((select value from ctx where key='org_a'),(select value from ctx where key='reading_a'),'organizational_event',(select value from ctx where key='event_a'),'observed_in','Event provenance.','{"event":"employee_created"}');
insert into public.intelligence_organizational_reading_hypotheses(id,organization_id,reading_id,hypothesis_statement,status,knowledge_kind,context,created_by) values
 ((select value from ctx where key='hypothesis_a'),(select value from ctx where key='org_a'),(select value from ctx where key='reading_a'),'Leadership change may be contributing to the movement.','proposed','hypothesis','{"not_causal_confirmation":true}',(select value from ctx where key='user_1'));

create or replace function pg_temp.assert_true(label text,condition boolean) returns void language plpgsql as $$ begin if condition is distinct from true then raise exception 'FAIL-FAST assertion: %',label; end if; end; $$;
select pg_temp.assert_true('reading vocabulary is controlled',not exists(select 1 from public.intelligence_organizational_readings where reading_type not in ('movement','pattern','anomaly','risk','opportunity','tension','gap','evolution')));
select pg_temp.assert_true('reading status vocabulary is controlled',not exists(select 1 from public.intelligence_organizational_readings where status not in ('open','under_investigation','supported','dismissed','resolved','archived')));
select pg_temp.assert_true('reading is interpreted, not fact',not exists(select 1 from public.intelligence_organizational_readings where knowledge_kind='fact'));
select pg_temp.assert_true('hypothesis remains epistemically distinct',exists(select 1 from public.intelligence_organizational_reading_hypotheses where knowledge_kind='hypothesis' and status='proposed') and not exists(select 1 from public.intelligence_organizational_readings where knowledge_kind='hypothesis'));
select pg_temp.assert_true('valid scope is shared architecture scope',not exists(select 1 from public.intelligence_organizational_readings where scope_type not in ('employee','team','area','position','process','unit','organization')));
select pg_temp.assert_true('observation window is ordered',not exists(select 1 from public.intelligence_organizational_readings where observation_window_end<observation_window_start));
select pg_temp.assert_true('one reading can use multiple existing sources',(select count(*) from public.intelligence_organizational_reading_sources where reading_id=(select value from ctx where key='reading_a'))=3);
select pg_temp.assert_true('source provenance points to existing evidence and event',exists(select 1 from public.intelligence_organizational_reading_sources where source_type='evidence' and evidence_id=(select value from ctx where key='evidence_a1')) and exists(select 1 from public.intelligence_organizational_reading_sources where source_type='organizational_event' and organizational_event_id=(select value from ctx where key='event_a')));
create or replace function pg_temp.duplicate_reading_source() returns boolean language plpgsql security invoker as $$ declare msg text; begin begin insert into public.intelligence_organizational_reading_sources(organization_id,reading_id,source_type,evidence_id,relationship_type,context) values((select value from ctx where key='org_a'),(select value from ctx where key='reading_a'),'evidence',(select value from ctx where key='evidence_a1'),'supports','{}'); return false; exception when others then get stacked diagnostics msg=message_text; return msg ilike '%intelligence_reading_sources_evidence_unique%'; end; end; $$;
select pg_temp.assert_true('same source cannot be linked twice to one Reading',pg_temp.duplicate_reading_source());
insert into public.intelligence_organizational_reading_sources(organization_id,reading_id,source_type,evidence_id,relationship_type,context) values((select value from ctx where key='org_a'),(select value from ctx where key='reading_a2'),'evidence',(select value from ctx where key='evidence_a1'),'supports','{}');
select pg_temp.assert_true('same source may link to another Reading in same tenant',exists(select 1 from public.intelligence_organizational_reading_sources where reading_id=(select value from ctx where key='reading_a2') and evidence_id=(select value from ctx where key='evidence_a1')));
select pg_temp.assert_true('different sources remain linkable to one Reading',(select count(distinct coalesce(evidence_id,organizational_event_id)) from public.intelligence_organizational_reading_sources where reading_id=(select value from ctx where key='reading_a'))=3);
select pg_temp.assert_true('hypothesis is not automatically a confirmed cause',not exists(select 1 from public.intelligence_organizational_reading_hypotheses where context->>'causal_confirmed'='true'));
select pg_temp.assert_true('reading does not create downstream contracts',not exists(select 1 from public.intelligence_recommendations where organization_id=(select value from ctx where key='org_a')) and not exists(select 1 from public.intelligence_decisions where organization_id=(select value from ctx where key='org_a')) and not exists(select 1 from public.intelligence_interventions where organization_id=(select value from ctx where key='org_a')) and not exists(select 1 from public.intelligence_actions where organization_id=(select value from ctx where key='org_a')));

create or replace function pg_temp.invalid_reading_vocab() returns boolean language plpgsql security invoker as $$ begin begin insert into public.intelligence_organizational_readings(organization_id,reading_type,scope_type,scope_ref,title,description,knowledge_kind,observation_window_start,observation_window_end,source_summary,context) values((select value from ctx where key='org_a'),'cause','organization','org-a','Invalid','Invalid','interpreted','2026-01-02','2026-01-01','source','{}'); return false; exception when others then return true; end; end; $$;
create or replace function pg_temp.invalid_reading_json() returns boolean language plpgsql security invoker as $$ begin begin insert into public.intelligence_organizational_readings(organization_id,reading_type,scope_type,scope_ref,title,description,knowledge_kind,observation_window_start,observation_window_end,source_summary,context) values((select value from ctx where key='org_a'),'movement','organization','org-a','Invalid','Invalid','interpreted','2026-01-01','2026-01-02','source','[]'); return false; exception when others then return true; end; end; $$;
create or replace function pg_temp.invalid_reading_fact() returns boolean language plpgsql security invoker as $$ begin begin insert into public.intelligence_organizational_readings(organization_id,reading_type,scope_type,scope_ref,title,description,knowledge_kind,observation_window_start,observation_window_end,source_summary,context) values((select value from ctx where key='org_a'),'movement','organization','org-a','Invalid','Invalid','fact','2026-01-01','2026-01-02','source','{}'); return false; exception when others then return true; end; end; $$;
create or replace function pg_temp.invalid_source_shape() returns boolean language plpgsql security invoker as $$ begin begin insert into public.intelligence_organizational_reading_sources(organization_id,reading_id,source_type,evidence_id,context) values((select value from ctx where key='org_a'),(select value from ctx where key='reading_a'),'evidence',null,'{}'); return false; exception when others then return true; end; end; $$;
create or replace function pg_temp.invalid_cross_tenant_source() returns boolean language plpgsql security invoker as $$ begin begin insert into public.intelligence_organizational_reading_sources(organization_id,reading_id,source_type,evidence_id,context) values((select value from ctx where key='org_a'),(select value from ctx where key='reading_a'),'evidence',(select value from ctx where key='evidence_b'),'{}'); return false; exception when others then return true; end; end; $$;
select pg_temp.assert_true('invalid reading vocabulary/window rejected',pg_temp.invalid_reading_vocab());
select pg_temp.assert_true('invalid reading JSON shape rejected',pg_temp.invalid_reading_json());
select pg_temp.assert_true('fact classification rejected for Reading',pg_temp.invalid_reading_fact());
select pg_temp.assert_true('source exact-one shape rejected',pg_temp.invalid_source_shape());
select pg_temp.assert_true('cross-tenant source rejected',pg_temp.invalid_cross_tenant_source());

-- Explicit Organizational Memory registration: interpreted Reading, not automatic projection.
insert into public.organizational_memory_relations(id,organization_id,source_entity_type,source_entity_id,target_entity_type,target_entity_id,relationship_type,knowledge_kind,valid_from,source_type,source_id,sensitivity,context)
values((select value from ctx where key='memory_a'),(select value from ctx where key='org_a'),'reading',(select value from ctx where key='reading_a'),'organization',(select value from ctx where key='org_a'),'observes','interpreted','2026-01-01','service',(select value::text from ctx where key='reading_a'),'standard','{"epistemic":"interpreted"}');
select pg_temp.assert_true('Reading can be registered explicitly in Organizational Memory',exists(select 1 from public.organizational_memory_relations where source_entity_type='reading' and source_entity_id=(select value from ctx where key='reading_a') and knowledge_kind='interpreted'));
-- Explicit Event Layer contract; no trigger emits it.
insert into public.organizational_events(organization_id,event_type,entity_type,entity_id,occurred_at,source_type,actor_user_id,sensitivity,payload)
values((select value from ctx where key='org_a'),'organizational_reading_created','reading',(select value from ctx where key='reading_a'),'2026-02-01','service',(select value from ctx where key='user_1'),'standard','{"reading_id":"reading_a"}');
select pg_temp.assert_true('organizational reading event contract is implemented',exists(select 1 from public.organizational_events where event_type='organizational_reading_created' and entity_id=(select value from ctx where key='reading_a')));
select pg_temp.assert_true('reading event vocabulary is implemented',(select count(*) from public.organizational_event_types where event_type in ('organizational_reading_created','organizational_reading_updated','organizational_reading_supported','organizational_reading_dismissed') and implemented=true)=4);

-- RLS: admin/RH manage own tenant; diretoria reads permitted organizational scope only.
set local role authenticated;
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_1'),true);
select pg_temp.assert_true('admin reads own readings',exists(select 1 from public.intelligence_organizational_readings where organization_id=(select value from ctx where key='org_a')));
select pg_temp.assert_true('admin cannot read tenant B',not exists(select 1 from public.intelligence_organizational_readings where organization_id=(select value from ctx where key='org_b')));
create or replace function pg_temp.cross_tenant_reading_insert() returns boolean language plpgsql security invoker as $$ declare msg text; begin begin insert into public.intelligence_organizational_readings(organization_id,reading_type,scope_type,scope_ref,title,description,knowledge_kind,observation_window_start,observation_window_end,source_summary,context) values((select value from ctx where key='org_b'),'movement','organization','org-b','Cross tenant','Cross tenant','interpreted','2026-01-01','2026-01-02','source','{}'); return false; exception when others then get stacked diagnostics msg=message_text; return msg ilike '%row-level security%'; end; end; $$;
select pg_temp.assert_true('admin cross-tenant write denied',pg_temp.cross_tenant_reading_insert());
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_2'),true);
select pg_temp.assert_true('diretoria reads permitted organizational reading',exists(select 1 from public.intelligence_organizational_readings where organization_id=(select value from ctx where key='org_a') and scope_type='team'));
select pg_temp.assert_true('diretoria cannot read tenant B',not exists(select 1 from public.intelligence_organizational_readings where organization_id=(select value from ctx where key='org_b')));
create or replace function pg_temp.reading_insert_denied() returns boolean language plpgsql security invoker as $$ declare msg text; begin begin insert into public.intelligence_organizational_readings(organization_id,reading_type,scope_type,scope_ref,title,description,knowledge_kind,observation_window_start,observation_window_end,source_summary,context) values((select value from ctx where key='org_a'),'movement','organization','org-a','Unauthorized','Unauthorized','interpreted','2026-01-01','2026-01-02','source','{}'); return false; exception when others then get stacked diagnostics msg=message_text; return msg ilike '%row-level security%'; end; end; $$;
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_3'),true);
select pg_temp.assert_true('gestor has no generic reading access',not exists(select 1 from public.intelligence_organizational_readings where organization_id=(select value from ctx where key='org_a')));
select pg_temp.assert_true('gestor cannot create generic reading',pg_temp.reading_insert_denied());
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_4'),true);
select pg_temp.assert_true('colaborador has no generic reading access',not exists(select 1 from public.intelligence_organizational_readings where organization_id=(select value from ctx where key='org_a')));
select pg_temp.assert_true('colaborador cannot create generic reading',pg_temp.reading_insert_denied());
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_5'),true);
insert into public.intelligence_organizational_readings(id,organization_id,reading_type,scope_type,scope_ref,title,description,knowledge_kind,observation_window_start,observation_window_end,source_summary,context) values((select value from ctx where key='reading_rh'),(select value from ctx where key='org_a'),'gap','organization',(select value from ctx where key='org_a'),'RH reading','RH-managed reading.','interpreted','2026-02-01','2026-02-02','RH provenance','{}');
select pg_temp.assert_true('RH can manage own tenant readings',exists(select 1 from public.intelligence_organizational_readings where id=(select value from ctx where key='reading_rh')));

-- Controlled reading revision preserves history and prevents silent update/delete.
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_1'),true);
select public.revise_organizational_reading((select value from ctx where key='reading_a'),'{"reading_type":"movement","scope_type":"team","scope_ref":"team-a","title":"Turnover movement revised","description":"Revised organizational description.","status":"under_investigation","knowledge_kind":"interpreted","observation_window_start":"2026-01-01T00:00:00Z","observation_window_end":"2026-01-31T00:00:00Z","detected_at":"2026-02-01T00:00:00Z","source_summary":"Same sources, revised description.","context":{"tenure_band":"6-18m","teams":2,"revised":true}}'::jsonb,'admin reading revision');
select pg_temp.assert_true('controlled reading revision updates current state',exists(select 1 from public.intelligence_organizational_readings where id=(select value from ctx where key='reading_a') and status='under_investigation' and knowledge_kind='interpreted'));
select pg_temp.assert_true('reading revision preserves snapshots',exists(select 1 from public.intelligence_organizational_reading_revisions where reading_id=(select value from ctx where key='reading_a') and previous_snapshot->>'title'='Turnover movement in two teams' and new_snapshot->>'title'='Turnover movement revised'));
create or replace function pg_temp.silent_reading_update() returns boolean language plpgsql security invoker as $$ declare msg text; begin begin update public.intelligence_organizational_readings set description='silent overwrite' where id=(select value from ctx where key='reading_a'); return false; exception when others then get stacked diagnostics msg=message_text; return msg ilike '%permission denied%' or msg ilike '%row-level security%'; end; end; $$;
select pg_temp.assert_true('silent reading update is blocked',pg_temp.silent_reading_update());
select pg_temp.assert_true('no automatic downstream records exist',not exists(select 1 from public.intelligence_recommendations where organization_id=(select value from ctx where key='org_a')) and not exists(select 1 from public.intelligence_decisions where organization_id=(select value from ctx where key='org_a')) and not exists(select 1 from public.intelligence_interventions where organization_id=(select value from ctx where key='org_a')) and not exists(select 1 from public.intelligence_actions where organization_id=(select value from ctx where key='org_a')));
select pg_temp.assert_true('no user triggers on Reading Engine tables',not exists(select 1 from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('intelligence_organizational_readings','intelligence_organizational_reading_sources','intelligence_organizational_reading_hypotheses','intelligence_organizational_reading_revisions') and not t.tgisinternal));
select pg_temp.assert_true('Reading Engine stores no raw conversation or prompt',not exists(select 1 from information_schema.columns where table_schema='public' and table_name like 'intelligence_organizational_reading%' and column_name in ('conversation','raw_conversation','prompt','raw_prompt','message','chain_of_thought')));
rollback;
