-- youB — Recommendation & Intervention Model V1 structural suite
-- Disposable staging only. Fixtures are transactional and no migration is applied.
begin;
create temp table ctx(key text primary key, value uuid not null) on commit drop;
do $$ begin
  if to_regclass('public.intelligence_recommendation_evidence') is null then raise exception 'missing recommendation evidence junction'; end if;
  if (select count(*) from auth.users) < 5 then raise exception 'suite requires five auth users'; end if;
end $$;
insert into ctx values
 ('org_a','aaaaaaa1-eeee-eeee-eeee-eeeeeeeeeeee'),('org_b','ffffffff-ffff-ffff-ffff-ffffffffffff'),
 ('employee_a','aaaaaaa1-0000-0000-0000-000000000001'),('employee_b','ffffffff-0000-0000-0000-000000000001'),
 ('recommendation_a','aaaaaaa1-0000-0000-0000-000000000010'),('intervention_a','aaaaaaa1-0000-0000-0000-000000000011'),
 ('signal_a','aaaaaaa1-0000-0000-0000-000000000012'),('evidence_supports','aaaaaaa1-0000-0000-0000-000000000013'),
 ('evidence_contradicts','aaaaaaa1-0000-0000-0000-000000000014'),('evidence_neutral','aaaaaaa1-0000-0000-0000-000000000015');
insert into ctx select 'user_'||row_number() over(order by created_at),id from auth.users order by created_at limit 5;
insert into public.organizations(id,name,slug,plan,status) values ((select value from ctx where key='org_a'),'Recommendation A','recommendation-a','essencial','active'),((select value from ctx where key='org_b'),'Recommendation B','recommendation-b','essencial','active');
insert into public.memberships(organization_id,user_id,role) values ((select value from ctx where key='org_a'),(select value from ctx where key='user_1'),'admin_youb'),((select value from ctx where key='org_a'),(select value from ctx where key='user_2'),'diretoria'),((select value from ctx where key='org_a'),(select value from ctx where key='user_3'),'gestor'),((select value from ctx where key='org_a'),(select value from ctx where key='user_4'),'colaborador'),((select value from ctx where key='org_a'),(select value from ctx where key='user_5'),'rh');
insert into public.employees(id,organization_id,auth_user_id,full_name,email,manager_employee_id) values ((select value from ctx where key='employee_a'),(select value from ctx where key='org_a'),null,'Employee A','employee-a@example.invalid',null),((select value from ctx where key='employee_b'),(select value from ctx where key='org_b'),null,'Employee B','employee-b@example.invalid',null);
insert into public.intelligence_signals(id,organization_id,employee_id,signal_type,source_type) values ((select value from ctx where key='signal_a'),(select value from ctx where key='org_a'),(select value from ctx where key='employee_a'),'fixture','test');
insert into public.intelligence_evidence(id,organization_id,signal_id,evidence_type,summary,relation,independence_group,source_type) values ((select value from ctx where key='evidence_supports'),(select value from ctx where key='org_a'),(select value from ctx where key='signal_a'),'quantitative','supports','supports','source-a','test'),((select value from ctx where key='evidence_contradicts'),(select value from ctx where key='org_a'),(select value from ctx where key='signal_a'),'qualitative','contradicts','contradicts','source-b','test'),((select value from ctx where key='evidence_neutral'),(select value from ctx where key='org_a'),(select value from ctx where key='signal_a'),'documented','neutral','neutral','source-c','test');
insert into public.intelligence_recommendations(id,organization_id,employee_id,title,recommendation_type,evidence_state,problem_statement,unknowns,alternatives,do_not_recommend,measurement_plan,approval_required,context) values ((select value from ctx where key='recommendation_a'),(select value from ctx where key='org_a'),(select value from ctx where key='employee_a'),'Fixture recommendation','monitor','moderate','Factual attention statement','["unknown"]','["alternative"]','["unsupported action"]','{"indicator":"check-in","follow_up":"2026-10-01"}',true,'{}');
insert into public.intelligence_interventions(id,organization_id,recommendation_id,employee_id,intervention_type,intervention_family,title,objective,target_scope_type,success_criteria,measurement_plan,requires_human_approval,context) values ((select value from ctx where key='intervention_a'),(select value from ctx where key='org_a'),(select value from ctx where key='recommendation_a'),(select value from ctx where key='employee_a'),'fixture','investigation','Fixture intervention','Understand context','employee','["criterion"]','{"indicator":"follow-up"}',true,'{}');
insert into public.intelligence_recommendation_evidence(organization_id,recommendation_id,evidence_id) values ((select value from ctx where key='org_a'),(select value from ctx where key='recommendation_a'),(select value from ctx where key='evidence_supports')),((select value from ctx where key='org_a'),(select value from ctx where key='recommendation_a'),(select value from ctx where key='evidence_contradicts')),((select value from ctx where key='org_a'),(select value from ctx where key='recommendation_a'),(select value from ctx where key='evidence_neutral'));
create or replace function pg_temp.probe_recommendation(target_org uuid,target_employee uuid) returns boolean language plpgsql security invoker as $$ declare probe uuid; begin begin insert into public.intelligence_recommendations(organization_id,employee_id,title,recommendation_type) values(target_org,target_employee,'probe','monitor') returning id into probe; delete from public.intelligence_recommendations where id=probe; return true; exception when others then return false; end; end; $$;
create or replace function pg_temp.probe_intervention(target_org uuid,target_employee uuid) returns boolean language plpgsql security invoker as $$ declare probe uuid; begin begin insert into public.intelligence_interventions(organization_id,employee_id,intervention_type,title) values(target_org,target_employee,'probe','probe') returning id into probe; delete from public.intelligence_interventions where id=probe; return true; exception when others then return false; end; end; $$;
create or replace function pg_temp.update_recommendation(target_id uuid) returns boolean language plpgsql security invoker as $$ begin begin update public.intelligence_recommendations set rationale='probe' where id=target_id; return found; exception when others then return false; end; end; $$;
create or replace function pg_temp.update_intervention(target_id uuid) returns boolean language plpgsql security invoker as $$ begin begin update public.intelligence_interventions set title='probe' where id=target_id; return found; exception when others then return false; end; end; $$;
create or replace function pg_temp.invalid_recommendation_type() returns boolean language plpgsql security invoker as $$ begin begin insert into public.intelligence_recommendations(organization_id,employee_id,title,recommendation_type) values((select value from ctx where key='org_a'),(select value from ctx where key='employee_a'),'invalid','invalid'); return true; exception when others then return false; end; end; $$;
create or replace function pg_temp.insufficient_intervene() returns boolean language plpgsql security invoker as $$ begin begin insert into public.intelligence_recommendations(organization_id,employee_id,title,recommendation_type,evidence_state) values((select value from ctx where key='org_a'),(select value from ctx where key='employee_a'),'invalid intervene','intervene','insufficient'); return true; exception when others then return false; end; end; $$;
create or replace function pg_temp.valid_recommendation_types() returns boolean language plpgsql security invoker as $$ declare kind text; probe uuid; begin foreach kind in array array['investigate','intervene','maintain','replicate','monitor','no_action'] loop insert into public.intelligence_recommendations(organization_id,employee_id,title,recommendation_type,evidence_state) values((select value from ctx where key='org_a'),(select value from ctx where key='employee_a'),kind,kind,case when kind='intervene' then 'moderate' else null end) returning id into probe; delete from public.intelligence_recommendations where id=probe; end loop; return true; exception when others then return false; end; $$;
create or replace function pg_temp.valid_intervention_families() returns boolean language plpgsql security invoker as $$ declare family text; probe uuid; begin foreach family in array array['investigation','learning','mentoring','coaching','leadership','process','work_design','communication','recognition','career','succession','mobility','structure','people_practice','consulting','none'] loop insert into public.intelligence_interventions(organization_id,employee_id,intervention_type,intervention_family,title) values((select value from ctx where key='org_a'),(select value from ctx where key='employee_a'),'probe',family,'probe') returning id into probe; delete from public.intelligence_interventions where id=probe; end loop; return true; exception when others then return false; end; $$;
create or replace function pg_temp.invalid_intervention_family() returns boolean language plpgsql security invoker as $$ begin begin insert into public.intelligence_interventions(organization_id,employee_id,intervention_type,intervention_family,title) values((select value from ctx where key='org_a'),(select value from ctx where key='employee_a'),'probe','invalid','probe'); return true; exception when others then return false; end; end; $$;
create or replace function pg_temp.invalid_intervention_dates() returns boolean language plpgsql security invoker as $$ begin begin insert into public.intelligence_interventions(organization_id,employee_id,intervention_type,title,starts_at,expected_end_at) values((select value from ctx where key='org_a'),(select value from ctx where key='employee_a'),'probe','probe','2026-09-02','2026-09-01'); return true; exception when others then return false; end; end; $$;
create or replace function pg_temp.no_automatic_action() returns boolean language plpgsql security invoker as $$ declare i integer;a integer;probe uuid;begin i=(select count(*) from public.intelligence_interventions);a=(select count(*) from public.intelligence_actions);insert into public.intelligence_recommendations(organization_id,employee_id,title,recommendation_type) values((select value from ctx where key='org_a'),(select value from ctx where key='employee_a'),'no automation','monitor') returning id into probe;if i<>(select count(*) from public.intelligence_interventions) or a<>(select count(*) from public.intelligence_actions) then delete from public.intelligence_recommendations where id=probe;return false;end if;delete from public.intelligence_recommendations where id=probe;return true;exception when others then return false;end;$$;
-- Integrity-only probes: deliberately invalid tenant/employee references, retained separately from RLS probes.
create or replace function pg_temp.cross_tenant_recommendation_integrity_fk() returns boolean language plpgsql security invoker as $$ begin begin insert into public.intelligence_recommendations(organization_id,employee_id,title,recommendation_type,evidence_state) values((select value from ctx where key='org_a'),(select value from ctx where key='employee_b'),'integrity probe','monitor','moderate');return true;exception when others then return false;end;end;$$;
create or replace function pg_temp.cross_tenant_intervention_integrity_fk() returns boolean language plpgsql security invoker as $$ begin begin insert into public.intelligence_interventions(organization_id,recommendation_id,employee_id,intervention_type,intervention_family,title) values((select value from ctx where key='org_a'),(select value from ctx where key='recommendation_a'),(select value from ctx where key='employee_b'),'integrity','investigation','integrity probe');return true;exception when others then return false;end;end;$$;
-- RLS probes: both payloads are valid in tenant B; denial must come from missing tenant-B authorization.
create or replace function pg_temp.cross_tenant_recommendation_rls() returns boolean language plpgsql security invoker as $$ declare probe uuid; begin begin insert into public.intelligence_recommendations(organization_id,employee_id,title,recommendation_type,evidence_state,problem_statement,unknowns,alternatives,do_not_recommend,measurement_plan,approval_required,context) values((select value from ctx where key='org_b'),(select value from ctx where key='employee_b'),'valid tenant B probe','monitor','moderate','Factual tenant B probe statement','["unknown"]','["alternative"]','["unsupported action"]','{"indicator":"check-in"}',false,'{}') returning id into probe; delete from public.intelligence_recommendations where id=probe; return true; exception when others then return false; end; end; $$;
create or replace function pg_temp.cross_tenant_intervention_rls() returns boolean language plpgsql security invoker as $$ declare probe uuid; begin begin insert into public.intelligence_interventions(organization_id,employee_id,intervention_type,intervention_family,title,objective,target_scope_type,success_criteria,measurement_plan,requires_human_approval,context) values((select value from ctx where key='org_b'),(select value from ctx where key='employee_b'),'valid tenant B probe','investigation','Valid tenant B probe','Understand context','employee','["criterion"]','{"indicator":"follow-up"}',true,'{}') returning id into probe; delete from public.intelligence_interventions where id=probe; return true; exception when others then return false; end; end; $$;
create or replace function pg_temp.invalid_evidence_state() returns boolean language plpgsql security invoker as $$ begin begin insert into public.intelligence_recommendations(organization_id,employee_id,title,evidence_state) values((select value from ctx where key='org_a'),(select value from ctx where key='employee_a'),'invalid evidence','invalid'); return true; exception when others then return false; end; end; $$;
create or replace function pg_temp.bad_recommendation_evidence_junction() returns boolean language plpgsql security invoker as $$ begin begin insert into public.intelligence_recommendation_evidence(organization_id,recommendation_id,evidence_id) values((select value from ctx where key='org_b'),(select value from ctx where key='recommendation_a'),(select value from ctx where key='evidence_supports')); return true; exception when others then return false; end; end; $$;
create or replace function pg_temp.assert_true(label text, condition boolean) returns void language plpgsql as $$ begin if condition is distinct from true then raise exception 'FAIL-FAST assertion: %', label; end if; end; $$;
set local role authenticated;
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_1'),true);
select jsonb_build_object('valid_recommendation_types',pg_temp.valid_recommendation_types(),'invalid_recommendation_type_rejected',not pg_temp.invalid_recommendation_type(),'insufficient_intervene_rejected',not pg_temp.insufficient_intervene(),'valid_intervention_families',pg_temp.valid_intervention_families(),'invalid_intervention_family_rejected',not pg_temp.invalid_intervention_family(),'invalid_intervention_dates_rejected',not pg_temp.invalid_intervention_dates(),'recommendation_evidence_junction_preserved',(select count(*)=3 from public.intelligence_recommendation_evidence where recommendation_id=(select value from ctx where key='recommendation_a')),'contradictory_evidence_allowed',(select count(*)=1 from public.intelligence_recommendation_evidence re join public.intelligence_evidence e on e.id=re.evidence_id where re.recommendation_id=(select value from ctx where key='recommendation_a') and e.relation='contradicts'),'no_automatic_action',pg_temp.no_automatic_action(),'admin_same_tenant_recommendation',pg_temp.probe_recommendation((select value from ctx where key='org_a'),(select value from ctx where key='employee_a')),'admin_same_tenant_intervention',pg_temp.probe_intervention((select value from ctx where key='org_a'),(select value from ctx where key='employee_a')),'admin_cross_tenant_recommendation_denied',not pg_temp.cross_tenant_recommendation_rls(),'admin_cross_tenant_intervention_denied',not pg_temp.cross_tenant_intervention_rls(),'admin_cross_tenant_integrity_fk_denied',not pg_temp.cross_tenant_recommendation_integrity_fk() and not pg_temp.cross_tenant_intervention_integrity_fk()) as admin_assertions;
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_5'),true);
select jsonb_build_object('rh_same_tenant_recommendation',pg_temp.probe_recommendation((select value from ctx where key='org_a'),(select value from ctx where key='employee_a')),'rh_same_tenant_intervention',pg_temp.probe_intervention((select value from ctx where key='org_a'),(select value from ctx where key='employee_a')),'rh_cross_tenant_recommendation_denied',not pg_temp.cross_tenant_recommendation_rls(),'rh_cross_tenant_intervention_denied',not pg_temp.cross_tenant_intervention_rls()) as rh_assertions;
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_2'),true);
select jsonb_build_object('diretoria_cannot_insert_recommendation',not pg_temp.probe_recommendation((select value from ctx where key='org_a'),(select value from ctx where key='employee_a')),'diretoria_cannot_update_recommendation',not pg_temp.update_recommendation((select value from ctx where key='recommendation_a')),'diretoria_cannot_insert_intervention',not pg_temp.probe_intervention((select value from ctx where key='org_a'),(select value from ctx where key='employee_a')),'diretoria_cannot_update_intervention',not pg_temp.update_intervention((select value from ctx where key='intervention_a'))) as diretoria_assertions;
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_3'),true);
select jsonb_build_object('manager_cannot_insert_recommendation',not pg_temp.probe_recommendation((select value from ctx where key='org_a'),(select value from ctx where key='employee_a')),'manager_cannot_update_recommendation',not pg_temp.update_recommendation((select value from ctx where key='recommendation_a')),'manager_cannot_insert_intervention',not pg_temp.probe_intervention((select value from ctx where key='org_a'),(select value from ctx where key='employee_a')),'manager_cannot_update_intervention',not pg_temp.update_intervention((select value from ctx where key='intervention_a'))) as manager_assertions;
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_4'),true);
select jsonb_build_object('collaborator_cannot_insert_recommendation',not pg_temp.probe_recommendation((select value from ctx where key='org_a'),(select value from ctx where key='employee_a')),'collaborator_cannot_update_recommendation',not pg_temp.update_recommendation((select value from ctx where key='recommendation_a')),'collaborator_cannot_insert_intervention',not pg_temp.probe_intervention((select value from ctx where key='org_a'),(select value from ctx where key='employee_a')),'collaborator_cannot_update_intervention',not pg_temp.update_intervention((select value from ctx where key='intervention_a'))) as collaborator_assertions;
-- JSON above is diagnostic only. These assertions are authoritative and fail-fast.
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_1'),true);
select pg_temp.assert_true('invalid recommendation_type rejected',not pg_temp.invalid_recommendation_type());
select pg_temp.assert_true('invalid evidence_state rejected',not pg_temp.invalid_evidence_state());
select pg_temp.assert_true('insufficient plus intervene rejected',not pg_temp.insufficient_intervene());
select pg_temp.assert_true('invalid intervention_family rejected',not pg_temp.invalid_intervention_family());
select pg_temp.assert_true('invalid intervention dates rejected',not pg_temp.invalid_intervention_dates());
select pg_temp.assert_true('recommendation-evidence junction preserved',((select count(*) from public.intelligence_recommendation_evidence where recommendation_id=(select value from ctx where key='recommendation_a'))=3));
select pg_temp.assert_true('contradictory evidence preserved',((select count(*) from public.intelligence_recommendation_evidence re join public.intelligence_evidence e on e.id=re.evidence_id where re.recommendation_id=(select value from ctx where key='recommendation_a') and e.relation='contradicts')=1));
select pg_temp.assert_true('admin cross-tenant recommendation denied',not pg_temp.cross_tenant_recommendation_rls());
select pg_temp.assert_true('admin cross-tenant intervention denied',not pg_temp.cross_tenant_intervention_rls());
select pg_temp.assert_true('admin wrong junction denied',not pg_temp.bad_recommendation_evidence_junction());
select pg_temp.assert_true('no automatic intervention or action',pg_temp.no_automatic_action());
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_5'),true);
select pg_temp.assert_true('RH cross-tenant recommendation denied',not pg_temp.cross_tenant_recommendation_rls());
select pg_temp.assert_true('RH cross-tenant intervention denied',not pg_temp.cross_tenant_intervention_rls());
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_2'),true);
select pg_temp.assert_true('diretoria recommendation insert denied',not pg_temp.probe_recommendation((select value from ctx where key='org_a'),(select value from ctx where key='employee_a')));
select pg_temp.assert_true('diretoria recommendation update denied',not pg_temp.update_recommendation((select value from ctx where key='recommendation_a')));
select pg_temp.assert_true('diretoria intervention insert denied',not pg_temp.probe_intervention((select value from ctx where key='org_a'),(select value from ctx where key='employee_a')));
select pg_temp.assert_true('diretoria intervention update denied',not pg_temp.update_intervention((select value from ctx where key='intervention_a')));
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_3'),true);
select pg_temp.assert_true('gestor recommendation insert denied',not pg_temp.probe_recommendation((select value from ctx where key='org_a'),(select value from ctx where key='employee_a')));
select pg_temp.assert_true('gestor recommendation update denied',not pg_temp.update_recommendation((select value from ctx where key='recommendation_a')));
select pg_temp.assert_true('gestor intervention insert denied',not pg_temp.probe_intervention((select value from ctx where key='org_a'),(select value from ctx where key='employee_a')));
select pg_temp.assert_true('gestor intervention update denied',not pg_temp.update_intervention((select value from ctx where key='intervention_a')));
select set_config('request.jwt.claim.sub',(select value::text from ctx where key='user_4'),true);
select pg_temp.assert_true('collaborator recommendation insert denied',not pg_temp.probe_recommendation((select value from ctx where key='org_a'),(select value from ctx where key='employee_a')));
select pg_temp.assert_true('collaborator recommendation update denied',not pg_temp.update_recommendation((select value from ctx where key='recommendation_a')));
select pg_temp.assert_true('collaborator intervention insert denied',not pg_temp.probe_intervention((select value from ctx where key='org_a'),(select value from ctx where key='employee_a')));
select pg_temp.assert_true('collaborator intervention update denied',not pg_temp.update_intervention((select value from ctx where key='intervention_a')));
rollback;

