import type { SupabaseSession } from "../../lib/supabase";

export type Feedback360Role = "admin_youb" | "rh" | "diretoria" | "gestor" | "colaborador";
export type Feedback360Round = { id: string; cycle_id: string; name: string; description?: string | null; confidentiality_mode: "confidential"; status: "draft" | "active" | "closed"; activated_at?: string | null; closed_at?: string | null };
export type Feedback360Cycle = { id: string; name: string; status: "draft" | "active" | "closed" };
export type Feedback360Employee = { id: string; full_name: string; position_id?: string | null; manager_employee_id?: string | null; auth_user_id?: string | null };
export type Feedback360Participant = { id: string; round_id: string; subject_employee_id: string; evaluator_employee_id: string; relationship_type: "self" | "manager" | "peer" | "direct_report"; status: "pending" | "in_progress" | "submitted"; submitted_at?: string | null };
export type Feedback360Criterion = { id: string; round_id: string; subject_employee_id: string; competency_id: string; expected_level_snapshot: number };
export type Feedback360Score = { id: string; participant_id: string; subject_competency_id: string; score?: number | null; comment?: string | null };
export type Feedback360SubjectResult = { round_id: string; subject_employee_id: string; competency_id: string; competency_name: string; position_id: string; relationship_type: "self" | "manager" | "peer" | "direct_report"; response_count: number; average_score: number; expected_level_snapshot: number; feedback_comment?: string | null };
export type Feedback360Aggregate = { round_id: string; competency_id: string; competency_name: string; source_role: string; position_id: string; subject_count: number; response_count: number; average_score: number };
export type Feedback360Evolution = { source_type: string; cycle_id: string; round_id?: string | null; competency_id: string; competency_name: string; position_id: string; expected_level_snapshot: number; score: number; previous_score?: number | null; delta?: number | null; distance_to_expected: number; completed_at: string };

const baseUrl = ((import.meta.env.VITE_SUPABASE_URL as string | undefined) ?? "").replace(/\/$/, "");
const anonKey = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;
function config() { if (!baseUrl || !anonKey) throw new Error("O ambiente ainda não está conectado ao Supabase."); return { baseUrl, anonKey }; }
function enc(value: string): string { return encodeURIComponent(value); }
async function request<T>(session: SupabaseSession, path: string, options: RequestInit = {}): Promise<T> { const c = config(); const response = await fetch(`${c.baseUrl}/rest/v1/${path}`, { ...options, headers: { apikey: c.anonKey, Authorization: `Bearer ${session.access_token}`, "Content-Type": "application/json", ...(options.headers ?? {}) } }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error((body && typeof body === "object" && ((body as { message?: string }).message || (body as { details?: string }).details)) || "Não foi possível concluir a operação."); return body as T; }
export async function rpc<T>(session: SupabaseSession, name: string, payload: Record<string, unknown>): Promise<T> { return request<T>(session, `rpc/${name}`, { method: "POST", body: JSON.stringify(payload) }); }
export async function readRounds(session: SupabaseSession, organizationId: string): Promise<Feedback360Round[]> { return request<Feedback360Round[]>(session, `feedback_360_rounds?select=id,cycle_id,name,description,confidentiality_mode,status,activated_at,closed_at&organization_id=eq.${enc(organizationId)}&order=created_at.desc`); }
export async function readCycles(session: SupabaseSession, organizationId: string): Promise<Feedback360Cycle[]> { return request<Feedback360Cycle[]>(session, `cycles?select=id,name,status&organization_id=eq.${enc(organizationId)}&order=created_at.desc`); }
export async function readEmployees(session: SupabaseSession, organizationId: string): Promise<Feedback360Employee[]> { return request<Feedback360Employee[]>(session, `employees?select=id,full_name,position_id,manager_employee_id,auth_user_id&organization_id=eq.${enc(organizationId)}&order=full_name`); }
export async function readCompetencies(session: SupabaseSession, organizationId: string): Promise<Array<{ id: string; name: string }>> { return request<Array<{ id: string; name: string }>>(session, `competencies?select=id,name&organization_id=eq.${enc(organizationId)}&order=name`); }
export async function readParticipants(session: SupabaseSession, organizationId: string, roundId?: string): Promise<Feedback360Participant[]> { const filter = roundId ? `&round_id=eq.${enc(roundId)}` : ""; return request<Feedback360Participant[]>(session, `feedback_360_participants?select=id,round_id,subject_employee_id,evaluator_employee_id,relationship_type,status,submitted_at&organization_id=eq.${enc(organizationId)}${filter}&order=created_at.desc`); }
export async function readScores(session: SupabaseSession, organizationId: string, participantId: string): Promise<Feedback360Score[]> { return request<Feedback360Score[]>(session, `feedback_360_scores?select=id,participant_id,subject_competency_id,score,comment&organization_id=eq.${enc(organizationId)}&participant_id=eq.${enc(participantId)}&order=created_at`); }
export async function readCriteria(session: SupabaseSession, organizationId: string, roundId: string, subjectId: string): Promise<Feedback360Criterion[]> { return request<Feedback360Criterion[]>(session, `feedback_360_subject_competencies?select=id,round_id,subject_employee_id,competency_id,expected_level_snapshot&organization_id=eq.${enc(organizationId)}&round_id=eq.${enc(roundId)}&subject_employee_id=eq.${enc(subjectId)}&order=created_at`); }
export async function readSubjectResult(session: SupabaseSession, organizationId: string, roundId: string, subjectId: string): Promise<Feedback360SubjectResult[]> { return rpc<Feedback360SubjectResult[]>(session, "fb360_read_subject_result", { p_organization_id: organizationId, p_round_id: roundId, p_subject_employee_id: subjectId }); }
export async function readAggregate(session: SupabaseSession, organizationId: string, roundId: string): Promise<Feedback360Aggregate[]> { return rpc<Feedback360Aggregate[]>(session, "fb360_read_organization_aggregate", { p_organization_id: organizationId, p_round_id: roundId }); }
export async function readEvolution(session: SupabaseSession, organizationId: string, subjectId: string, origin?: string): Promise<Feedback360Evolution[]> { return rpc<Feedback360Evolution[]>(session, "fb360_read_evolution", { p_organization_id: organizationId, p_subject_employee_id: subjectId, p_origin_filter: origin || null }); }
