import { useEffect, useMemo, useState, type ReactNode } from "react";
import EmployeeExperienceRoute from "./EmployeeExperienceRoute";
import ExecutiveHome from "../mockups/ExecutiveHome";
import { contextResultMessage, employeeLinkMessage, requiresEmployeeLink, resolveEmployeeExperienceContext, restoreSession, type EmployeeExperienceContext, type SupabaseSession } from "../../lib/supabase";
import { handleBeeIntent, readBeeRuntime, type BeeIntent, type BeeRuntimeContext, type BeeRuntimeReadModel } from "../../features/intelligence-core/bee-runtime";
import { appPath } from "../../lib/app-paths";

async function safeSession(): Promise<SupabaseSession | null> { return restoreSession(); }
function displayName(session: SupabaseSession, context: EmployeeExperienceContext): string { return context.employee?.full_name || (typeof session.user.user_metadata?.full_name === "string" ? session.user.user_metadata.full_name : null) || session.user.email || "Usuário autenticado"; }
function selectedOrganizationId(): string | undefined { const raw = window.localStorage.getItem("youb-organization"); return raw ? (JSON.parse(raw) as { id?: string }).id : undefined; }
function buildRuntimeContext(session: SupabaseSession, context: EmployeeExperienceContext): BeeRuntimeContext { const role = context.membership.role; if (requiresEmployeeLink(role) && context.employeeLinkStatus !== "linked") throw new Error(employeeLinkMessage(context.employeeLinkStatus)); const authorizedScopes = role === "gestor" && context.employeeId ? [{ scopeType: "employee" as const, scopeRefs: [context.employeeId], sensitivity: ["standard" as const] }] : role === "colaborador" && context.employeeId ? [{ scopeType: "personal" as const, scopeRefs: [context.employeeId], sensitivity: ["standard" as const] }] : [{ scopeType: "organization" as const, scopeRefs: [context.organization.id], sensitivity: ["standard" as const] }]; return { organizationId: context.organization.id, userId: session.user.id, role, employeeId: context.employeeId, authorizedScopes, sensitivity: ["standard"], purpose: "executive_home", session }; }
function welcomeRole(role: EmployeeExperienceContext["membership"]["role"]): string { return role === "diretoria" ? "Visão executiva para decisões melhores sobre pessoas." : role === "rh" || role === "admin_youb" ? "Uma visão por exceção para cuidar do que pede sua atenção." : "O que está autorizado para sua equipe, em um só lugar."; }
function PageMessage({ title, detail, action }: { title: string; detail: string; action?: ReactNode }) { return <main className="flex min-h-screen items-center justify-center bg-background px-5 text-foreground"><section className="max-w-md rounded-3xl border border-border bg-card p-8 text-center shadow-sm"><h1 className="text-xl font-bold">{title}</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">{detail}</p>{action}</section></main>; }

export default function ExecutiveHomeRoute() {
  const [session, setSession] = useState<SupabaseSession | null>(null); const [organizationContext, setOrganizationContext] = useState<EmployeeExperienceContext | null>(null); const [model, setModel] = useState<BeeRuntimeReadModel | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [beeResponse, setBeeResponse] = useState<string | null>(null);
  useEffect(() => { let cancelled = false; void safeSession().then(async (savedSession) => { if (!savedSession) { setLoading(false); return; } try { const result = await resolveEmployeeExperienceContext(savedSession, selectedOrganizationId()); if (cancelled) return; if (result.status !== "ready") { setError(contextResultMessage(result)); return; } if (requiresEmployeeLink(result.context.membership.role) && result.context.employeeLinkStatus !== "linked") { setError(employeeLinkMessage(result.context.employeeLinkStatus)); return; } setSession(savedSession); setOrganizationContext(result.context); if (result.context.membership.role === "colaborador") return; const runtimeModel = await readBeeRuntime(buildRuntimeContext(savedSession, result.context)); if (!cancelled) setModel(runtimeModel); } catch (routeError) { if (!cancelled) setError(routeError instanceof Error ? routeError.message : "Não foi possível carregar o contexto da organização."); } finally { if (!cancelled) setLoading(false); } }).catch(() => { if (!cancelled) { setError("Não foi possível restaurar sua sessão."); setLoading(false); } }); return () => { cancelled = true; }; }, []);
  const runtimeContext = useMemo(() => session && organizationContext ? buildRuntimeContext(session, organizationContext) : null, [session, organizationContext]);
  function runIntent(intent: BeeIntent) { if (!model) return; const result = handleBeeIntent(model, intent); if (intent === "attention_today") setBeeResponse(result.attention?.length ? `${result.attention.length} prioridade(s) com contexto disponível. Abra um card para ver a explicação.` : "Nenhum item exige atenção especial agora."); else if (intent === "list_open_readings") setBeeResponse(result.readings?.length ? `${result.readings.length} Leitura(s) Organizacional(is) aberta(s).` : "Nenhuma Leitura Organizacional aberta no momento."); else if (intent === "list_unknowns") setBeeResponse(result.unknowns?.length ? `${result.unknowns.length} ponto(s) ainda precisam de investigação.` : "Não há unknowns registrados neste contexto."); else if (intent === "list_actions") setBeeResponse(result.actions?.length ? `${result.actions.length} Action(s) autorizada(s) estão disponíveis.` : "Nenhuma Action disponível neste contexto."); }
  if (loading) return <PageMessage title="Preparando sua Home executiva" detail="Estamos reunindo apenas os dados e conhecimentos permitidos para você." />;
  if (!session) return <PageMessage title="Acesse sua conta" detail="Entre na youB para visualizar sua Home executiva." action={<a className="mt-5 inline-flex rounded-full bg-primary px-4 py-2 text-sm font-bold text-primary-foreground" href={appPath("/preview/Onboarding")}>Abrir acesso</a>} />;
  if (error || !organizationContext) return <PageMessage title="Contexto indisponível" detail={error ?? "Não foi possível identificar sua organização."} />;
  if (organizationContext.membership.role === "colaborador") return <EmployeeExperienceRoute />;
  if (!model || !runtimeContext) return <PageMessage title="Visão executiva indisponível" detail="As fontes autorizadas estão vazias, indisponíveis ou insuficientes para preparar esta Home. Nenhuma métrica foi fabricada." />;
  const sourceStates = Object.values(model.sourceStatus ?? {}); const hasAvailableSource = sourceStates.some((item) => item.status === "available"); const hasOnlyEmptySources = sourceStates.length > 0 && sourceStates.every((item) => item.status === "empty");
  if (!hasAvailableSource) return <PageMessage title="Contexto executivo insuficiente" detail={hasOnlyEmptySources ? "As fontes autorizadas estão disponíveis, mas ainda não possuem registros suficientes para preparar indicadores." : "Uma ou mais fontes autorizadas estão indisponíveis ou não autorizadas. Nenhuma métrica foi fabricada."} />;
  return <ExecutiveHome displayName={displayName(session, organizationContext)} organizationName={organizationContext.organization.name} runtimeContext={runtimeContext} model={model} onIntent={runIntent} beeResponse={beeResponse} />;
}

export function executiveWelcome(role: EmployeeExperienceContext["membership"]["role"]): string { return welcomeRole(role); }
