import { useEffect, useMemo, useState, type ReactNode } from "react";
import ExecutiveHome from "../mockups/ExecutiveHome";
import EmployeeExperienceRoute from "./EmployeeExperienceRoute";
import { getEmployeeExperienceContext, type EmployeeExperienceContext, type SupabaseSession } from "../../lib/supabase";
import { handleBeeIntent, readBeeRuntime, type BeeIntent, type BeeRuntimeContext, type BeeRuntimeReadModel } from "../../features/intelligence-core/bee-runtime";
import { appPath } from "../../lib/app-paths";

function safeSession(): SupabaseSession | null { try { const raw = window.localStorage.getItem("youb-session"); return raw ? JSON.parse(raw) as SupabaseSession : null; } catch { return null; } }
function displayName(session: SupabaseSession, context: EmployeeExperienceContext): string { return context.employee?.full_name || (typeof session.user.user_metadata?.full_name === "string" ? session.user.user_metadata.full_name : null) || session.user.email || "Usuário autenticado"; }
function buildRuntimeContext(session: SupabaseSession, context: EmployeeExperienceContext): BeeRuntimeContext { const role = context.membership.role; const authorizedScopes = role === "gestor" && context.employeeId ? [{ scopeType: "employee" as const, scopeRefs: [context.employeeId], sensitivity: ["standard" as const] }] : role === "colaborador" && context.employeeId ? [{ scopeType: "personal" as const, scopeRefs: [context.employeeId], sensitivity: ["standard" as const] }] : [{ scopeType: "organization" as const, scopeRefs: [context.organization.id], sensitivity: ["standard" as const] }]; return { organizationId: context.organization.id, userId: session.user.id, role, employeeId: context.employeeId, authorizedScopes, sensitivity: ["standard"], purpose: "executive_home", session }; }
function welcomeRole(role: EmployeeExperienceContext["membership"]["role"]): string { return role === "diretoria" ? "Visão executiva para decisões melhores sobre pessoas." : role === "rh" || role === "admin_youb" ? "Uma visão por exceção para cuidar do que pede sua atenção." : "O que está autorizado para sua equipe, em um só lugar."; }
function PageMessage({ title, detail, action }: { title: string; detail: string; action?: ReactNode }) { return <main className="flex min-h-screen items-center justify-center bg-background px-5 text-foreground"><section className="max-w-md rounded-3xl border border-border bg-card p-8 text-center shadow-sm"><h1 className="text-xl font-bold">{title}</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">{detail}</p>{action}</section></main>; }

export default function ExecutiveHomeRoute() {
  const [session, setSession] = useState<SupabaseSession | null>(null); const [organizationContext, setOrganizationContext] = useState<EmployeeExperienceContext | null>(null); const [model, setModel] = useState<BeeRuntimeReadModel | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [beeResponse, setBeeResponse] = useState<string | null>(null);
  useEffect(() => { const savedSession = safeSession(); if (!savedSession) { setLoading(false); return; } let cancelled = false; void getEmployeeExperienceContext(savedSession).then(async (context) => { if (cancelled || !context) { if (!cancelled) setError("O contexto autenticado ainda não foi carregado."); return; } setSession(savedSession); setOrganizationContext(context); if (context.membership.role === "colaborador") return; try { const runtimeContext = buildRuntimeContext(savedSession, context); const runtimeModel = await readBeeRuntime(runtimeContext); if (!cancelled) setModel(runtimeModel); } catch { if (!cancelled) setError("Não foi possível carregar a visão executiva agora."); } }).catch(() => { if (!cancelled) setError("Não foi possível carregar o contexto da organização."); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, []);
  const runtimeContext = useMemo(() => session && organizationContext ? buildRuntimeContext(session, organizationContext) : null, [session, organizationContext]);
  function runIntent(intent: BeeIntent) { if (!model) return; const result = handleBeeIntent(model, intent); if (intent === "attention_today") setBeeResponse(result.attention?.length ? `${result.attention.length} prioridade(s) com contexto disponível. Abra um card para ver a explicação.` : "Nenhum item exige atenção especial agora."); else if (intent === "list_open_readings") setBeeResponse(result.readings?.length ? `${result.readings.length} Leitura(s) Organizacional(is) aberta(s).` : "Nenhuma Leitura Organizacional aberta no momento."); else if (intent === "list_unknowns") setBeeResponse(result.unknowns?.length ? `${result.unknowns.length} ponto(s) ainda precisam de investigação.` : "Não há unknowns registrados neste contexto."); else if (intent === "list_actions") setBeeResponse(result.actions?.length ? `${result.actions.length} Action(s) autorizada(s) estão disponíveis.` : "Nenhuma Action disponível neste contexto."); }
  if (loading) return <PageMessage title="Preparando sua Home executiva" detail="Estamos reunindo apenas os dados e conhecimentos permitidos para você." />;
  if (!session) return <PageMessage title="Acesse sua conta" detail="Entre na youB para visualizar sua Home executiva." action={<a className="mt-5 inline-flex rounded-full bg-primary px-4 py-2 text-sm font-bold text-primary-foreground" href={appPath("/preview/Onboarding")}>Abrir acesso</a>} />;
  if (error || !organizationContext) return <PageMessage title="Contexto indisponível" detail={error ?? "Não foi possível identificar sua organização."} />;
  if (organizationContext.membership.role === "colaborador") return <EmployeeExperienceRoute />;
  if (!model || !runtimeContext) return <PageMessage title="Visão executiva indisponível" detail="Os contratos autorizados ainda não estão disponíveis. Tente novamente em instantes." />;
  return <ExecutiveHome displayName={displayName(session, organizationContext)} organizationName={organizationContext.organization.name} runtimeContext={runtimeContext} model={model} onIntent={runIntent} beeResponse={beeResponse} />;
}

export function executiveWelcome(role: EmployeeExperienceContext["membership"]["role"]): string { return welcomeRole(role); }
