// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/BeeShell.tsx": () => import("../components/mockups/BeeShell.tsx"),
  "./components/mockups/CompetencyCycleAssessment.tsx": () => import("../components/mockups/CompetencyCycleAssessment.tsx"),
  "./components/mockups/Dashboard.tsx": () => import("../components/mockups/Dashboard.tsx"),
  "./components/mockups/EmployeeHome.tsx": () => import("../components/mockups/EmployeeHome.tsx"),
  "./components/mockups/ExecutiveHome.tsx": () => import("../components/mockups/ExecutiveHome.tsx"),
  "./components/mockups/Feedback360Evolution.tsx": () => import("../components/mockups/Feedback360Evolution.tsx"),
  "./components/mockups/Onboarding.tsx": () => import("../components/mockups/Onboarding.tsx"),
  "./components/mockups/PdiDevelopment.tsx": () => import("../components/mockups/PdiDevelopment.tsx")
};
