import { useMemo, useState, type ReactNode } from "react";
import { Activity, ArrowRight, BookOpen, BrainCircuit, Check, ChevronRight, CircleHelp, Compass, Filter, Heart, Menu, Network, Search, ShieldCheck, Sparkles, Target, Users, Workflow, X } from "lucide-react";

type Role = "diretoria" | "rh" | "gestor" | "colaborador";
type Screen = "home" | "organization" | "team" | "week" | "evolution" | "rh";

const roleNames: Record<Role, string> = { diretoria: "Diretoria", rh: "RH", gestor: "Líder", colaborador: "Colaborador" };
const roleNav: Record<Role, { id: Screen; label: string; icon: typeof Activity }[]> = {
  diretoria: [{ id: "home", label: "Organização agora", icon: Activity }, { id: "organization", label: "Organização Viva", icon: Network }, { id: "rh", label: "Leituras Organizacionais", icon: BrainCircuit }],
  rh: [{ id: "home", label: "Intelligence Workspace", icon: Activity }, { id: "organization", label: "Organização Viva", icon: Network }, { id: "rh", label: "Investigar", icon: Search }],
  gestor: [{ id: "home", label: "Hoje", icon: Activity }, { id: "week", label: "Semana", icon: Workflow }, { id: "evolution", label: "Evolução", icon: Target }, { id: "team", label: "Meu time", icon: Users }, { id: "organization", label: "Organização Viva", icon: Network }],
  colaborador: [{ id: "home", label: "Minha evolução", icon: Activity }, { id: "evolution", label: "Desenvolvimento", icon: Target }, { id: "organization", label: "Eu", icon: BookOpen }],
};

function DemoBadge() { return <span className="youb-badge">Demonstração visual · dados sintéticos</span>; }
function Logo() { return <div className="flex items-center gap-2" aria-label="youB"><span className="text-2xl font-semibold tracking-[-0.08em] text-[var(--youb-navy)]">you</span><span className="text-3xl font-black tracking-[-0.08em] text-[var(--youb-violet)]">B</span></div>; }
function Label({ children }: { children: string }) { return <p className="youb-eyebrow">{children}</p>; }

function BeePanel({ onClose }: { onClose: () => void }) {
  const prompts = ["O que mudou?", "O que merece minha atenção?", "Preparar próximo passo"];
  return <div className="fixed inset-0 z-50 flex items-end justify-end bg-[rgba(17,24,58,.28)] p-3 backdrop-blur-sm sm:p-6" role="presentation"><section className="w-full max-w-md overflow-hidden rounded-[1.75rem] border border-[var(--youb-line)] bg-white shadow-[0_24px_80px_rgba(20,25,70,.22)]" role="dialog" aria-modal="true" aria-label="Bee, presença contextual"><header className="bg-[var(--youb-navy)] p-5 text-white"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-white/10"><BrainCircuit size={23} /></div><div><Label>Bee · presença contextual</Label><h2 className="mt-1 text-lg font-semibold">Clareza para o próximo movimento.</h2></div></div><button type="button" onClick={onClose} aria-label="Fechar Bee" className="rounded-full p-2 text-white/70 hover:bg-white/10"><X size={17} /></button></div><p className="mt-4 text-sm leading-6 text-white/70">A Bee organiza e explica o contexto autorizado. A decisão continua humana.</p></header><div className="space-y-3 p-5"><div className="youb-callout"><div className="flex items-center gap-2 text-xs font-semibold text-[var(--youb-violet-deep)]"><ShieldCheck size={15} /> Contexto permitido</div><p className="mt-2 text-xs leading-5 text-[var(--youb-ink-soft)]">Esta é uma demonstração visual. Nenhuma ação é executada automaticamente.</p></div>{prompts.map((prompt) => <button key={prompt} type="button" className="flex w-full items-center justify-between rounded-xl border border-[var(--youb-line)] px-4 py-3 text-left text-sm font-semibold text-[var(--youb-ink)] transition hover:border-[var(--youb-violet)] hover:bg-[var(--youb-lilac)]">{prompt}<ArrowRight size={15} className="text-[var(--youb-violet)]" /></button>)}<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-950"><strong>Confirmação humana</strong><br />Quando houver contexto suficiente, a Bee prepara a revisão antes de qualquer decisão.</div></div></section></div>;
}

function Header({ role, onRole, onMenu }: { role: Role; onRole: (role: Role) => void; onMenu: () => void }) {
  return <header className="sticky top-0 z-30 border-b border-[var(--youb-line)] bg-[rgba(252,252,255,.9)] px-4 py-3 backdrop-blur-xl sm:px-7"><div className="mx-auto flex max-w-[1500px] items-center gap-4"><Logo /><span className="hidden h-7 w-px bg-[var(--youb-line)] md:block" /><div className="relative hidden min-w-0 flex-1 md:block"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-[var(--youb-violet)]" size={16} /><input aria-label="Buscar contexto" className="h-10 w-full rounded-full border border-[var(--youb-line)] bg-white pl-11 pr-4 text-sm text-[var(--youb-ink)] outline-none transition focus:border-[var(--youb-violet)] focus:ring-4 focus:ring-[var(--youb-lilac)]" placeholder="O que você quer entender hoje?" /></div><button type="button" aria-label="Abrir navegação" onClick={onMenu} className="ml-auto rounded-full p-2 text-[var(--youb-violet)] hover:bg-[var(--youb-lilac)] md:hidden"><Menu size={19} /></button><div className="hidden items-center gap-2 sm:flex"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-[var(--youb-lilac)] text-xs font-black text-[var(--youb-violet-deep)]">A</div><span className="text-xs font-semibold text-[var(--youb-ink-soft)]">{roleNames[role]}</span></div><select aria-label="Perfil da demonstração" value={role} onChange={(event) => onRole(event.target.value as Role)} className="max-w-[118px] rounded-full border border-[var(--youb-line)] bg-white px-3 py-2 text-xs font-semibold text-[var(--youb-ink)] outline-none focus:border-[var(--youb-violet)]"><option value="diretoria">Diretoria</option><option value="rh">RH</option><option value="gestor">Líder</option><option value="colaborador">Colaborador</option></select></div></header>;
}

function ShellNav({ role, screen, onScreen, open }: { role: Role; screen: Screen; onScreen: (screen: Screen) => void; open: boolean }) {
  return <aside className={`${open ? "flex" : "hidden"} fixed inset-x-0 bottom-0 z-20 border-t border-[var(--youb-line)] bg-white/95 px-2 py-2 backdrop-blur-xl md:static md:flex md:w-56 md:shrink-0 md:border-0 md:bg-transparent md:px-0 md:py-0`}><div className="flex w-full justify-around gap-1 md:sticky md:top-24 md:flex-col md:gap-2">{roleNav[role].map(({ id, label, icon: Icon }) => <button key={id} type="button" onClick={() => onScreen(id)} aria-current={screen === id ? "page" : undefined} className={`flex min-w-0 flex-1 flex-col items-center gap-1 rounded-xl px-2 py-2 text-[10px] font-semibold transition md:flex-row md:justify-start md:gap-3 md:px-3 md:py-3 md:text-xs ${screen === id ? "bg-[var(--youb-navy)] text-white shadow-[0_10px_24px_rgba(23,30,72,.16)]" : "text-[var(--youb-ink-soft)] hover:bg-[var(--youb-lilac)] hover:text-[var(--youb-violet-deep)]"}`}><Icon size={17} /><span className="truncate">{label}</span></button>)}</div></aside>;
}

function Hero({ role, title, subtitle, onOpenBee }: { role: Role; title: string; subtitle: string; onOpenBee: () => void }) {
  const eyebrow = role === "gestor" ? "Hoje · visão do líder" : role === "rh" ? "Intelligence Workspace" : role === "colaborador" ? "Minha jornada" : "Diretoria · visão do sistema";
  return <section className="youb-hero"><div className="relative max-w-3xl"><Label>{eyebrow}</Label><div className="mt-4 flex items-start gap-4"><div className="hidden h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-[var(--youb-lilac)] text-[var(--youb-violet)] sm:flex"><Sparkles size={21} /></div><div><h1 className="text-3xl font-semibold leading-tight tracking-[-0.04em] text-[var(--youb-navy)] sm:text-5xl">{title}</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-[var(--youb-ink-soft)] sm:text-base">{subtitle}</p><div className="mt-5 flex flex-wrap items-center gap-2"><DemoBadge /><button type="button" onClick={onOpenBee} className="inline-flex items-center gap-2 rounded-full border border-[var(--youb-line)] bg-white px-3 py-2 text-xs font-semibold text-[var(--youb-violet-deep)] hover:border-[var(--youb-violet)]"><Sparkles size={13} /> Perguntar à Bee</button></div></div></div></div></section>;
}

function AttentionRow({ title, detail, tag, onOpen }: { title: string; detail: string; tag: string; onOpen?: () => void }) { return <button type="button" onClick={onOpen} className="group flex w-full items-start gap-3 border-b border-[var(--youb-line)] py-4 text-left last:border-0"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-[var(--youb-violet)]" /><span className="min-w-0 flex-1"><strong className="block text-sm text-[var(--youb-ink)]">{title}</strong><span className="mt-1 block text-xs leading-5 text-[var(--youb-ink-soft)]">{detail}</span><span className="mt-2 inline-flex rounded-full bg-[var(--youb-lilac)] px-2 py-1 text-[10px] font-semibold text-[var(--youb-violet-deep)]">{tag}</span></span><ChevronRight size={16} className="mt-1 shrink-0 text-[var(--youb-ink-muted)] transition group-hover:translate-x-1 group-hover:text-[var(--youb-violet)]" /></button>; }
function Section({ title, eyebrow, children, className = "" }: { title: string; eyebrow?: string; children: ReactNode; className?: string }) { return <section className={`youb-panel ${className}`}>{eyebrow && <Label>{eyebrow}</Label>}<h2 className="mt-1 text-xl font-semibold tracking-[-0.025em] text-[var(--youb-navy)]">{title}</h2><div className="mt-5">{children}</div></section>; }

function LeaderHome({ openBee, onScreen }: { openBee: () => void; onScreen: (screen: Screen) => void }) {
  return <><Hero role="gestor" title="Bom dia, Carlos." subtitle="Organizei o que mudou desde ontem. Você recebe apenas o que precisa de atenção, confirmação ou decisão humana." onOpenBee={openBee} /><div className="mt-6 grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><Section title="O que precisa da sua atenção" eyebrow="Hoje · máximo de três focos" className="bg-[var(--youb-navy)] text-white"><p className="max-w-xl text-sm leading-6 text-white/70">A complexidade fica na youB. A sua atenção encontra o próximo movimento mínimo.</p><div className="mt-4 divide-y divide-white/10">{[["Preparar uma conversa", "Há um contexto autorizado aguardando sua leitura.", "FAZER"], ["Revisar uma confirmação", "Uma hipótese ainda precisa de validação humana.", "DECIDIR"], ["Redistribuir atenção", "Uma atividade pode ser delegada sem perder contexto.", "DELEGAR"]].map(([title, detail, tag]) => <AttentionRow key={title} title={title} detail={detail} tag={tag} onOpen={() => onScreen("team")} />)}</div></Section><Section title="Bee ao seu lado" eyebrow="Chief of Staff contextual"><div className="rounded-2xl bg-[var(--youb-lilac)] p-4"><div className="flex items-center gap-2 text-sm font-semibold text-[var(--youb-violet-deep)]"><BrainCircuit size={17} /> Sem decisões automáticas</div><p className="mt-3 text-sm leading-6 text-[var(--youb-ink-soft)]">Escolha um horizonte para aprofundar. A Bee organiza fontes autorizadas e explicita o que ainda não sabemos.</p><button type="button" onClick={openBee} className="mt-4 inline-flex items-center gap-2 rounded-full bg-[var(--youb-navy)] px-4 py-2.5 text-xs font-semibold text-white">Abrir contexto <ArrowRight size={14} /></button></div></Section></div><div className="mt-5 grid gap-5 md:grid-cols-3"><Section title="Hoje" eyebrow="Ver" className="min-h-[180px]"><p className="text-sm leading-6 text-[var(--youb-ink-soft)]">Uma atenção principal, confirmações pendentes e conversas que só você pode conduzir.</p></Section><Section title="Semana" eyebrow="Preparar" className="min-h-[180px]"><p className="text-sm leading-6 text-[var(--youb-ink-soft)]">Compromissos de liderança aparecem com contexto, dependência e próximo passo.</p></Section><Section title="Evolução" eyebrow="Acompanhar" className="min-h-[180px]"><p className="text-sm leading-6 text-[var(--youb-ink-soft)]">Padrões de desenvolvimento permanecem distintos de hipótese, diagnóstico ou causalidade.</p></Section></div></>;
}

function RhHome({ onScreen }: { onScreen: (screen: Screen) => void }) { const paths = [{ title: "Investigar", detail: "Abrir uma Leitura Organizacional e separar observação, evidência e hipótese.", icon: Search }, { title: "Interpretar", detail: "Compreender contexto sem transformar correlação em causalidade.", icon: BookOpen }, { title: "Intervir", detail: "Preparar uma recomendação para decisão humana.", icon: Target }, { title: "Acompanhar", detail: "Revisar resultado observado depois da intervenção.", icon: Activity }]; return <><Hero role="rh" title="Leituras Organizacionais." subtitle="Centro de Orquestração de Pessoas para investigar, interpretar, intervir e acompanhar — sem esconder limites, proveniência ou desconhecidos." onOpenBee={() => undefined} /><div className="mt-6 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><Section title="De onde começar" eyebrow="Intelligence Workspace"><div className="grid gap-2 sm:grid-cols-2">{paths.map(({ title, detail, icon: Icon }) => <button type="button" key={title} onClick={() => onScreen("rh")} className="rounded-2xl border border-[var(--youb-line)] p-4 text-left transition hover:-translate-y-0.5 hover:border-[var(--youb-violet)] hover:bg-[var(--youb-lilac)]"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[var(--youb-lilac)] text-[var(--youb-violet)]"><Icon size={17} /></span><h3 className="mt-4 text-sm font-semibold text-[var(--youb-ink)]">{title}</h3><p className="mt-2 text-xs leading-5 text-[var(--youb-ink-soft)]">{detail}</p><ArrowRight size={14} className="mt-4 text-[var(--youb-violet)]" /></button>)}</div></Section><Section title="Leitura responsável" eyebrow="Contrato de evidência"><div className="youb-callout"><div className="flex items-center gap-2 text-sm font-semibold text-[var(--youb-violet-deep)]"><ShieldCheck size={17} /> O que permanece separado</div><ul className="mt-3 space-y-2 text-xs leading-5 text-[var(--youb-ink-soft)]"><li>Observação não é hipótese.</li><li>Hipótese não é fato.</li><li>Recommendation não é Decision.</li><li>Decision não significa Action executada.</li></ul></div></Section></div><div className="mt-5 grid gap-5 md:grid-cols-2"><Section title="Contexto insuficiente" eyebrow="Estado seguro"><p className="text-sm leading-6 text-[var(--youb-ink-soft)]">Quando não houver fonte autorizada suficiente, a youB mostra o desconhecido e não fabrica prioridade, risco ou leitura.</p></Section><Section title="Próximo passo humano" eyebrow="Acompanhar"><p className="text-sm leading-6 text-[var(--youb-ink-soft)]">Toda recomendação pode ser explorada junto de evidências, limitações e autorização antes de qualquer decisão.</p></Section></div></>; }

function DirectorHome({ openBee, onScreen }: { openBee: () => void; onScreen: (screen: Screen) => void }) { return <><Hero role="diretoria" title="Organização agora." subtitle="Uma leitura executiva do que mudou, por que importa e onde uma decisão humana merece contexto." onOpenBee={openBee} /><div className="mt-6 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Section title="O que mudou" eyebrow="Visão do sistema"><AttentionRow title="Uma Leitura Organizacional aguarda aprofundamento" detail="A evidência está disponível; a interpretação ainda precisa de revisão." tag="EVIDÊNCIA" onOpen={() => onScreen("rh")} /><AttentionRow title="Uma decisão permanece pendente" detail="O próximo passo autorizado é revisar alternativas e limitações." tag="DECISÃO HUMANA" onOpen={() => onScreen("rh")} /><AttentionRow title="Um resultado ainda não foi validado" detail="A intervenção aconteceu, mas o impacto não deve ser presumido." tag="RESULTADO" onOpen={() => onScreen("rh")} /></Section><Section title="Pergunte à Bee" eyebrow="Contexto executivo"><div className="rounded-2xl bg-[var(--youb-lilac)] p-4"><p className="text-sm leading-6 text-[var(--youb-ink-soft)]">A Bee pode explicar fontes, limites e consequências possíveis sem substituir governança.</p><button type="button" onClick={openBee} className="mt-4 inline-flex items-center gap-2 rounded-full bg-[var(--youb-navy)] px-4 py-2.5 text-xs font-semibold text-white">Abrir Bee <Sparkles size={14} /></button></div></Section></div><div className="mt-5 grid gap-5 md:grid-cols-3"><Section title="Evidência" eyebrow="Sustenta"><p className="text-sm leading-6 text-[var(--youb-ink-soft)]">O que está observado e declarado aparece antes de qualquer interpretação.</p></Section><Section title="Atenção" eyebrow="Merece decisão"><p className="text-sm leading-6 text-[var(--youb-ink-soft)]">Poucos temas, priorizados por contexto autorizado — sem ranking inventado.</p></Section><Section title="Depois" eyebrow="Acompanhar"><p className="text-sm leading-6 text-[var(--youb-ink-soft)]">Resultados ficam abertos até serem medidos e validados.</p></Section></div></>; }

function EmployeeHome({ openBee }: { openBee: () => void }) { return <><Hero role="colaborador" title="Minha evolução." subtitle="Um espaço pessoal para compreender seu desenvolvimento, preparar conversas e escolher o próximo passo no seu ritmo." onOpenBee={openBee} /><div className="mt-6 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><Section title="Próximo passo" eyebrow="Contexto pessoal"><div className="flex items-start gap-3 rounded-2xl bg-[var(--youb-lilac)] p-4"><Check className="mt-0.5 text-[var(--youb-violet)]" size={18} /><div><p className="text-sm font-semibold text-[var(--youb-ink)]">Preparar uma conversa de desenvolvimento</p><p className="mt-1 text-xs leading-5 text-[var(--youb-ink-soft)]">O objetivo aparece com a fonte autorizada e pode ser revisto antes de você agir.</p></div></div><button type="button" onClick={openBee} className="mt-4 inline-flex items-center gap-2 rounded-full border border-[var(--youb-line)] px-4 py-2.5 text-xs font-semibold text-[var(--youb-violet-deep)] hover:bg-[var(--youb-lilac)]">Preparar com Bee <ArrowRight size={14} /></button></Section><Section title="Meu espaço" eyebrow="Privacidade por padrão"><div className="youb-callout"><div className="flex items-center gap-2 text-sm font-semibold text-[var(--youb-violet-deep)]"><ShieldCheck size={17} /> Somente seu contexto</div><p className="mt-3 text-xs leading-5 text-[var(--youb-ink-soft)]">Você vê apenas informações relacionadas ao seu desenvolvimento e às conversas autorizadas.</p></div></Section></div><div className="mt-5 grid gap-5 md:grid-cols-3"><Section title="PDI" eyebrow="Desenvolvimento"><p className="text-sm leading-6 text-[var(--youb-ink-soft)]">Objetivos, critérios de sucesso e próximos passos em uma única linha de contexto.</p></Section><Section title="Competências" eyebrow="Evolução"><p className="text-sm leading-6 text-[var(--youb-ink-soft)]">Evidências de desenvolvimento, sem transformar um recorte em identidade.</p></Section><Section title="Conversas" eyebrow="Acompanhar"><p className="text-sm leading-6 text-[var(--youb-ink-soft)]">Preparação para conversas mais claras, humanas e úteis.</p></Section></div></>; }

function OrganizationView() { const clusters = [{ label: "Pessoas", subtitle: "contexto e desenvolvimento" }, { label: "Times", subtitle: "colaboração e liderança" }, { label: "Temas", subtitle: "leituras e competências" }, { label: "Evidências", subtitle: "fontes e limites" }, { label: "Intervenções", subtitle: "decisões humanas" }]; return <section className="youb-hero"><div className="flex flex-wrap items-start justify-between gap-4"><div><Label>Organização Viva · exploração progressiva</Label><h1 className="mt-3 text-3xl font-semibold tracking-[-0.04em] text-[var(--youb-navy)] sm:text-4xl">Relações antes de rankings.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--youb-ink-soft)]">Explore pessoas, times, temas, evidências e intervenções sem transformar a organização em uma galáxia ou em um painel de KPIs.</p></div><button type="button" className="rounded-full border border-[var(--youb-line)] bg-white px-4 py-2 text-xs font-semibold text-[var(--youb-violet-deep)]"><Filter size={14} className="mr-1 inline" />Filtrar contexto</button></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{clusters.map((cluster, index) => <article key={cluster.label} className={`rounded-2xl border p-4 ${index === 0 ? "border-[var(--youb-violet)] bg-[var(--youb-lilac)]" : "border-[var(--youb-line)] bg-white"}`}><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-white text-[var(--youb-violet)]"><Network size={16} /></span><div><h3 className="text-sm font-semibold text-[var(--youb-ink)]">{cluster.label}</h3><p className="text-xs text-[var(--youb-ink-soft)]">{cluster.subtitle}</p></div></div><div className="mt-4 flex gap-2">{[1, 2, 3, 4].map((dot) => <span key={dot} className={`h-2.5 w-2.5 rounded-full ${index === 0 ? "bg-[var(--youb-violet)]" : "bg-[var(--youb-line-strong)]"}`} />)}</div></article>)}</div><div className="mt-5 flex items-center justify-between rounded-2xl border border-dashed border-[var(--youb-line-strong)] bg-white/70 p-4 text-xs text-[var(--youb-ink-soft)]"><span>Foco atual: relações com contexto suficiente</span><span className="font-semibold text-[var(--youb-violet-deep)]">Mapa · Lista</span></div></section>; }

function FinalUI({ role, screen, onScreen, openBee, navOpen }: { role: Role; screen: Screen; onScreen: (screen: Screen) => void; openBee: () => void; navOpen: boolean }) { const content = screen === "organization" ? <OrganizationView /> : role === "rh" ? <RhHome onScreen={onScreen} /> : role === "diretoria" ? <DirectorHome openBee={openBee} onScreen={onScreen} /> : role === "colaborador" ? <EmployeeHome openBee={openBee} /> : <LeaderHome openBee={openBee} onScreen={onScreen} />; return <div className="mx-auto max-w-[1500px] px-3 py-4 pb-24 sm:px-6 sm:py-6 md:flex md:gap-6 md:pb-8"><ShellNav role={role} screen={screen} onScreen={onScreen} open={navOpen} /><main className="min-w-0 flex-1">{content}</main></div>; }

export default function CommercialV1FinalUI() { const [role, setRole] = useState<Role>("diretoria"); const [screen, setScreen] = useState<Screen>("home"); const [beeOpen, setBeeOpen] = useState(false); const [navOpen, setNavOpen] = useState(false); const title = useMemo(() => `${roleNames[role]} · Commercial V1`, [role]); function changeRole(nextRole: Role) { setRole(nextRole); setScreen("home"); setNavOpen(false); } return <div className="min-h-screen bg-[var(--youb-surface)] text-[var(--youb-ink)]"><Header role={role} onRole={changeRole} onMenu={() => setNavOpen((open) => !open)} /><div className="sr-only" aria-live="polite">{title}</div><FinalUI role={role} screen={screen} onScreen={(next) => { setScreen(next); setNavOpen(false); }} openBee={() => setBeeOpen(true)} navOpen={navOpen} />{beeOpen && <BeePanel onClose={() => setBeeOpen(false)} />}</div>; }
