import { CalendarDays, CheckCircle2, ClipboardList, Goal, HeartPulse, Sparkles, Target, TrendingUp } from "lucide-react";
import type { EmployeeHomeData } from "../../features/intelligence-core/service";
import BeeShell, { type BeeContext } from "./BeeShell";

export type EmployeeHomeContext = { displayName: string; organizationName: string; beeContext: BeeContext; data?: EmployeeHomeData };
type Card = { label: string; detail: string; icon: typeof Target };
function cardsFrom(data?: EmployeeHomeData): Card[] {
  const pendingActions = data?.actions.filter((action) => action.status !== "completed" && action.status !== "cancelled").length ?? 0;
  const pdis = data?.pdis.filter((pdi) => pdi.status !== "cancelled").length ?? 0;
  const assessments = data?.assessments.length ?? 0;
  const latestCheckin = data?.checkins[0]?.checkin_date;
  return [
    { label: "Tarefas de hoje", detail: data ? pendingActions ? `${pendingActions} ação(ões) pendente(s) vinculada(s) ao seu perfil.` : "Nenhuma ação pendente vinculada ao seu perfil." : "Nenhuma fonte de tarefas está conectada.", icon: CheckCircle2 },
    { label: "Meu PDI", detail: data ? pdis ? `${pdis} objetivo(s) de PDI encontrado(s).` : "Nenhum objetivo de PDI encontrado." : "Nenhum objetivo disponível neste momento.", icon: Target },
    { label: "Minhas avaliações", detail: data ? assessments ? `${assessments} avaliação(ões) concluída(s) disponível(is).` : "Nenhuma avaliação concluída disponível." : "Nenhuma avaliação disponível neste momento.", icon: ClipboardList },
    { label: "Próximos compromissos", detail: "Nenhuma fonte de compromissos está conectada.", icon: CalendarDays },
    { label: "Meu desenvolvimento", detail: latestCheckin ? `Último check-in registrado em ${latestCheckin}.` : "Nenhum check-in registrado.", icon: TrendingUp },
  ];
}
function HomeCard({ card }: { card: Card }) { const Icon = card.icon; return <article className="rounded-3xl border border-border bg-card p-5 text-card-foreground shadow-sm"><div className="flex items-start justify-between"><p className="text-xs font-bold uppercase tracking-[0.12em] text-muted-foreground">{card.label}</p><div className="rounded-2xl bg-muted p-2.5 text-muted-foreground"><Icon size={19} /></div></div><p className="mt-5 text-sm leading-6 text-muted-foreground">{card.detail}</p></article>; }
function AssessmentHistory({ data }: { data: EmployeeHomeData }) {
  const competencyNames = new Map(data.competencies.map((item) => [item.id, item.name]));
  return <section className="rounded-3xl border border-border bg-card p-6 text-card-foreground shadow-sm"><div className="flex items-center gap-3"><div className="rounded-2xl bg-muted p-2.5 text-muted-foreground"><ClipboardList size={20} /></div><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-muted-foreground">Minhas avaliações</p><h2 className="mt-1 text-xl font-bold">Resultados concluídos</h2></div></div><div className="mt-5 space-y-4">{data.assessments.map((assessment) => { const scores = data.assessmentScores.filter((score) => score.assessment_id === assessment.id); return <article className="rounded-2xl border border-border p-4" key={assessment.id}><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-bold">Avaliação concluída</p><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">Concluída</span></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{scores.map((score) => <div className="rounded-xl bg-muted/60 p-3" key={score.id}><p className="text-sm font-semibold">{competencyNames.get(score.competency_id) ?? "Competência"}</p><p className="mt-1 text-xs text-muted-foreground">Resultado: <strong>{score.score ?? "—"}/5</strong> · Esperado: {score.expected_level_snapshot}/5</p>{score.evidence_note && <p className="mt-2 text-xs leading-5 text-muted-foreground">{score.evidence_note}</p>}</div>)}</div></article>; })}</div></section>;
}
export default function EmployeeHome({ context }: { context: EmployeeHomeContext }) { const cards = cardsFrom(context.data); const latestCheckin = context.data?.checkins[0]; return <main className="min-h-screen bg-background px-5 py-8 text-foreground sm:px-8"><div className="mx-auto max-w-6xl space-y-8"><header className="flex flex-col gap-5 rounded-[2rem] bg-primary p-7 text-primary-foreground shadow-lg sm:flex-row sm:items-end sm:justify-between sm:p-10"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary-foreground/70">Minha jornada · {context.organizationName}</p><h1 className="mt-3 text-3xl font-extrabold tracking-tight sm:text-4xl">Olá, {context.displayName}</h1><p className="mt-3 max-w-xl text-sm leading-7 text-primary-foreground/80">Um espaço para acompanhar seus próximos passos com clareza e no seu ritmo.</p></div><BeeShell context={context.beeContext} /></header><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{cards.map((card) => <HomeCard key={card.label} card={card} />)}</section>{context.data?.assessments.length ? <AssessmentHistory data={context.data} /> : null}<section className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><article className="rounded-3xl border border-border bg-card p-6 text-card-foreground shadow-sm"><div className="flex items-center gap-3"><div className="rounded-2xl bg-muted p-2.5 text-muted-foreground"><HeartPulse size={20} /></div><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-muted-foreground">Check-in de hoje</p><h2 className="mt-1 text-xl font-bold">Como você está?</h2></div></div><p className="mt-4 text-sm leading-6 text-muted-foreground">{latestCheckin ? `Seu último check-in foi registrado em ${latestCheckin.checkin_date}.` : "Nenhum check-in registrado. O check-in estará disponível quando esta fonte for conectada."}</p><div className="mt-5 flex flex-wrap gap-2">{["Estou bem", "Mais ou menos", "Preciso de apoio"].map((option) => <button key={option} className="rounded-full border border-border px-4 py-2 text-sm font-semibold text-muted-foreground transition hover:bg-muted">{option}</button>)}</div></article><article className="rounded-3xl border border-dashed border-border bg-card p-6 text-card-foreground"><div className="flex items-center gap-3"><div className="rounded-2xl bg-muted p-2.5 text-muted-foreground"><ClipboardList size={20} /></div><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-muted-foreground">Atalhos</p><h2 className="mt-1 text-xl font-bold">Espaços disponíveis</h2></div></div><div className="mt-5 space-y-3 text-sm text-muted-foreground"><p className="flex items-center gap-2"><Goal size={16} /> Definir um objetivo quando o PDI estiver conectado</p><p className="flex items-center gap-2"><Sparkles size={16} /> Pergunte à Bee sobre os próximos passos</p></div></article></section></div></main>; }
export function EmployeeHomePreview() { return <EmployeeHome context={{ displayName: "Usuária de preview", organizationName: "Organização de preview", beeContext: { userName: "Usuária de preview", organizationName: "Organização de preview", role: "Colaborador", capabilities: ["read:own_profile"], employeeLinked: false, screen: "preview" } }} />; }
