import { useEffect, useMemo, useState } from "react";
import type { FormEvent } from "react";
import type { SupabaseSession } from "../../lib/supabase";
import { readAggregate, readCompetencies, readCriteria, readCycles, readEmployees, readEvolution, readParticipants, readRounds, readScores, readSubjectResult, rpc, type Feedback360Aggregate, type Feedback360Criterion, type Feedback360Cycle, type Feedback360Employee, type Feedback360Evolution, type Feedback360Participant, type Feedback360Role, type Feedback360Round, type Feedback360Score, type Feedback360SubjectResult } from "../../features/feedback-360-evolution/service";

type Props = { session: SupabaseSession; organization: { id: string }; role: Feedback360Role; employeeId: string | null };
const input = "mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-100";
const primary = "rounded-xl bg-[#1e3a6e] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50";
const secondary = "rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-700 disabled:opacity-50";
const statusLabel: Record<string, string> = { draft: "Rascunho", active: "Ativa", closed: "Encerrada", pending: "Pendente", in_progress: "Em andamento", submitted: "Submetida" };
const relationshipLabel: Record<string, string> = { self: "Autoavaliação", manager: "Gestor", peer: "Par", direct_report: "Liderado direto" };

export default function Feedback360Evolution({ session, organization, role, employeeId }: Props) {
  const isAdmin = role === "admin_youb" || role === "rh";
  const [rounds, setRounds] = useState<Feedback360Round[]>([]);
  const [cycles, setCycles] = useState<Feedback360Cycle[]>([]);
  const [employees, setEmployees] = useState<Feedback360Employee[]>([]);
  const [competencies, setCompetencies] = useState<Array<{ id: string; name: string }>>([]);
  const [participants, setParticipants] = useState<Feedback360Participant[]>([]);
  const [selectedRound, setSelectedRound] = useState("");
  const [selectedParticipant, setSelectedParticipant] = useState("");
  const [criteria, setCriteria] = useState<Feedback360Criterion[]>([]);
  const [scores, setScores] = useState<Feedback360Score[]>([]);
  const [result, setResult] = useState<Feedback360SubjectResult[]>([]);
  const [aggregate, setAggregate] = useState<Feedback360Aggregate[]>([]);
  const [evolution, setEvolution] = useState<Feedback360Evolution[]>([]);
  const [roundName, setRoundName] = useState("");
  const [roundCycle, setRoundCycle] = useState("");
  const [subject, setSubject] = useState("");
  const [evaluator, setEvaluator] = useState("");
  const [relationship, setRelationship] = useState<"self" | "manager" | "peer" | "direct_report">("self");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [notice, setNotice] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const employeesById = useMemo(() => new Map(employees.map((item) => [item.id, item.full_name])), [employees]);
  const competenciesById = useMemo(() => new Map(competencies.map((item) => [item.id, item.name])), [competencies]);
  const selected = participants.find((item) => item.id === selectedParticipant) ?? null;
  const selectedRoundData = rounds.find((item) => item.id === selectedRound) ?? null;
  const visibleParticipants = participants.filter((item) => !selectedRound || item.round_id === selectedRound);

  async function refresh() {
    setLoading(true); setError(null);
    try {
      const [nextRounds, nextCycles, nextEmployees, nextCompetencies, nextParticipants] = await Promise.all([readRounds(session, organization.id), readCycles(session, organization.id), readEmployees(session, organization.id), readCompetencies(session, organization.id), readParticipants(session, organization.id)]);
      setRounds(nextRounds); setCycles(nextCycles); setEmployees(nextEmployees); setCompetencies(nextCompetencies); setParticipants(nextParticipants);
      if (!selectedRound && nextRounds[0]) setSelectedRound(nextRounds[0].id);
    } catch (value) { setError(value instanceof Error ? value.message : "Não foi possível carregar as rodadas 360."); } finally { setLoading(false); }
  }
  useEffect(() => { void refresh(); }, [organization.id, session.access_token, role, employeeId]);
  useEffect(() => {
    if (!selected) { setCriteria([]); setScores([]); return; }
    void Promise.all([readCriteria(session, organization.id, selected.round_id, selected.subject_employee_id), readScores(session, organization.id, selected.id)]).then(([nextCriteria, nextScores]) => { setCriteria(nextCriteria); setScores(nextScores); }).catch((value) => setError(value instanceof Error ? value.message : "Não foi possível carregar a participação."));
  }, [selectedParticipant, organization.id, session.access_token]);

  function fail(value: unknown) { setError(value instanceof Error ? value.message : "Não foi possível concluir a operação."); }
  async function run(action: () => Promise<unknown>, success: string) { setSaving(true); setError(null); try { await action(); setNotice(success); await refresh(); } catch (value) { fail(value); } finally { setSaving(false); } }
  async function createRound(event: FormEvent) { event.preventDefault(); await run(async () => { const id = await rpc<string>(session, "fb360_create_round", { p_organization_id: organization.id, p_cycle_id: roundCycle, p_name: roundName, p_description: "confidential" }); setSelectedRound(id); setRoundName(""); }, "Rodada criada como rascunho."); }
  async function addParticipant(event: FormEvent) { event.preventDefault(); await run(() => rpc(session, "fb360_add_participant", { p_round_id: selectedRound, p_subject_employee_id: subject, p_evaluator_employee_id: evaluator, p_relationship_type: relationship }), "Participante explícito adicionado."); }
  async function transitionRound(action: "fb360_activate_round" | "fb360_close_round") { await run(() => rpc(session, action, { p_round_id: selectedRound }), action === "fb360_activate_round" ? "Rodada ativada com snapshot dos critérios." : "Rodada encerrada."); }
  async function saveScore(score: Feedback360Score, value: string, comment: string) { await run(async () => { await rpc(session, "fb360_save_score", { p_participant_id: score.participant_id, p_subject_competency_id: score.subject_competency_id, p_score: Number(value), p_comment: comment }); setScores(await readScores(session, organization.id, score.participant_id)); }, "Resposta salva."); }
  async function submit() { if (selected) await run(() => rpc(session, "fb360_submit_participation", { p_participant_id: selected.id }), "Participação submetida e bloqueada para edição."); }
  async function loadResult() { if (!selectedRound || !employeeId) return; try { setResult(await readSubjectResult(session, organization.id, selectedRound, employeeId)); } catch (value) { fail(value); } }
  async function loadAggregate() { if (!selectedRound) return; try { setAggregate(await readAggregate(session, organization.id, selectedRound)); } catch (value) { fail(value); } }
  async function loadEvolution() { if (!employeeId) return; try { setEvolution(await readEvolution(session, organization.id, employeeId)); } catch (value) { fail(value); } }

  if (loading && !rounds.length) return <section className="rounded-2xl border border-slate-200 bg-white p-8 text-sm text-slate-500">Carregando rodadas 360 e evolução...</section>;
  return (
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
      <header className="flex flex-col justify-between gap-3 border-b border-slate-100 pb-5 sm:flex-row"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-blue-600">Feedback 360 + evolução V1</p><h2 className="mt-1 text-2xl font-extrabold text-slate-900">Rodadas confidenciais e histórico por origem</h2><p className="mt-1 text-sm text-slate-500">Self, Gestor, Pares e Liderados permanecem separados. A Diretoria recebe somente agregado seguro.</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600">Confidencial V1</span></header>
      {notice && <p className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{notice}</p>}
      {error && <p className="mt-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{error}</p>}
      <div className="mt-6 grid gap-6 xl:grid-cols-[0.9fr_1.1fr]">
        <div className="space-y-6">
          {isAdmin && <RoundForm cycles={cycles} name={roundName} cycle={roundCycle} saving={saving} onName={setRoundName} onCycle={setRoundCycle} onSubmit={createRound} />}
          {isAdmin && selectedRound && selectedRoundData?.status === "draft" && <ParticipantForm employees={employees} subject={subject} evaluator={evaluator} relationship={relationship} saving={saving} onSubject={setSubject} onEvaluator={setEvaluator} onRelationship={setRelationship} onSubmit={addParticipant} />}
          {selectedRoundData && <div className="rounded-2xl border border-slate-200 p-5"><h3 className="font-bold">Estado da rodada</h3><p className="mt-2 text-sm text-slate-500">{selectedRoundData.name} · {statusLabel[selectedRoundData.status]}</p>{isAdmin && <div className="mt-4 flex flex-wrap gap-2">{selectedRoundData.status === "draft" && <button className={primary} disabled={saving} onClick={() => void transitionRound("fb360_activate_round")} type="button">Ativar e congelar critérios</button>}{selectedRoundData.status === "active" && <button className={secondary} disabled={saving} onClick={() => void transitionRound("fb360_close_round")} type="button">Encerrar rodada</button>}</div>}</div>}
        </div>
        <div className="space-y-6">
          <div className="rounded-2xl border border-slate-200 p-5"><h3 className="font-bold">Rodadas e participações</h3><select className={input} value={selectedRound} onChange={(event) => { setSelectedRound(event.target.value); setSelectedParticipant(""); }}><option value="">Selecione uma rodada</option>{rounds.map((round) => <option key={round.id} value={round.id}>{round.name} · {statusLabel[round.status]}</option>)}</select><div className="mt-4 space-y-2">{visibleParticipants.map((item) => <button className={`flex w-full justify-between rounded-xl border p-3 text-left ${selectedParticipant === item.id ? "border-blue-500 bg-blue-50" : "border-slate-200"}`} key={item.id} onClick={() => setSelectedParticipant(item.id)} type="button"><span><strong>{employeesById.get(item.subject_employee_id) ?? "Avaliado"}</strong><small className="mt-1 block text-xs text-slate-500">{relationshipLabel[item.relationship_type]} · {statusLabel[item.status]}</small></span><span className="text-xs text-slate-500">{isAdmin ? employeesById.get(item.evaluator_employee_id) ?? "Avaliador" : "Participação"}</span></button>)}{!visibleParticipants.length && <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Nenhuma participação autorizada nesta rodada.</p>}</div></div>
          {selected && <ParticipantEditor participant={selected} scores={scores} criteria={criteria} competencyNames={competenciesById} canEdit={selected.status !== "submitted" && selectedRoundData?.status === "active"} saving={saving} onSave={saveScore} onSubmit={submit} />}
          {(role === "colaborador" || role === "gestor") && <div className="rounded-2xl border border-slate-200 p-5"><h3 className="font-bold">Resultado próprio/autorizado</h3><button className={`${secondary} mt-3`} onClick={() => void loadResult()} type="button">Carregar resultado seguro</button><SafeResult result={result} /></div>}
          {role === "diretoria" && <AggregatePanel aggregate={aggregate} onLoad={loadAggregate} />}
          <EvolutionPanel evolution={evolution} onLoad={loadEvolution} />
        </div>
      </div>
    </section>
  );
}

function RoundForm({ cycles, name, cycle, saving, onName, onCycle, onSubmit }: { cycles: Feedback360Cycle[]; name: string; cycle: string; saving: boolean; onName: (value: string) => void; onCycle: (value: string) => void; onSubmit: (event: FormEvent) => void }) { return <form className="rounded-2xl border border-blue-100 bg-blue-50/60 p-5" onSubmit={onSubmit}><h3 className="font-bold">Nova rodada 360</h3><label className="mt-4 block text-xs font-bold text-slate-600">Nome<input className={input} value={name} onChange={(event) => onName(event.target.value)} required /></label><label className="mt-3 block text-xs font-bold text-slate-600">Ciclo<select className={input} value={cycle} onChange={(event) => onCycle(event.target.value)} required><option value="">Selecione</option>{cycles.filter((item) => item.status !== "closed").map((item) => <option key={item.id} value={item.id}>{item.name} · {item.status === "active" ? "ativo" : "rascunho"}</option>)}</select></label><p className="mt-2 text-xs text-slate-500">A rodada só poderá ser ativada quando o ciclo estiver ativo.</p><button className={`${primary} mt-4`} disabled={saving} type="submit">Criar rodada</button></form>; }
function ParticipantForm({ employees, subject, evaluator, relationship, saving, onSubject, onEvaluator, onRelationship, onSubmit }: { employees: Feedback360Employee[]; subject: string; evaluator: string; relationship: "self" | "manager" | "peer" | "direct_report"; saving: boolean; onSubject: (value: string) => void; onEvaluator: (value: string) => void; onRelationship: (value: "self" | "manager" | "peer" | "direct_report") => void; onSubmit: (event: FormEvent) => void }) { return <form className="rounded-2xl border border-slate-200 p-5" onSubmit={onSubmit}><h3 className="font-bold">Participante explícito</h3><Select label="Avaliado" value={subject} options={employees} onChange={onSubject} /><Select label="Avaliador" value={evaluator} options={employees} onChange={onEvaluator} /><label className="mt-3 block text-xs font-bold text-slate-600">Origem<select className={input} value={relationship} onChange={(event) => onRelationship(event.target.value as typeof relationship)}><option value="self">Autoavaliação</option><option value="manager">Gestor</option><option value="peer">Par</option><option value="direct_report">Liderado direto</option></select></label><button className={`${primary} mt-4`} disabled={saving} type="submit">Adicionar</button></form>; }
function Select({ label, value, options, onChange }: { label: string; value: string; options: Feedback360Employee[]; onChange: (value: string) => void }) { return <label className="mt-3 block text-xs font-bold text-slate-600">{label}<select className={input} value={value} onChange={(event) => onChange(event.target.value)} required><option value="">Selecione</option>{options.map((item) => <option key={item.id} value={item.id}>{item.full_name}</option>)}</select></label>; }
function ParticipantEditor({ participant, scores, criteria, competencyNames, canEdit, saving, onSave, onSubmit }: { participant: Feedback360Participant; scores: Feedback360Score[]; criteria: Feedback360Criterion[]; competencyNames: Map<string, string>; canEdit: boolean; saving: boolean; onSave: (score: Feedback360Score, value: string, comment: string) => Promise<void>; onSubmit: () => Promise<void> }) { const complete = scores.length > 0 && scores.every((item) => item.score != null); return <div className="rounded-2xl border border-blue-100 bg-blue-50/40 p-5"><div className="flex items-center justify-between gap-3"><div><h3 className="font-bold">Responder · {relationshipLabel[participant.relationship_type]}</h3><p className="mt-1 text-sm text-slate-500">{scores.filter((item) => item.score != null).length}/{scores.length} competências respondidas</p></div><span className="rounded-full bg-white px-3 py-1 text-xs font-bold">{statusLabel[participant.status]}</span></div><div className="mt-4 space-y-3">{scores.map((score) => <ScoreRow key={score.id} score={score} criterion={criteria.find((item) => item.id === score.subject_competency_id)} name={competencyNames.get(criteria.find((item) => item.id === score.subject_competency_id)?.competency_id ?? "") ?? "Competência"} canEdit={canEdit} saving={saving} onSave={onSave} />)}{!scores.length && <p className="rounded-xl bg-amber-50 p-4 text-sm text-amber-800">A rodada ainda não possui critérios congelados.</p>}</div>{canEdit && <button className={`${primary} mt-4`} disabled={saving || !complete} onClick={() => void onSubmit()} type="button">Submeter participação</button>}</div>; }
function ScoreRow({ score, criterion, name, canEdit, saving, onSave }: { score: Feedback360Score; criterion?: Feedback360Criterion; name: string; canEdit: boolean; saving: boolean; onSave: (score: Feedback360Score, value: string, comment: string) => Promise<void> }) { const [value, setValue] = useState(score.score?.toString() ?? ""); const [comment, setComment] = useState(score.comment ?? ""); return <div className="rounded-xl border border-white bg-white p-4"><div className="flex items-center justify-between gap-3"><div><p className="font-bold">{name}</p><p className="mt-1 text-xs text-slate-500">Expected level congelado: {criterion?.expected_level_snapshot ?? "—"}/5</p></div><select className="rounded-lg border border-slate-200 px-3 py-2 text-sm" disabled={!canEdit || saving} value={value} onChange={(event) => setValue(event.target.value)}><option value="">Score</option>{[1,2,3,4,5].map((item) => <option key={item} value={item}>{item}</option>)}</select></div><textarea className={`${input} mt-3`} disabled={!canEdit || saving} rows={2} value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Comentário opcional" />{canEdit && <button className={`${secondary} mt-3`} disabled={saving || !value} onClick={() => void onSave(score,value,comment)} type="button">Salvar resposta</button>}</div>; }
function SafeResult({ result }: { result: Feedback360SubjectResult[] }) { return <div className="mt-4 space-y-2">{result.map((item) => <div className="rounded-xl bg-slate-50 p-3 text-sm" key={`${item.round_id}-${item.competency_id}-${item.relationship_type}`}><strong>{item.competency_name}</strong> · {relationshipLabel[item.relationship_type]} · {item.average_score}/5 {item.relationship_type === "peer" || item.relationship_type === "direct_report" ? `(${item.response_count} respostas protegidas)` : item.feedback_comment ? <p className="mt-1 text-xs text-slate-600">{item.feedback_comment}</p> : null}</div>)}{!result.length && <p className="text-sm text-slate-500">Nenhum resultado fechado ou população suficiente.</p>}</div>; }
function AggregatePanel({ aggregate, onLoad }: { aggregate: Feedback360Aggregate[]; onLoad: () => Promise<void> }) { return <div className="rounded-2xl border border-slate-200 p-5"><h3 className="font-bold">Agregado seguro da Diretoria</h3><button className={`${secondary} mt-3`} onClick={() => void onLoad()} type="button">Carregar agregado</button><div className="mt-4 space-y-2">{aggregate.map((item) => <div className="rounded-xl bg-slate-50 p-3 text-sm" key={`${item.competency_id}-${item.source_role}-${item.position_id}`}><strong>{item.competency_name}</strong> · {relationshipLabel[item.source_role] ?? item.source_role} · {item.average_score}/5 <span className="text-xs text-slate-500">({item.subject_count} avaliados)</span></div>)}{!aggregate.length && <p className="text-sm text-slate-500">Grupos abaixo do threshold permanecem ocultos.</p>}</div></div>; }
function EvolutionPanel({ evolution, onLoad }: { evolution: Feedback360Evolution[]; onLoad: () => Promise<void> }) { return <div className="rounded-2xl border border-slate-200 p-5"><h3 className="font-bold">Evolução entre ciclos</h3><button className={`${secondary} mt-3`} onClick={() => void onLoad()} type="button">Carregar evolução separada por origem</button><div className="mt-4 space-y-2">{evolution.map((item, index) => <div className="rounded-xl bg-slate-50 p-3 text-sm" key={`${item.source_type}-${item.competency_id}-${item.completed_at}-${index}`}><strong>{item.competency_name}</strong> · {relationshipLabel[item.source_type] ?? item.source_type} · {item.score}/5 {item.delta == null ? "· sem predecessor comparável" : `· delta ${item.delta > 0 ? "+" : ""}${item.delta}`}<small className="mt-1 block text-xs text-slate-500">Esperado no snapshot: {item.expected_level_snapshot}/5 · distância: {item.distance_to_expected}</small></div>)}{!evolution.length && <p className="text-sm text-slate-500">Sem histórico comparável.</p>}</div></div>; }
