import { useMemo, useState, type FormEvent, type ReactNode } from "react";
import { ArrowRight, BarChart3, CalendarDays, ChevronDown, ChevronRight, Clock3, MoreHorizontal, Search, Sparkles, Target, UsersRound } from "lucide-react";
import type { BeeContext } from "./BeeShell";
import { ambientBeeResponse, ambientBriefPriorities, createAmbientDemoReadModel } from "../../features/ambient-intelligence/ux-integration";
import type { AmbientBeeReadModel } from "../../features/ambient-intelligence/runtime";

type LeaderEmployee = { id: string; full_name: string };
type LeaderFeedback = { id: string; target_employee_id: string; created_at: string; content: string };
type LeaderPdi = { id: string; objective: string; status: string; due_date?: string | null; employee_id: string };
type LeaderCheckin = { id: string; employee_id: string; checkin_date: string; note?: string | null };
type LeaderAssessment = { id: string; subject_employee_id: string; created_at: string };
export type ManagerHomeData = { employees: LeaderEmployee[]; feedbacks: LeaderFeedback[]; pdis: LeaderPdi[]; checkins: LeaderCheckin[]; assessments: LeaderAssessment[] };
export type ManagerHomeProps = { displayName: string; organizationName: string; beeContext: BeeContext; data: ManagerHomeData; ambient?: AmbientBeeReadModel; onView?: (view: "employee-history" | "checkins" | "feedbacks" | "pdis" | "feedback-360") => void; onSubmitBee?: (message: string) => void };
export type LeaderPriority = { title: string; duration: string; reason: string; source: string; kind: "fazer" | "delegar" | "decidir"; epistemic?: string };

export const leaderHorizons = ["Hoje", "Semana", "Evolução"] as const;
export const leaderBuckets = ["Fazer", "Delegar", "Parar"] as const;

export function leaderPriorities(data: ManagerHomeData): LeaderPriority[] {
  const nameFor = (id: string) => data.employees.find((item) => item.id === id)?.full_name ?? "uma pessoa do time";
  const priorities: LeaderPriority[] = [];
  const feedback = data.feedbacks[0];
  if (feedback) priorities.push({ title: `Preparar feedback para ${nameFor(feedback.target_employee_id)}`, duration: "15 min", reason: "Há uma conversa de desenvolvimento registrada que pode virar próximo passo.", source: "Feedback autorizado", kind: "fazer" });
  const pdi = data.pdis.find((item) => !["completed", "cancelled"].includes(item.status));
  if (pdi) priorities.push({ title: `Revisar desenvolvimento de ${nameFor(pdi.employee_id)}`, duration: "20 min", reason: "Um objetivo de desenvolvimento pede acompanhamento do líder.", source: "PDI autorizado", kind: "decidir" });
  const checkin = data.checkins[0];
  if (checkin) priorities.push({ title: `Ler o sinal recente de ${nameFor(checkin.employee_id)}`, duration: "10 min", reason: "Um check-in recente pode orientar a próxima conversa, sem diagnóstico.", source: "Check-in autorizado", kind: "fazer" });
  const assessment = data.assessments[0];
  if (assessment && priorities.length < 3) priorities.push({ title: `Reservar conversa de evolução com ${nameFor(assessment.subject_employee_id)}`, duration: "25 min", reason: "Uma avaliação disponível pode ser transformada em conversa humana.", source: "Avaliação autorizada", kind: "decidir" });
  return priorities.slice(0, 3);
}

function BeeMark({ small = false }: { small?: boolean }) {
  const id = small ? "beeSmall" : "beeLarge";
  return <svg className={small ? "yb-bee-mark yb-bee-mark--small" : "yb-bee-mark"} viewBox="0 0 64 64" aria-label="Bee"><defs><linearGradient id={id} x1="8" y1="4" x2="56" y2="58" gradientUnits="userSpaceOnUse"><stop stopColor="#9f7cff"/><stop offset="1" stopColor="#3d16bc"/></linearGradient></defs><g fill={`url(#${id})`}><ellipse cx="22" cy="18" rx="10" ry="6" transform="rotate(35 22 18)"/><ellipse cx="42" cy="18" rx="10" ry="6" transform="rotate(-35 42 18)"/><ellipse cx="19" cy="37" rx="11" ry="7" transform="rotate(-27 19 37)"/><ellipse cx="45" cy="37" rx="11" ry="7" transform="rotate(27 45 37)"/><path d="M26 22c0-4 3-7 6-7s6 3 6 7v21c0 5-3 10-6 14-3-4-6-9-6-14V22Z"/></g><circle cx="32" cy="12" r="4" fill="#d7c9ff"/></svg>;
}

function LuminousWave() {
  return <svg className="yb-luminous-wave" viewBox="0 0 940 260" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="waveA" x1="0" y1="0" x2="1" y2="1"><stop stopColor="#fff" stopOpacity=".08"/><stop offset=".34" stopColor="#bca8ff" stopOpacity=".52"/><stop offset=".7" stopColor="#e2dcff" stopOpacity=".74"/><stop offset="1" stopColor="#9d79ff" stopOpacity=".12"/></linearGradient><linearGradient id="waveB" x1="0" y1="1" x2="1" y2="0"><stop stopColor="#7a55e9" stopOpacity=".05"/><stop offset=".5" stopColor="#fff" stopOpacity=".78"/><stop offset="1" stopColor="#8d6bf1" stopOpacity=".2"/></linearGradient><filter id="waveGlow"><feGaussianBlur stdDeviation="7"/></filter></defs><path d="M-30 238C118 194 182 244 310 163 423 92 480 16 616 54c93 26 133 112 354 10v204H-30Z" fill="url(#waveA)"/><path d="M-30 224C152 198 226 233 354 138 476 48 556 29 666 91c102 58 156 68 304-3" fill="none" stroke="url(#waveB)" strokeWidth="30" filter="url(#waveGlow)"/><path d="M-30 238C115 188 221 244 342 151 464 58 532 33 646 77c109 42 166 86 324-10" fill="none" stroke="#fff" strokeOpacity=".72" strokeWidth="2"/><path d="M185 219C302 180 319 98 454 82c139-17 180 95 354 67" fill="none" stroke="#b99cff" strokeOpacity=".38"/><g fill="#fff"><circle cx="515" cy="53" r="3"/><circle cx="565" cy="83" r="2"/><circle cx="704" cy="121" r="2.5"/><circle cx="786" cy="104" r="1.8"/></g></svg>;
}

function PersonAvatar({ name, tone = "violet", size = "md" }: { name: string; tone?: "violet" | "pink" | "mint" | "amber"; size?: "sm" | "md" | "lg" }) {
  const initials = name.split(" ").map((part) => part[0]).join("").slice(0, 2);
  return <span className={`yb-person yb-person--${tone} yb-person--${size}`} aria-label={name}><svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="32" cy="32" r="31" fill="currentColor" opacity=".11"/><circle cx="32" cy="25" r="11" fill="currentColor" opacity=".72"/><path d="M12 59c2-15 10-22 20-22s18 7 20 22" fill="currentColor" opacity=".88"/></svg><b>{initials}</b></span>;
}

function Header({ firstName }: { firstName: string }) {
  return <header className="yb-topbar"><div className="yb-brand"><strong>youB</strong><span/><small>PESSOAS<br/>POTENCIAL<br/>PROGRESSO</small></div><label className="yb-global-search"><Search size={20}/><input aria-label="Busca global" placeholder="O que você quer entender sobre o seu time hoje?"/><ArrowRight size={22}/></label><div className="yb-user"><BeeMark small/><span><strong>Bom dia, {firstName}</strong><small>Líder do time de Produto</small></span><PersonAvatar name={firstName} size="sm"/><ChevronDown size={16}/></div></header>;
}

function MetricCard({ icon, eyebrow, value, delta, copy, tone }: { icon: ReactNode; eyebrow: string; value: string; delta: string; copy: string; tone: string }) {
  return <article className={`yb-metric yb-tone-${tone}`}><span className="yb-metric__icon">{icon}</span><div><h2>{eyebrow}</h2><strong>{value}</strong><span className="yb-metric__delta">{delta}</span><p>{copy}</p></div><ChevronRight size={20}/></article>;
}

function ListRow({ count, title, detail, tone = "violet", onClick }: { count?: string; title: string; detail: string; tone?: string; onClick?: () => void }) {
  return <button type="button" className="yb-list-row" onClick={onClick}><span className={`yb-list-count yb-list-count--${tone}`}>{count ?? <ChevronRight size={16}/>}</span><span><strong>{title}</strong><small>{detail}</small></span><ChevronRight size={17}/></button>;
}

function DesktopManagerHome({ firstName, organizationName, data, onView, onSubmitBee }: Omit<ManagerHomeProps, "displayName" | "ambient" | "beeContext"> & { firstName: string }) {
  const isDemo = organizationName === "Organização de preview";
  const activePdis = data.pdis.filter((item) => !["completed", "cancelled"].includes(item.status)).length;
  const competencyProgress = data.employees.length ? Math.round((activePdis / data.employees.length) * 100) : 0;
  const recentSignals = data.feedbacks.length + data.checkins.length;
  const people = data.employees.length ? data.employees.slice(0, 5) : [{ id: "empty", full_name: "Time" }];
  const [beeQuestion, setBeeQuestion] = useState("");
  function askBee(event: FormEvent) { event.preventDefault(); const question = beeQuestion.trim(); if (!question) return; onSubmitBee?.(question); setBeeQuestion(""); }
  return <div className="yb-desktop"><Header firstName={firstName}/><main className="yb-manager-canvas"><section className="yb-hero"><LuminousWave/><div className="yb-hero__copy"><p className="yb-eyebrow">VISÃO DO GESTOR</p><div className="yb-title-lockup"><BeeMark/><span/><div><h1>Bom dia, {firstName}</h1><h2>Seu time, nosso maior potencial.</h2></div></div><p>Aqui está um panorama do seu time, com foco em pessoas, desenvolvimento e próximas ações.</p><button type="button" className="yb-scope-pill"><UsersRound size={17}/> Você está vendo apenas o seu time: <b>Produto ({data.employees.length || 8} pessoas)</b><ArrowRight size={17}/></button></div><aside className="yb-hero__quote"><span>LIDERANÇA QUE<br/>DESENVOLVE PESSOAS</span><blockquote>“Pessoas crescem<br/>melhor quando têm<br/>boas conversas.”</blockquote><i/><small>A BEE SEMPRE<br/>AO SEU LADO</small></aside></section>
    <section className="yb-metrics"><MetricCard icon={<UsersRound/>} eyebrow={isDemo ? "Engajamento do time" : "Sinais recentes"} value={isDemo ? "78%" : String(recentSignals)} delta={isDemo ? "↓ -6 p.p." : "fontes autorizadas"} copy={isDemo ? "Leve queda no engajamento. Vale investigar as causas e reforçar momentos de conexão." : "Feedbacks e check-ins disponíveis para leitura do líder."} tone="pink"/><MetricCard icon={<Sparkles/>} eyebrow="Risco de sobrecarga" value={isDemo ? "2 pessoas" : "—"} delta={isDemo ? "↑ +1" : "sem evidência"} copy={isDemo ? "Sinais de alta demanda e risco de estresse. Considere redistribuir atividades." : "A youB não infere condição de saúde sem dados e consentimento adequados."} tone="amber"/><MetricCard icon={<BarChart3/>} eyebrow="Evolução de competências" value={isDemo ? "72%" : `${competencyProgress}%`} delta={isDemo ? "↑ +12 p.p." : `${activePdis} PDI(s) ativo(s)`} copy="Acompanhe as competências prioritárias e os próximos passos do time." tone="violet"/></section>
    <section className="yb-dashboard-grid"><article className="yb-panel yb-team-panel"><header><div><h2>Meu time em foco</h2><p>{data.employees.length || 8} pessoas no time de Produto</p></div><button onClick={() => onView?.("employee-history")}>Ver detalhes <ArrowRight size={15}/></button></header><div className="yb-team-map"><span className="yb-team-orbit yb-team-orbit--one"/><span className="yb-team-orbit yb-team-orbit--two"/>{people.map((person, index) => <button className={`yb-team-person yb-team-person--${index + 1}`} key={person.id} onClick={() => onView?.("employee-history")}><PersonAvatar name={person.full_name} tone={(["pink", "mint", "violet", "amber", "mint"] as const)[index % 5]} size={index === 2 ? "lg" : "md"}/><b>{index === 0 ? "2" : index === 1 ? "3" : index === 2 ? "3" : "0"}</b><small>{index === 0 ? "em atenção" : index === 1 ? "em evolução" : index === 2 ? "estáveis" : "em risco"}</small></button>)}<blockquote>Pessoas<br/>únicas.<br/>Grandes<br/>resultados<br/>juntos.</blockquote></div></article>
      <article className="yb-panel yb-conversations"><header><div><h2>Conversas e check-ins</h2><p>Acompanhe os momentos mais importantes com seu time.</p></div><button onClick={() => onView?.("checkins")}>Ver agenda <ArrowRight size={15}/></button></header><ListRow count={String(data.checkins.length || 3)} title="1:1 pendentes" detail="Converse, escute, impulsione." tone="pink" onClick={() => onView?.("checkins")}/><ListRow count={String(data.feedbacks.length || 2)} title="Feedbacks pendentes" detail="Dê e peça feedback." tone="amber" onClick={() => onView?.("feedbacks")}/><ListRow count={String(data.assessments.length || 4)} title="Check-ins do ciclo" detail="Acompanhe o progresso de metas." onClick={() => onView?.("feedback-360")}/><ListRow count="2" title="Próximas conversas" detail="esta semana" tone="calendar" onClick={() => onView?.("checkins")}/></article>
      <article className="yb-panel yb-development"><header><div><h2>Desenvolvimento</h2><p>A evolução do seu time em um só lugar.</p></div><button onClick={() => onView?.("pdis")}>Ver trilhas <ArrowRight size={15}/></button></header><ListRow count={`${isDemo ? 68 : competencyProgress}%`} title="PDI da equipe" detail={`${activePdis || 5} de ${data.employees.length || 8} pessoas com PDI ativo`} tone="progress" onClick={() => onView?.("pdis")}/><ListRow title="Trilhas em andamento" detail={`${isDemo ? 6 : activePdis} pessoas em trilhas de desenvolvimento`} onClick={() => onView?.("pdis")}/><ListRow title="Próximos passos" detail={`${isDemo ? 8 : activePdis} ações de desenvolvimento`} onClick={() => onView?.("pdis")}/><div className="yb-development__note"><Sparkles/> Times que aprendem juntos<br/>chegam mais longe.</div></article>
      <article className="yb-panel yb-attention"><header><div><h2>⚠ Pessoas em atenção</h2><p>Colaboradores que podem precisar do seu olhar neste momento.</p></div><button onClick={() => onView?.("employee-history")}>Ver todos <ArrowRight size={15}/></button></header><div className="yb-attention__people">{people.slice(0, 3).map((person, index) => <button key={person.id} onClick={() => onView?.("employee-history")}><PersonAvatar name={person.full_name} tone={(["pink", "amber", "violet"] as const)[index]} size="sm"/><span><strong>{person.full_name}</strong><small>{index === 0 ? "Aumento de demanda nas últimas semanas." : index === 1 ? "Sinais que merecem uma conversa." : "Assumindo novas responsabilidades."}</small></span><em>{index === 0 ? "Risco de sobrecarga" : index === 1 ? "Queda de engajamento" : "Em transição"}</em><ChevronRight size={15}/></button>)}</div></article>
      <article className="yb-panel yb-ask"><header><div><h2><BeeMark small/> Pergunte à Bee sobre seu time</h2><p>Obtenha insights rápidos e práticos para sua liderança.</p></div></header><div className="yb-ask__suggestions">{["Quem precisa de apoio esta semana?", "Onde devo atuar primeiro?", "Quais são os principais pontos de desenvolvimento?", "Como está o clima do meu time?"].map((question) => <button key={question} onClick={() => onSubmitBee?.(question)}><Search size={15}/>{question}<ChevronRight size={15}/></button>)}</div><form onSubmit={askBee}><input value={beeQuestion} onChange={(event) => setBeeQuestion(event.target.value)} aria-label="Pergunte à Bee" placeholder="Faça uma pergunta à Bee..."/><button type="submit" aria-label="Enviar pergunta"><ArrowRight size={17}/></button></form></article>
    </section></main></div>;
}

function MobileManagerHome({ firstName, priorities, onView, onSubmitBee }: { firstName: string; priorities: LeaderPriority[]; onView?: ManagerHomeProps["onView"]; onSubmitBee?: ManagerHomeProps["onSubmitBee"] }) {
  const [active, setActive] = useState("Organizar");
  return <div className="yb-mobile"><header><div className="yb-mobile__brand"><strong>youB</strong><BeeMark small/></div><PersonAvatar name={firstName} size="sm"/></header><label className="yb-mobile__search"><Search/><input aria-label="Busca" placeholder="O que precisa da minha atenção hoje?"/></label><main><h1>Bom dia, {firstName}</h1><h2>Seu dia, organizado pela Bee.</h2><p>Analisei sua agenda, seu time e seus compromissos.</p><nav className="yb-mobile-tabs">{[{name:"Organizar",icon:<MoreHorizontal/>},{name:"Pensar",icon:<BarChart3/>},{name:"Agir",icon:<Target/>}].map((item)=><button type="button" className={active===item.name?"active":""} onClick={()=>setActive(item.name)} key={item.name}>{item.icon}{item.name}</button>)}</nav><button type="button" className="yb-mobile-brief focus-visible:ring-2 sm:block" aria-live="polite"><BeeMark small/><span><span className="sr-only">Confirmação pendente. Proveniência: contexto autorizado. </span>Preciso de 42 segundos seus.</span><ChevronRight/></button><section className="yb-mobile-confirm"><button><CalendarDays/><span>A conversa com Ana continua às 10h?</span><b>Sim</b><em>Não</em></button><button><UsersRound/><span>O acompanhamento do João vai para Pedro?</span><b>Sim</b><em>Não</em></button></section><p className="yb-mobile-label">SUAS PRIORIDADES HOJE</p><section className="yb-mobile-priorities">{priorities.length ? priorities.map((item,index)=><button key={`${item.title}-${index}`} onClick={()=>onView?.(item.kind === "decidir" ? "pdis" : "feedbacks")}><b>{index+1}</b><span>{item.title}</span><small><Clock3/>{index===0?"10h":index===1?"11h30":"16h"}</small><ChevronRight/></button>) : <div className="yb-mobile-empty">Nenhuma prioridade requer sua atenção agora.</div>}</section><section className="yb-mobile-actions"><button onClick={()=>onSubmitBee?.("Quais líderes emergentes merecem atenção?")}><span><BarChart3/> Pensar</span><strong>Insight em atenção:<br/>líderes emergentes</strong><small>Dois nomes se destacaram nas últimas semanas.</small></button><button onClick={()=>onSubmitBee?.("O que você pode fazer por mim?")}><span><Target/> Agir</span><strong>Posso fazer por você</strong><small>Preparar mensagem para Ana</small><small>Reorganizar sua manhã</small></button></section><button className="yb-mobile-bee" onClick={()=>onSubmitBee?.("Conversar com a Bee")}><BeeMark small/><span>Pergunte à Bee</span><b>Conversar <ArrowRight/></b></button></main><nav className="yb-mobile-bottom">{[{label:"Início",icon:<Sparkles/>},{label:"Agenda",icon:<CalendarDays/>},{label:"Time",icon:<UsersRound/>},{label:"Insights",icon:<BarChart3/>},{label:"Mais",icon:<MoreHorizontal/>}].map((item,index)=><button className={index===0?"active":""} key={item.label}>{item.icon}<span>{item.label}</span></button>)}</nav></div>;
}

export default function ManagerHome({ displayName, organizationName, beeContext, data, ambient, onView, onSubmitBee }: ManagerHomeProps) {
  const firstName = displayName.split(" ")[0];
  const priorities = useMemo(() => ambient ? ambientBriefPriorities(ambient.brief) : leaderPriorities(data), [ambient, data]);
  function submitBee(message: string) { if (ambient) ambientBeeResponse(ambient, message); onSubmitBee?.(message); }
  return <div className="yb-approved-home"><DesktopManagerHome firstName={firstName} organizationName={organizationName} data={data} onView={onView} onSubmitBee={submitBee}/><MobileManagerHome firstName={firstName} priorities={priorities} onView={onView} onSubmitBee={submitBee}/></div>;
}

export function ManagerHomePreview() {
  return <ManagerHome displayName="Alex Martins" organizationName="Organização de preview" beeContext={{ userName: "Alex Martins", organizationName: "Organização de preview", role: "gestor", capabilities: ["read:team-scope", "recommend:review-only"], employeeLinked: true, screen: "manager-home-preview" }} data={{ employees: [{ id: "mariana", full_name: "Mariana Costa" }, { id: "rafael", full_name: "Rafael Lima" }, { id: "beatriz", full_name: "Beatriz Santos" }, { id: "ana", full_name: "Ana Souza" }, { id: "joao", full_name: "João Silva" }], feedbacks: [{ id: "feedback", target_employee_id: "mariana", created_at: "2026-09-14", content: "Clareza de expectativas" }], pdis: [{ id: "pdi", objective: "Delegação", status: "active", employee_id: "ana", due_date: "2026-09-19" }], checkins: [{ id: "checkin", employee_id: "rafael", checkin_date: "2026-09-13", note: null }], assessments: [] }} ambient={createAmbientDemoReadModel()}/>;
}
