-- Recommendation and Intervention V1 constraints. Structural only.
do $$ begin
 if not exists(select 1 from pg_constraint where conname='recommendations_type_v1_check') then alter table public.intelligence_recommendations add constraint recommendations_type_v1_check check(recommendation_type is null or recommendation_type in('investigate','intervene','maintain','replicate','monitor','no_action')); end if;
 if not exists(select 1 from pg_constraint where conname='recommendations_scope_type_v1_check') then alter table public.intelligence_recommendations add constraint recommendations_scope_type_v1_check check(scope_type is null or scope_type in('employee','team','area','position','process','unit','organization')); end if;
 if not exists(select 1 from pg_constraint where conname='recommendations_evidence_state_v1_check') then alter table public.intelligence_recommendations add constraint recommendations_evidence_state_v1_check check(evidence_state is null or evidence_state in('insufficient','moderate','strong')); end if;
 if not exists(select 1 from pg_constraint where conname='recommendations_insufficient_intervene_v1_check') then alter table public.intelligence_recommendations add constraint recommendations_insufficient_intervene_v1_check check(evidence_state is distinct from 'insufficient' or recommendation_type is null or recommendation_type in('investigate','monitor','no_action')); end if;
 if not exists(select 1 from pg_constraint where conname='recommendations_cost_currency_v1_check') then alter table public.intelligence_recommendations add constraint recommendations_cost_currency_v1_check check((estimated_cost is null and currency is null) or(estimated_cost is not null and estimated_cost>=0 and currency is not null and length(btrim(currency))>0)); end if;
 if not exists(select 1 from pg_constraint where conname='recommendations_unknowns_array_v1_check') then alter table public.intelligence_recommendations add constraint recommendations_unknowns_array_v1_check check(jsonb_typeof(unknowns)='array'); end if;
 if not exists(select 1 from pg_constraint where conname='recommendations_alternatives_array_v1_check') then alter table public.intelligence_recommendations add constraint recommendations_alternatives_array_v1_check check(jsonb_typeof(alternatives)='array'); end if;
 if not exists(select 1 from pg_constraint where conname='recommendations_do_not_recommend_array_v1_check') then alter table public.intelligence_recommendations add constraint recommendations_do_not_recommend_array_v1_check check(jsonb_typeof(do_not_recommend)='array'); end if;
 if not exists(select 1 from pg_constraint where conname='recommendations_measurement_plan_object_v1_check') then alter table public.intelligence_recommendations add constraint recommendations_measurement_plan_object_v1_check check(jsonb_typeof(measurement_plan)='object'); end if;
 if not exists(select 1 from pg_constraint where conname='recommendations_context_object_v1_check') then alter table public.intelligence_recommendations add constraint recommendations_context_object_v1_check check(jsonb_typeof(context)='object'); end if;
 if not exists(select 1 from pg_constraint where conname='interventions_family_v1_check') then alter table public.intelligence_interventions add constraint interventions_family_v1_check check(intervention_family is null or intervention_family in('investigation','learning','mentoring','coaching','leadership','process','work_design','communication','recognition','career','succession','mobility','structure','people_practice','consulting','none')); end if;
 if not exists(select 1 from pg_constraint where conname='interventions_target_scope_type_v1_check') then alter table public.intelligence_interventions add constraint interventions_target_scope_type_v1_check check(target_scope_type is null or target_scope_type in('employee','team','area','position','process','unit','organization')); end if;
 if not exists(select 1 from pg_constraint where conname='interventions_dates_v1_check') then alter table public.intelligence_interventions add constraint interventions_dates_v1_check check(starts_at is null or expected_end_at is null or expected_end_at>=starts_at); end if;
 if not exists(select 1 from pg_constraint where conname='interventions_cost_currency_v1_check') then alter table public.intelligence_interventions add constraint interventions_cost_currency_v1_check check((estimated_cost is null and currency is null) or(estimated_cost is not null and estimated_cost>=0 and currency is not null and length(btrim(currency))>0)); end if;
 if not exists(select 1 from pg_constraint where conname='interventions_success_criteria_array_v1_check') then alter table public.intelligence_interventions add constraint interventions_success_criteria_array_v1_check check(jsonb_typeof(success_criteria)='array'); end if;
 if not exists(select 1 from pg_constraint where conname='interventions_measurement_plan_object_v1_check') then alter table public.intelligence_interventions add constraint interventions_measurement_plan_object_v1_check check(jsonb_typeof(measurement_plan)='object'); end if;
 if not exists(select 1 from pg_constraint where conname='interventions_context_object_v1_check') then alter table public.intelligence_interventions add constraint interventions_context_object_v1_check check(jsonb_typeof(context)='object'); end if;
end $$;
