import type { SupabaseSession } from "../../lib/supabase";
import type { BeeActionRequest, IntelligenceAction, IntelligenceEvidence, IntelligenceIntervention, IntelligenceOutcome, IntelligenceReadContext, IntelligenceRecommendation, IntelligenceSignal, KnowledgeDocument, KnowledgeSource, OrganizationalEvent, OrganizationalMemoryRelation, IntelligenceDecision, IntelligenceDecisionIntervention, IntelligenceDecisionRevision, IntelligenceOrganizationalReading, IntelligenceOrganizationalReadingSource, IntelligenceOrganizationalReadingHypothesis, IntelligenceOrganizationalReadingRevision, IntelligenceEvidenceAssessment, IntelligenceEvidenceAssessmentEvidence, IntelligenceEvidenceAssessmentRevision, IntelligenceRecommendationReading, IntelligenceRecommendationAssessment, IntelligenceRecommendationHypothesis, IntelligenceRecommendationEvidence, IntelligenceRecommendationRevision } from "./types";

const viteEnv = (import.meta as ImportMeta & { env?: Record<string, unknown> }).env ?? {};
const supabaseUrl = (viteEnv.VITE_SUPABASE_URL as string | undefined)?.replace(/\/$/, "");
const supabaseAnonKey = viteEnv.VITE_SUPABASE_ANON_KEY as string | undefined;
type TableMap = { intelligence_signals: IntelligenceSignal; intelligence_evidence: IntelligenceEvidence; intelligence_recommendations: IntelligenceRecommendation; intelligence_interventions: IntelligenceIntervention; intelligence_actions: IntelligenceAction; intelligence_outcomes: IntelligenceOutcome; bee_action_requests: BeeActionRequest; knowledge_sources: KnowledgeSource; knowledge_documents: KnowledgeDocument; organizational_memory_relations: OrganizationalMemoryRelation; organizational_events: OrganizationalEvent; intelligence_decisions: IntelligenceDecision; intelligence_decision_interventions: IntelligenceDecisionIntervention; intelligence_decision_revisions: IntelligenceDecisionRevision; intelligence_organizational_readings: IntelligenceOrganizationalReading; intelligence_organizational_reading_sources: IntelligenceOrganizationalReadingSource; intelligence_organizational_reading_hypotheses: IntelligenceOrganizationalReadingHypothesis; intelligence_organizational_reading_revisions: IntelligenceOrganizationalReadingRevision; intelligence_evidence_assessments: IntelligenceEvidenceAssessment; intelligence_evidence_assessment_evidence: IntelligenceEvidenceAssessmentEvidence; intelligence_evidence_assessment_revisions: IntelligenceEvidenceAssessmentRevision; intelligence_recommendation_readings: IntelligenceRecommendationReading; intelligence_recommendation_assessments: IntelligenceRecommendationAssessment; intelligence_recommendation_hypotheses: IntelligenceRecommendationHypothesis; intelligence_recommendation_evidence: IntelligenceRecommendationEvidence; intelligence_recommendation_revisions: IntelligenceRecommendationRevision };
function requireConfig(): { url: string; key: string } { if (!supabaseUrl || !supabaseAnonKey) throw new Error("O ambiente ainda não está conectado ao Supabase."); return { url: supabaseUrl, key: supabaseAnonKey }; }
function encode(value: string): string { return encodeURIComponent(value); }
async function readTable<T extends keyof TableMap>(context: IntelligenceReadContext, table: T, select: string, extra = ""): Promise<TableMap[T][]> { const config = requireConfig(); const query = `select=${encode(select)}&organization_id=eq.${encode(context.organizationId)}${extra}`; const response = await fetch(`${config.url}/rest/v1/${table}?${query}`, { headers: { apikey: config.key, Authorization: `Bearer ${context.session.access_token}` } }); const body: unknown = await response.json().catch(() => null); if (!response.ok) throw new Error("Não foi possível carregar este conteúdo agora."); return (body ?? []) as TableMap[T][]; }
const selects = {
  signals: "id,organization_id,employee_id,signal_type,signal_family,signal_nature,scope_type,scope_ref,direction,persistence,impact_level,sensitivity,window_start,window_end,context,observed_at,value,source_type,source_id,status,created_by,created_at,updated_at",
  evidence: "id,organization_id,signal_id,evidence_type,summary,payload,source_type,source_id,observed_at,relation,independence_group,created_by,created_at,updated_at",
  recommendations: "id,organization_id,employee_id,title,rationale,status,source_evidence_ids,recommendation_type,scope_type,scope_ref,evidence_state,problem_statement,unknowns,recommended_intervention_type,alternatives,do_not_recommend,expected_outcome,measurement_plan,estimated_cost,currency,owner_employee_id,approval_required,approved_by,approved_at,follow_up_at,context,created_by,reviewed_by,reviewed_at,created_at,updated_at",
  interventions: "id,organization_id,recommendation_id,employee_id,intervention_type,intervention_family,title,plan,objective,target_scope_type,target_scope_ref,success_criteria,measurement_plan,estimated_cost,currency,starts_at,expected_end_at,follow_up_at,requires_human_approval,context,status,owner_employee_id,created_by,approved_by,approved_at,created_at,updated_at",
  actions: "id,organization_id,intervention_id,action_type,title,details,status,assignee_employee_id,due_at,completed_at",
  outcomes: "id,organization_id,intervention_id,action_id,outcome_type,status,details,measured_at,outcome_level,claim_strength,measurement_kind,validation_status,metric_key,metric_label,metric_unit,baseline_value,observed_value,delta_value,baseline_at,window_start,window_end,data_source_type,data_source_id,measurement_methodology,attribution_note,financial_value,currency,validated_by,validated_at,context",
  beeActionRequests: "id,organization_id,requester_user_id,requester_employee_id,source_recommendation_id,source_intervention_id,source_action_id,action_key,capability_level,risk_level,authorization_requirement,purpose,target_scope_type,target_scope_ref,target_employee_id,sensitivity,authorization_status,execution_status,confirmed_by,confirmed_at,approved_by,approved_at,request_payload,execution_payload,execution_result,failure_reason,correlation_id,executed_at,created_at,updated_at",
  sources: "id,organization_id,source_type,name,owner_user_id,access_level,status",
  documents: "id,organization_id,knowledge_source_id,document_type,title,version,status,valid_from,valid_until,content,storage_path,access_level,owner_user_id",
  organizationalMemoryRelations: "id,organization_id,source_entity_type,source_entity_id,target_entity_type,target_entity_id,relationship_type,knowledge_kind,valid_from,valid_until,recorded_at,source_type,source_id,sensitivity,context,created_at",
  organizationalEvents: "id,organization_id,event_type,entity_type,entity_id,related_entity_type,related_entity_id,occurred_at,recorded_at,source_type,source_id,actor_user_id,sensitivity,payload,correlation_id,created_at",
  decisions: "id,organization_id,decision_type,scope_type,scope_ref,recommendation_id,decision_statement,selected_option,alternatives_considered,rationale,evidence_snapshot,unknowns,risk_level,risk_accepted,status,owner_employee_id,decision_maker_user_id,approval_required,required_approver_role,approved_by,approved_at,effective_at,review_at,supersedes_decision_id,context,created_at,updated_at",
  decisionInterventions: "id,organization_id,decision_id,intervention_id,relationship_type,context,created_at",
  decisionRevisions: "id,organization_id,decision_id,revision_number,changed_by_user_id,change_reason,previous_snapshot,new_snapshot,created_at",
  organizationalReadings: "id,organization_id,reading_type,scope_type,scope_ref,title,description,status,knowledge_kind,observation_window_start,observation_window_end,detected_at,source_summary,context,created_at,updated_at",
  organizationalReadingSources: "id,organization_id,reading_id,source_type,evidence_id,knowledge_source_id,knowledge_document_id,organizational_event_id,memory_relation_id,relationship_type,provenance_note,context,created_at",
  organizationalReadingHypotheses: "id,organization_id,reading_id,hypothesis_statement,status,knowledge_kind,context,created_by,created_at,updated_at",
  organizationalReadingRevisions: "id,organization_id,reading_id,revision_number,changed_by_user_id,change_reason,previous_snapshot,new_snapshot,created_at",
  evidenceAssessments: "id,organization_id,reading_id,hypothesis_id,status,evidence_state,supporting_evidence_count,contradicting_evidence_count,unknowns,limitations,assessment_summary,assessed_by_user_id,assessed_at,context,created_at,updated_at",
  assessmentEvidence: "id,organization_id,assessment_id,evidence_id,evidence_relation,provenance_note,context,created_at",
  assessmentRevisions: "id,organization_id,assessment_id,revision_number,changed_by_user_id,change_reason,previous_snapshot,new_snapshot,created_at",
  recommendationReadings: "id,organization_id,recommendation_id,reading_id,relationship_type,context,created_at",
  recommendationAssessments: "id,organization_id,recommendation_id,assessment_id,relationship_type,context,created_at",
  recommendationHypotheses: "id,organization_id,recommendation_id,hypothesis_id,relationship_type,context,created_at",
  recommendationEvidence: "organization_id,recommendation_id,evidence_id,evidence_relation,context,created_at",
  recommendationRevisions: "id,organization_id,recommendation_id,revision_number,changed_by_user_id,change_reason,previous_snapshot,new_snapshot,created_at",
} as const;
export const readSignals = (context: IntelligenceReadContext) => readTable(context, "intelligence_signals", selects.signals, context.employeeId ? `&employee_id=eq.${encode(context.employeeId)}` : "");
export const readEvidence = (context: IntelligenceReadContext) => readTable(context, "intelligence_evidence", selects.evidence);
export const readRecommendations = (context: IntelligenceReadContext) => readTable(context, "intelligence_recommendations", selects.recommendations, context.employeeId ? `&employee_id=eq.${encode(context.employeeId)}` : "");
export const readInterventions = (context: IntelligenceReadContext) => readTable(context, "intelligence_interventions", selects.interventions, context.employeeId ? `&employee_id=eq.${encode(context.employeeId)}` : "");
export const readActions = (context: IntelligenceReadContext) => readTable(context, "intelligence_actions", selects.actions, context.employeeId ? `&assignee_employee_id=eq.${encode(context.employeeId)}` : "");
export const readOutcomes = (context: IntelligenceReadContext) => readTable(context, "intelligence_outcomes", selects.outcomes);
export const readBeeActionRequests = (context: IntelligenceReadContext) => readTable(context, "bee_action_requests", selects.beeActionRequests);
export const readKnowledgeSources = (context: IntelligenceReadContext) => readTable(context, "knowledge_sources", selects.sources, "&status=eq.active");
export const readOrganizationalMemoryRelations = (context: IntelligenceReadContext) => readTable(context, "organizational_memory_relations", selects.organizationalMemoryRelations, "&order=valid_from.desc");
export const readOrganizationalEvents = (context: IntelligenceReadContext) => readTable(context, "organizational_events", selects.organizationalEvents, "&order=occurred_at.desc,recorded_at.desc");
export const readDecisions = (context: IntelligenceReadContext) => readTable(context, "intelligence_decisions", selects.decisions, "&order=created_at.desc");
export const readDecisionInterventions = (context: IntelligenceReadContext) => readTable(context, "intelligence_decision_interventions", selects.decisionInterventions, "&order=created_at.desc");
export const readDecisionRevisions = (context: IntelligenceReadContext) => readTable(context, "intelligence_decision_revisions", selects.decisionRevisions, "&order=decision_id.asc,revision_number.desc");
export const readOrganizationalReadings = (context: IntelligenceReadContext) => readTable(context, "intelligence_organizational_readings", selects.organizationalReadings, "&order=detected_at.desc");
export const readOrganizationalReadingSources = (context: IntelligenceReadContext) => readTable(context, "intelligence_organizational_reading_sources", selects.organizationalReadingSources, "&order=created_at.desc");
export const readOrganizationalReadingHypotheses = (context: IntelligenceReadContext) => readTable(context, "intelligence_organizational_reading_hypotheses", selects.organizationalReadingHypotheses, "&order=created_at.desc");
export const readOrganizationalReadingRevisions = (context: IntelligenceReadContext) => readTable(context, "intelligence_organizational_reading_revisions", selects.organizationalReadingRevisions, "&order=reading_id.asc,revision_number.desc");
export const readEvidenceAssessments = (context: IntelligenceReadContext) => readTable(context, "intelligence_evidence_assessments", selects.evidenceAssessments, "&order=created_at.desc");
export const readAssessmentEvidence = (context: IntelligenceReadContext) => readTable(context, "intelligence_evidence_assessment_evidence", selects.assessmentEvidence, "&order=created_at.desc");
export const readAssessmentRevisions = (context: IntelligenceReadContext) => readTable(context, "intelligence_evidence_assessment_revisions", selects.assessmentRevisions, "&order=assessment_id.asc,revision_number.desc");
export const readRecommendationReadings = (context: IntelligenceReadContext) => readTable(context, "intelligence_recommendation_readings", selects.recommendationReadings, "&order=created_at.desc");
export const readRecommendationAssessments = (context: IntelligenceReadContext) => readTable(context, "intelligence_recommendation_assessments", selects.recommendationAssessments, "&order=created_at.desc");
export const readRecommendationHypotheses = (context: IntelligenceReadContext) => readTable(context, "intelligence_recommendation_hypotheses", selects.recommendationHypotheses, "&order=created_at.desc");
export const readRecommendationEvidence = (context: IntelligenceReadContext) => readTable(context, "intelligence_recommendation_evidence", selects.recommendationEvidence, "&order=created_at.desc");
export const readRecommendationRevisions = (context: IntelligenceReadContext) => readTable(context, "intelligence_recommendation_revisions", selects.recommendationRevisions, "&order=recommendation_id.asc,revision_number.desc");
export const readKnowledgeDocuments = (context: IntelligenceReadContext) => { const today = encode(new Date().toISOString().slice(0, 10)); return readTable(context, "knowledge_documents", `${selects.documents},knowledge_sources!inner(status)`, `&status=eq.published&and=(or(valid_from.is.null,valid_from.lte.${today}),or(valid_until.is.null,valid_until.gt.${today}))&knowledge_sources.status=eq.active`); };

export type EmployeeHomeAssessment = { id: string; cycle_id: string; status: string; position_id?: string | null; created_at: string; completed_at?: string | null };
export type EmployeeHomeAssessmentScore = { id: string; assessment_id: string; competency_id: string; expected_level_snapshot: number; score?: number | null; evidence_note?: string | null };
export type EmployeeHomeData = { pdis: Array<{ id: string; objective: string; status: string; due_date?: string | null }>; checkins: Array<{ id: string; checkin_date: string; mood: number; engagement: number; energy: number; workload: number; note?: string | null }>; actions: IntelligenceAction[]; assessments: EmployeeHomeAssessment[]; assessmentScores: EmployeeHomeAssessmentScore[]; competencies: Array<{ id: string; name: string }> };
async function safeLegacyRead<T>(context: IntelligenceReadContext, table: string, select: string, filters: string): Promise<T[]> { try { const config = requireConfig(); const query = `select=${encode(select)}&organization_id=eq.${encode(context.organizationId)}&${filters}`; const response = await fetch(`${config.url}/rest/v1/${table}?${query}`, { headers: { apikey: config.key, Authorization: `Bearer ${context.session.access_token}` } }); if (!response.ok) return []; return (await response.json()) as T[]; } catch { return []; } }
export async function readEmployeeHomeData(context: IntelligenceReadContext): Promise<EmployeeHomeData> {
  if (!context.employeeId) return { pdis: [], checkins: [], actions: [], assessments: [], assessmentScores: [], competencies: [] };
  const employee = encode(context.employeeId);
  const [pdis, checkins, actions, assessments, competencies] = await Promise.all([
    safeLegacyRead<EmployeeHomeData["pdis"][number]>(context, "pdis", "id,objective,status,due_date", `employee_id=eq.${employee}`),
    safeLegacyRead<EmployeeHomeData["checkins"][number]>(context, "checkins", "id,checkin_date,mood,engagement,energy,workload,note", `employee_id=eq.${employee}&order=checkin_date.desc&limit=1`),
    readActions(context).catch(() => [] as IntelligenceAction[]),
    safeLegacyRead<EmployeeHomeAssessment>(context, "assessments", "id,cycle_id,status,position_id,created_at,completed_at", `subject_employee_id=eq.${employee}&status=eq.completed&order=completed_at.desc`),
    safeLegacyRead<{ id: string; name: string }>(context, "competencies", "id,name", "order=name"),
  ]);
  const ids = assessments.map((assessment) => assessment.id);
  const assessmentScores = ids.length ? await safeLegacyRead<EmployeeHomeAssessmentScore>(context, "assessment_competency_scores", "id,assessment_id,competency_id,expected_level_snapshot,score,evidence_note", `assessment_id=in.(${ids.map(encode).join(",")})`) : [];
  return { pdis, checkins, actions, assessments, assessmentScores, competencies };
}
export async function readIntelligenceFoundation(context: IntelligenceReadContext) { const [signals, evidence, recommendations, interventions, actions, outcomes, beeActionRequests, knowledgeSources, knowledgeDocuments, organizationalMemoryRelations, organizationalEvents, decisions, decisionInterventions, decisionRevisions, organizationalReadings, organizationalReadingSources, organizationalReadingHypotheses, organizationalReadingRevisions, evidenceAssessments, assessmentEvidence, assessmentRevisions, recommendationReadings, recommendationAssessments, recommendationHypotheses, recommendationEvidence, recommendationRevisions] = await Promise.all([readSignals(context), readEvidence(context), readRecommendations(context), readInterventions(context), readActions(context), readOutcomes(context), readBeeActionRequests(context), readKnowledgeSources(context), readKnowledgeDocuments(context), readOrganizationalMemoryRelations(context), readOrganizationalEvents(context), readDecisions(context), readDecisionInterventions(context), readDecisionRevisions(context), readOrganizationalReadings(context), readOrganizationalReadingSources(context), readOrganizationalReadingHypotheses(context), readOrganizationalReadingRevisions(context), readEvidenceAssessments(context), readAssessmentEvidence(context), readAssessmentRevisions(context), readRecommendationReadings(context), readRecommendationAssessments(context), readRecommendationHypotheses(context), readRecommendationEvidence(context), readRecommendationRevisions(context)]); return { signals, evidence, recommendations, interventions, actions, outcomes, beeActionRequests, knowledgeSources, knowledgeDocuments, organizationalMemoryRelations, organizationalEvents, decisions, decisionInterventions, decisionRevisions, organizationalReadings, organizationalReadingSources, organizationalReadingHypotheses, organizationalReadingRevisions, evidenceAssessments, assessmentEvidence, assessmentRevisions, recommendationReadings, recommendationAssessments, recommendationHypotheses, recommendationEvidence, recommendationRevisions }; }
export type { SupabaseSession };
